ManifoldScholar/manifold

.hound.yml
.scss-lint.yml

A configuration yml has been added to trigger a custom configuration of
scss-lint. This initial configuration is based on a combination of
established standards and also Cast Iron Coding house style. Notably
the style for variables, mixins, and functions all follow standard JS
convention (camelcase). We are also trying out recess CSS order.
This initial config is not final, and may be modified after a few
rounds of commits.

[C] Configured scss linting for Hound CI

---

.hound.yml
client/src/actions/reader/ui/typography.js
client/src/components/reader/AppearanceMenuBody.js
client/src/components/reader/Header.js
client/src/containers/reader/Reader.js
client/src/containers/reader/Section.js
client/src/store/reducers/ui/__tests__/typography-test.js
client/src/store/reducers/ui/typography.js
client/src/theme/Components/_shared.scss
client/src/theme/Components/reader/_appearance-menu.scss
client/src/theme/STACSS/_structure.scss
client/src/theme/_variables.scss
client/src/theme/assets/svg/fonts/manicon/margins-narrow-arrows.svg
client/src/theme/assets/svg/fonts/manicon/margins-narrow-text.svg
client/src/theme/assets/svg/fonts/manicon/margins-wide-arrows.svg
client/src/theme/assets/svg/fonts/manicon/margins-wide-text.svg

[FEATURE DELIVERS #111080632] New actions have been added to increment/
decrement margin values in the store, that use a now-abstracted version
of the font-size increment/decrement reducers. In the view, there are
now buttons to increase/decrease the margin size in the reader. It's
important to note that while these buttons do not have disabled states
for minimum and maximum sizes, they do stop changing the store when a
limit is reached.

[F] Add margin controls to reader

---

client/src/components/reader/SectionPagination.js
client/src/components/reader/index.js
client/src/containers/reader/Reader.js
client/src/theme/Components/reader/_index.scss
client/src/theme/Components/reader/_section-pagination.scss
client/src/theme/assets/svg/fonts/manicon/arrow-left.svg
client/src/theme/assets/svg/fonts/manicon/arrow-right.svg
client/src/theme/assets/svg/fonts/manicon/arrow-round-left.svg
client/src/theme/assets/svg/fonts/manicon/arrow-round-right.svg

Add pagination to text-sections
[FEATURE DELIVERS #112835767] Feature adds functional "Previous" and
"Next" buttons to text-sections. The buttons link to paths generated
based on the current section and the existence of previous and next
sections in the table of contents.

Add pagination to text-sections

---

client/src/theme/STACSS/_appearance.scss

[BUGFIX FIXES #110890746] We can use the autoprefixed "appearance"
property to ensure that select arrows are removed on all modern
browsers. This change also forces the "pointer" cursor on styled select
elements.

[B] Fix select element cross-browser appearance

---

client/src/components/reader/Header.js
client/src/theme/Components/browse/_header-browse.scss
client/src/theme/Components/reader/_header-reader.scss
client/src/theme/STACSS/_appearance.scss

[FEATURE DELIVERS #113763363] In addition to swapping banner gradient
colors for the reader when it is in "dark mode," the banner gradient
has also been refactored as a DOM element (instead of a pseudo element)
and removed from the browse/frontend interface. In its place, a thin
border is used for now, but it should be noted that this is awaiting
approval from design.

[F] Change text-fade on reader dark color scheme

---

client/src/components/reader/Header.js
client/src/components/reader/TextTitles.js
client/src/components/reader/index.js
client/src/components/shared/higherOrder/scrollAware.js
client/src/containers/reader/Reader.js
client/src/theme/Components/reader/_header-reader.scss

Initial Commit:
[FEATURE DELIVERS #112837675] In the reader, the header banner now
shows the title of the text-section after the user begins to scroll
down into the reader. The design logic behind this is that the user
almost always sees the section title when the reader is at the top of a
given section, so showing the text title gives the most context. Once
the user is further into the section, we switch to the section title to
provide a persistent reminder of the user's location in the TOC.
From a front-end standpoint, this section title is always in the markup
and the swap happens with a CSS translateX function.
In addition to this markup, a layout bug has also been addressed which
ensures that the titles are truncated if they are longer than their
allotted space.
It should be noted …

[F] Show section title when user scrolls down

---

client/src/containers/frontend/Frontend.js
client/src/routes.js

[FEATURE #115350089] In addition to adding a min-height on all
Frontend pages, this commit also sets the 404 page/error pages to load
as children of the "Frontend" route, giving them the site-wide header/
footer templates.

[F] Set min-height to create sticky footer

---

client/src/components/frontend/Resource/Card.js
client/src/theme/Components/browse/resource/_card.scss

BUGFIX FIXES #134523515
Previously, there were multiple link targets inside the right hand info
area of the resource card. Now, the entire right side area is clickable
and will take the user to the resource detail. While tags are not yet
supported, provisional markup/JS has been made to handle tags that can
sit above the resource card and override the link behavior of the card
to take the user to a tag detail view.

[B] Fix resource card linking

---

client/src/components/global/HigherOrder/ResolveDataDependencies.js
client/src/components/reader/Section/Text.js
client/src/containers/reader/Reader.js
client/src/utils/entityUtils.js

This commit makes a significant change to how the reader fetches data.
With the reader we don’t want to trigger fetchData when hashes in the
URL change. This may not be a long-term change. The bigger problem is
a question of how we pass a new location to components rendered by the
router without triggering a new fetchData call. This doesn’t address that
problem per se, but does provide a work around for the time being.

Hash anchors only work after refreshing [#138746857]

---

client/src/components/backend/Drawer/Wrapper.js
client/src/components/global/Utility/ScrollLock.js
client/src/components/global/Utility/index.js
client/src/components/reader/TocDrawer.js
client/src/theme/Components/backend/_drawer.scss
client/src/theme/Components/reader/_toc-drawer.scss

[#139240881]
Initial POC converted to use the TOC; See TocDrawer.js
Note that the HOC (ScrollLock.js) is manipulating the direct child with
a ref, but it might be better if the child can pass a specific ref into
the HOC for cases where the scrolling element may be more deeply nested
(like on a resource drawer inside a ReactCSSTransition)

Prevent scroll propagation if the cursor is over the drawer. [#139240881]

---

client/src/store/reducers/ui/__tests__/loading-test.js
client/src/store/reducers/ui/loading.js

Sometimes, especially in local development environments, a STOP_LOADING
action can be reduced before the corresponding START_LOADING action is
reduced. This leads to a START_LOADING that never stops. This revision
stores STOP_LOADING actions in a pending queue in the store, which
blocks the corresopnding START_LOADING action from being added to the
active loaders
[Delivers #142145903]

In some cases, a stop loading action is being resolved before a start loading action, which leads to infinite load states. [#142145903]

---

client/src/components/reader/Annotation/Popup/Annotate.js
client/src/components/reader/Annotation/Popup/Share.js
client/src/components/reader/Annotation/Popup/SocialButtons.js
client/src/theme/Components/reader/_annotation-popup.scss

This is a minor fix to add some of the more complex hover styles back to the annotation popup. Because some of the buttons are in groups, we can't use simple sibling selectors to highlight the tail when the button next to it is hovered.

[C] Add explicit tail-hover to popup buttons

---

api/app/models/collection_resource.rb
api/app/serializers/collection_serializer.rb
api/db/migrate/20170425220220_add_counter_cache_to_collection.rb
api/db/schema.rb
client/src/components/frontend/ResourceCollection/Detail.js
client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
client/src/components/frontend/ResourceList/Totals.js
client/src/components/frontend/ResourceList/__tests__/Totals-test.js
client/src/components/frontend/ResourceList/__tests__/__snapshots__/Totals-test.js.snap

[B] Fix resource count for collections

---

client/src/theme/Components/backend/_vertical-list.scss

[Fixes #313]
Preview of active state without drawer:

[B] Bump active background on BE list to the right

---

client/src/theme/Components/_base.scss
client/src/theme/Components/backend/_panel.scss

[Fixes #293]
Also auto-hide scrollbars in IE11/Edge

[B] Make BE secondary nav scrollable

---

client/src/containers/global/HigherOrder/RequireRole.js

This updates the HigherOrder.RequireRole container to use react-router's redirect mechanism instead of history.push.

[B] Use react router Redirect in RequireRole

---

api/app/models/concerns/attachments.rb
api/app/serializers/project_partial_serializer.rb
api/db/migrate/20170606175305_add_avatar_meta_to_projects.rb
api/db/schema.rb
client/src/components/frontend/Project/Cover.js

This PR address bug #378, but also includes a usage change.  We previously were using the project's avatar image on the home grid, while it seems we should be looking for Cover -> Avatar -> Placeholder.
[Fixes #378]

[B] Fix project thumbnail usage and style

---

client/src/containers/frontend/Following.js
client/src/containers/frontend/Home.js
client/src/theme/Components/shared/_section-heading.scss

Also includes a CSS fix to move the project filter dropdown when featured projects are not present.  Avoids clipping with Manifold heading image.

Hide featured projects section when there are none

---

client/src/components/frontend/Event/Teaser.js

I added a function to determine this in case there are more event types later.  Let me know if you think it's overkill and would rather a variable be set in render.
Fixes #468

[B] Only open tweet events in new tab

---

client/src/theme/Components/_base.scss
client/src/theme/Components/browse/event/_events.scss
client/src/theme/Components/reader/_text-section.scss
client/src/theme/Components/reader/annotation/_detail.scss
client/src/theme/STACSS/_typography.scss

Fixes wrapping in several places:
- Project grid titles
- Event card titles
- Project text titles
[Fixes #401]

[B] Fix text clipping through container

---

client/src/components/reader/Annotation/Editor.js

Fixes #495
For information about original info/why we're using a timeout:
[https://stackoverflow.com/questions/35522220/react-ref-with-focus-doesnt-work-without-settimeout-my-example#answer-35522475](https://stackoverflow.com/questions/35522220/react-ref-with-focus-doesnt-work-without-settimeout-my-example#answer-35522475)

[B] Focus on textarea when annotation editor mounts

---

client/src/containers/reader/Section.js
client/src/store/reducers/notifications.js

The notification reducer was mutating the initial state, which was
causing notifications to persist between requests to the node
renderer service.
Fixes #504

[B] Fix notification reduce initial state mutation

---

client/src/components/frontend/Layout/ButtonNavigation.js
client/src/components/frontend/Layout/MobileNav.js
client/src/components/frontend/Layout/__tests__/MobileNav-test.js
client/src/containers/frontend/Following.js
client/src/containers/frontend/Home.js
client/src/containers/frontend/__tests__/__snapshots__/Home-test.js.snap
client/src/theme/Components/browse/layout/_button-nav.scss
client/src/theme/STACSS/_structure.scss

Fixes #512
Also makes footer nav active states to be more specific to prevent "Projects" being active on featured page.

[B] Don't show page nav buttons at mobile sizes

---

client/src/components/global/SignInUp/Create.js
client/src/components/global/SignInUp/Login.js
client/src/components/global/SignInUp/Overlay.js
client/src/components/global/SignInUp/PasswordForgot.js
client/src/components/global/SignInUp/__tests__/Create-test.js
client/src/components/global/SignInUp/__tests__/Login-test.js
client/src/components/global/SignInUp/__tests__/PasswordForgot-test.js

Fixes #473 
This bug was caused by the component updating after it's props changed before the `hideSignInUpOverlay` function was called.  There is never a case where the component should transition from `login => update` or vice-versa, so we don't have to try and determine which of those to use after it's created.  Instead, we can initialize the component state with the view we want, rather than deferring to the default case of the `renderChild` function.
Additionally, rather than passing down function props for each view change, this commit refactors the `childProps` function to only pass down a single function to handle changing views.

[B] Prevent sign in overlay from updating on authentication

---

client/src/components/frontend/Resource/Detail.js
client/src/components/frontend/Resource/__tests__/__snapshots__/Detail-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/CollectionResourceDetail-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/ResourceDetail-test.js.snap
client/src/containers/global/Comment/Editor.js
client/src/containers/global/Comment/__tests__/__snapshots__/Editor-test.js.snap
client/src/theme/Components/reader/annotation/comment/_editor.scss

Delivers #560 
Note that this feature merges some design styles between the annotation comments and the resource comments. It adds a word-bubble icon to the "Post" button.
An optional label prop has been added that automatically contains a relatively sized pencil icon.
There are some inconsistencies between the resource detail content area and master that were not addressed:
- Publish vs. Post button text (this can be addressed but wasn't part of the issue. Personally I think having separate text for the same function isn't helpful)
- Button Font size (it's a little bigger on the resource detail but I don't think it needs to be)
These are easy to address of course, so let me know if we want to adjust and I can make it part of this PR.

[B] Update comment editor with icons/label

---

client/src/components/frontend/Project/__tests__/__snapshots__/Resources-test.js.snap
client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
client/src/components/frontend/ResourceList/Filters.js
client/src/components/frontend/ResourceList/__tests__/__snapshots__/Filters-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/ProjectResources-test.js.snap
client/src/theme/Components/shared/forms/_list-filter.scss

Starts #556 
This addresses an issue where a dropdown arrow collides with text in the dropdown. That said, the maximum size of this select is small enough on most sizes that the longest text string (in this case "Project Created") still gets cut off. (See screenshot)
It's inevitable for some longer selects to get cut off, but the width of this select group is being truncated due to style used in the resource/collection filter (screenshot 2).
To mitigate this, I've added an inline class that allows the filters to sit aside the search input in just these cases.
Please have a quick QA and let me know if I missed any cases where the inline property needs to be applied.

[B] Update select group input padding

---

client/src/components/backend/Layout/Header.js
client/src/components/backend/Layout/__tests__/__snapshots__/Header-test.js.snap
client/src/components/backend/Navigation/Breadcrumb.js
client/src/components/backend/Navigation/__tests__/__snapshots__/Breadcrumb-test.js.snap
client/src/components/backend/Navigation/__tests__/__snapshots__/DetailHeader-test.js.snap
client/src/containers/backend/CollectionDetail/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/NewCollection/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/NewProject/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/NewResource/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/NewUser/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/ProjectDetail/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/ResourceDetail/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/TextDetail/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
client/src/theme/Components/_header-app.scss
client/src/theme/Components/backend/project/_header.scss
client/src/theme/Components/browse/layout/_footer-browse.scss
client/src/theme/Components/shared/_breadcrumb-primary.scss
client/src/theme/Components/shared/_buttons.scss

This addresses wrapping on project back links and also ports these updates to the backend breadcrumb:

Text wrap by block on back link and breadcrumb

---

client/src/containers/reader/Annotation/Annotatable.js
client/src/theme/Components/reader/_annotation-popup.scss

RESOLVES #637 
After much investigation and experimentation I came upon this little used css property used to stipulate where the background image or color gets clipped in regard to the element's content-box, border-box, padding-box, etc.  I feel like in the mordern-era this distinction is usually moot but in THIS case it ended up being crucial.  Background-clip it is doing the job of never ever letting the background color creep under (gasp) or past (double gasp gasp) the border.  So now it looks all neat and tidy (as it does in other browsers).  Once #678 is fixed this kind of issue should be checked in ie11 too.

[B] Fix annotation popup bugs in ie

---

client/src/components/global/SignInUp/Login.js
client/src/components/global/SignInUp/UpdateForm.js
client/src/components/global/SignInUp/__tests__/__snapshots__/CreateUpdate-test.js.snap
client/src/components/global/SignInUp/__tests__/__snapshots__/Login-test.js.snap
client/src/components/global/SignInUp/__tests__/__snapshots__/Overlay-test.js.snap
client/src/components/global/SignInUp/__tests__/__snapshots__/Update-test.js.snap
client/src/components/global/SignInUp/__tests__/__snapshots__/UpdateForm-test.js.snap
client/src/theme/Components/shared/forms/_form-inputs-primary.scss

This PR also includes a small fix for text inputs.  The placeholder colors in these are darker than the value colors.  After touching base with @naomiyaki, we decided on added a global default value to the `.form-input input` selector for text and password inputs.

[B] Use values instead of placeholders in edit form

---

api/app/services/seed.rb
api/lib/tasks/project.rake

Some of these were failing because they were missing the `args` reference.  Adjusted the others so the style matches.
Fixes #730

[B] Fix project rake task argument references

---

client/src/containers/backend/People/Makers/Edit.js
client/src/containers/backend/People/Makers/List.js
client/src/containers/backend/People/Users/Edit.js
client/src/containers/backend/People/Users/List.js
client/src/containers/backend/People/Wrapper.js
client/src/containers/backend/Project/Texts.js
client/src/containers/backend/Settings/Subjects/List.js
client/src/helpers/router/DrawerSwitch.js
client/src/helpers/router/Passthrough.js
client/src/helpers/router/childRoutes.js
client/src/helpers/router/index.js
client/src/helpers/router/switchFactory.js
client/src/routes.js

This commit adds a new method for rendering child routes from a
component, and refactors just enough of Manifold to serve as
proof of concept. We will need to remove all calls to our
renderRoutes helper and replace them with calls to the new
childRoutes helper.
Closes #737

[F] Refactor child route rendering

---

api/app/controllers/concerns/validation.rb
api/app/models/concerns/with_parsed_name.rb
client/src/components/backend/Maker/ListItem.js
client/src/components/backend/Maker/__tests__/__snapshots__/ListItem-test.js.snap
client/src/containers/backend/Form/Collaborators.js
client/src/containers/backend/People/Makers/Edit.js
client/src/containers/backend/People/Makers/__tests__/__snapshots__/List-test.js.snap

This was an issue with non-human name parts causing errors on Maker create.  The Namae gem uses capital letters to delineate name parts and assigns mid-name lowercase words to `:particle`.  This PR maps `:particle` to `:middle_name`.  
The name parsing seems like it may be an ever-evolving issue, though I think we're still in a better starting position here than our previous splitting methods.
Fixes #766

[B] Fix non-human name parsing

---

client/src/components/reader/Notation/Marker.js
client/src/components/reader/Notation/__tests__/__snapshots__/Marker-test.js.snap
client/src/theme/Components/reader/_text-section.scss
client/src/theme/Components/reader/notation/_marker.scss

Closes #636 
This replaces the long standing inline `&nbsp` with svg background with an icon-font glyph nested in an inline-flex span element. This seems to work great in all contexts and is a cleaner strategy overall that uses color transitions instead of swapping svgs. The icons look crisper and aren't cut off in Edge or Chrome.

[B] Swap resource cube inline svgs for icon font

---

api/app/jobs/update_citatable_children.rb
api/app/models/concerns/citable.rb

Fixes #802 
We still have to use the `after_save` callback instead of `after_commit` so we can compare the citations to know if we should update the children or not. Let me know if you want to look at changing that so we can use the `after_commit` callback instead.

[B] Move citable children update to a job

---

api/spec/services/validator/html_spec.rb

Previous verisons of Loofah/Nokogiri were not converting ASCII encoded
content to UTF8 as we'd expect them to. Recent updates to these
libraries also included updates to libxml, and the behavior seems to
have changed, which means this assertion is no longer necessary.

[C] Remove assertion in response to loofah update

---

client/src/theme/Components/reader/_appearance-menu.scss

Very minor.
Noticed that there was a transition applied to only the margin buttons.  Added it to the other reader appearance buttons.

[C] Add transitions to reader buttons

---

client/src/api/client.js
client/src/components/global/HigherOrder/fetchData.js
client/src/store/reducers/notifications.js

Fixes #639.
If an API request returns a 404, in almost every case we want the
client to also return a 404 to the user. This was the case
previously, only they were being cleared to agressively, sometimes
before the client-side app could respond with the correct header.

[B] Allow 404 API requests to bubble up

---

client/src/theme/Components/browse/resource/_slide.scss

Closes #933 
This swaps the transition CSS from a position transition to a translate3d one, which is generally more compatible when used. The `translate3d` (instead of translateX) parameter ensures the GPU will be used to perform the transition if there is one on the machine. In my testing on Chrome, Firefox, and Safari, this mitigated the bug with video flickering, and didn't cause any variation on photo slideshow pages.

[B] Fix video slider overlay artifacts

---

client/src/components/backend/List/Searchable.js
client/src/config.js
client/src/containers/backend/People/Users/List.js
client/src/containers/backend/People/Users/__tests__/__snapshots__/List-test.js.snap

This should address @mkgold's request to group the user list by role.
I'm leaving #941 open because I think it makes sense to include sortable headers/buttons.  On the frontend ordering is currently only in one place and we use a dropdown as there is only one attribute to sort by, but we may have situations like Users where there are multiple sort attributes.  In those cases, it seems like we should use buttons that change sort direction rather than a single dropdown with up/down directions for multiple attributes.
I have the sorting functionality in place in another branch. It is just waiting on some design to differentiate the sorting buttons from the filter dropdowns.

 [C] Filter User list by role

---

client/src/components/backend/Layout/Header.js
client/src/components/backend/List/Searchable.js
client/src/containers/backend/Backend.js
client/src/containers/backend/Dashboard.js
client/src/containers/backend/Dashboards/Admin.js
client/src/containers/backend/Dashboards/__tests__/Admin-test.js
client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap

Let me know how you feel about the `isProjects()` move.  I moved it into the `Backend` container so we know when to reset the snapshot.  It felt weird that the project list state persisted even after going to other pages outside of projects.

 [F] Remember page and filter in backend project list

---

api/app/models/resource_import.rb
api/app/models/resource_import_row.rb
api/app/services/resource_import_rows/import.rb
api/app/services/resource_import_rows/state_machine.rb
api/app/services/resource_imports/parse_csv.rb
api/app/services/resource_imports/parse_google_sheet.rb
api/app/services/resource_imports/state_machine.rb
api/spec/models/resource_import_row_spec.rb
client/src/containers/backend/ResourceImport/Results.js
client/src/theme/Components/backend/forms/_results-list.scss

Per @tsmyre's comments about how the "Special instructions" column is being used, individual statements in the column should be delimited with a semi-colon.  The import will then skip any row that is indicated as such in this column.
```
Special Instructions
Author wants this image to be set inline and not at the top or bottom of the page.; skip;
```
Closes #944

[F] Improvements to bulk resource import

---

client/src/theme/Components/reader/notation/_preview.scss
client/src/theme/_z-stack.scss

Fixes #1025
Also adjusts the mobile resource viewer footer so it matches the height of the section label.

[B] Adjust reader TOC/footer z-indices

---

api/app/controllers/concerns/validation.rb
client/src/components/frontend/Project/Events.js
client/src/components/global/HeadContent.js
client/src/containers/Manifold.js
client/src/containers/backend/Settings/General.js
client/src/containers/backend/Settings/__tests__/__snapshots__/General-test.js.snap
client/src/containers/frontend/Featured.js
client/src/containers/frontend/Following.js

The fix here has a few parts:
- Expose a `headTitle` attribute on settings.
- Pick that title up at the top level (`ManifoldContainer`) or use the default as specified in the config file.
- Set a `titleTemplate` prop for helmet by default.  The `titleTemplate` potentially also uses the title from settings, so it must be defined when helmet is first used (again in `ManifoldContainer`).  
- Expose a prop `nested` on the `HeadContent` component.  When included, the page will use the `titleTemplate`, which is defined at the higher scope.  When `nested` is not included as a prop, we pass `titleTemplate: false` to helmet to override the setting.
Please also review the language in the backend form.  I feel like it's a little unclear, but was struggling with naming/describing it.
Fixes #1024

[B] Allow HEAD <title> to be set by installation

---

api/app/jobs/text_section_jobs/reindex_searchable_nodes.rb
api/app/models/text_section.rb
api/spec/models/text_section_spec.rb

Fixes #1033
This also moves the contents of `text_section#update_text_index` to
a background job.

[B] Fix text section not reindexing searchable nodes on create

---

api/app/controllers/concerns/validation.rb
api/app/jobs/annotation_jobs/adopt_or_orphan_job.rb
api/app/jobs/text_section_jobs/enqueue_adopt_annotations_job.rb
api/app/models/annotation.rb
api/app/models/text_section.rb
api/app/serializers/annotation_serializer.rb
api/app/services/annotations/adopt_or_orphan.rb
api/db/migrate/20180511173451_add_orphaned_to_annotations.rb
api/db/schema.rb
api/spec/models/annotation_spec.rb
api/spec/services/annotations/adopt_or_orphan_spec.rb
client/src/api/resources/annotations.js
client/src/containers/reader/ReaderNotes.js

The behavior of this change ends up being relatively small.  Effectively, the only addition coming from this PR is that annotations will detect their new start and end nodes when the UUIDs change.  The cases/outcomes of annotation reassignment is below.  Both of these cases has the same application when the section nodes are reordered.
- **Node content unchanged**: If the annotation subject remains stable, we use the existing start/end nodes.  If there are additional, new nodes between the start and end nodes, we orphan the annotation.
- **Node content changed**: We find the start and end nodes (new uuids because content has changed) and then see if the content spanning from start to end contains the annotation subject _exactly_.  We reassign to those nodes if it does or orphan if it does …

 [F] Attempt to reassign annotation start/end nodes when section changes

---

client/src/components/backend/Form/CodeArea.js

Fixes #1043 
There were a couple problems here:
- `...props` included an `onChange` function (the default setter version), which was overwriting the `onChange` function we were trying to pass in from the component.  This was causing the bug illustrated in the issue.
- In the render function, I was returning another function.  This was causing the editor to remount and lose the focus on every character input.

[B] Fix CodeArea component onChange

---

client/src/components/backend/Form/setter.js
client/src/containers/backend/Form/Form.js

Fixes #1068
FormContainer change: `props.model` was `null` and being passed to the `open` entityEditor function.  That function uses the model argument to instantiate the model, so it need to be an empty hash by default.
setter change: This is because `ColumnMap` implements the new lifecycle function `getDerivedStateFromProps`, which is a static function.  When wrapped with the `setter` component, `getDerivedStateFromProps` is hoisted and requires state to be initialized.  The fix here is ignoring `getDerivedStateFromProps` when static functions are hoisted in the `setter` component.

[B] Fix FormContainer session initializing with null model

---

api/app/services/resource_import_rows/import.rb

Fixes #1071 
I chose to leave the arguments being passed to the blocker methods just in case we block by value in the future.

[B] Fix attachments being skipped on bulk resource import

---

client/src/containers/backend/Content/Features/List.js
client/src/theme/STACSS/_appearance.scss

Other similar button arrangements don't have any text for the delete button (see screenshot) so I made that screen reader text instead.  I also cleaned up the ternary for toggling the move up and move down buttons' visibility.
Resolves #1091

[B] Fix "delete feature" button states

---

client/src/theme/Components/backend/_vertical-list.scss
client/src/theme/Components/backend/collection/_resources-list.scss

Resolves #1086 
Adds styles to change the color of the icon and name of the resource in the list on hover (and retains the existing hoverstate of the subtitle)

[B] Fix reader side drawer resource list hoverstates

---

api/app/services/ingestor/preprocessor/html/header_ids.rb
api/app/services/ingestor/preprocessor/html/processor.rb
api/app/services/ingestor/strategy/google_doc/builder.rb
api/app/services/ingestor/strategy/google_doc/inspector/google_doc.rb
api/app/services/ingestor/strategy/google_doc/inspector/structure.rb
api/spec/services/ingestor/preprocessor/html_spec.rb
api/spec/services/ingestor/strategy/google_doc/strategy_spec.rb

Closes #1077
This commit adds TOC generation for single-page google docs. For TOCs
to generate reliably, it's important that documents are semantically correct.
A TOC node entry can only have children that have headers _one_ level below
itself. For instance, an `<h1>` will only receive `<h2>` children.  Those `<h2>`
children will then only receive `<h3>` children, and so on.

[F] Generate TOC for single-page Google Doc

---

client/src/components/global/Search/Query/Form.js
client/src/components/reader/Annotation/Editor.js
client/src/components/reader/Annotation/Selection/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/components/reader/Annotation/__tests__/__snapshots__/Editor-test.js.snap
client/src/components/reader/ControlMenu/VisibilityMenuBody.js
client/src/components/reader/ControlMenu/__tests__/__snapshots__/VisibilityMenuBody-test.js.snap
client/src/components/reader/Notes/Partial/Filters.js
client/src/components/reader/Notes/Partial/__tests__/__snapshots__/Filters-test.js.snap
client/src/components/reader/Notes/__tests__/__snapshots__/FilteredList-test.js.snap

Resolves #1103 
Includes updated tests.
Wherever possible I associated the label with the input using the `for` and `id` attributes (even if the label wrapped the input).  This ensures the greatest support across screen readers.

All checkbox and radio inputs have labels or other descriptive text

---

client/src/components/backend/Form/__tests__/__snapshots__/HasMany-test.js.snap
client/src/components/backend/Project/Form/__tests__/__snapshots__/Subjects-test.js.snap
client/src/containers/backend/Form/PredictiveInput.js
client/src/containers/backend/Form/__tests__/__snapshots__/Collaborators-test.js.snap
client/src/containers/backend/Permission/__tests__/__snapshots__/Form-test.js.snap
client/src/containers/backend/Permission/__tests__/__snapshots__/New-test.js.snap
client/src/containers/backend/Project/__tests__/__snapshots__/Collaborators-test.js.snap
client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
client/src/containers/backend/Text/__tests__/__snapshots__/Collaborators-test.js.snap
client/src/theme/Components/backend/forms/_input-predictive.scss

Resolves #1048
Plus sign next to the placeholder text in the Predictive Text Input was a button with no purpose so now it is an icon instead (visually identical).

Turns a functionless button in the predictive text input component into an icon

---

api/config/manifold.yml
client/src/components/backend/Form/Upload.js
client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Audio-test.js.snap

Currently .ogg files are being rejected because their mimetype is being reported as `video/ogg`.  I was unable to find any .ogg files that came back as `audio/ogg`.  Since we don't accept .ogg as video files, I think it makes sense to allow `video/ogg` for audio files.
Additionally, I added acceptance of .oga audio extensions.  Incidentally, these were also reporting `video/ogg` despite explicitly being an audio format.
Fixes #1131

[B] Improve ogg file acceptance

---

api/app/serializers/project_serializer.rb
client/src/theme/Components/browse/project/_resource-thumbnail-list.scss

The issue here is that we only fetch 12 resources.  This is fine in all cases except for full-width (> 960px), when the row items are 1/5 width.  
The fix I went with fetches 15 resources and hides the last 3 on screen sizes below 960px.  
The other approach would be to keep it at 12 resources and never have resource cards go smaller than 1/4 wide.
Fixes #1132

[B] Fix resource cards not using full space on project detail

---

client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
client/src/components/frontend/ResourceList/Slide/Caption.js
client/src/components/frontend/ResourceList/Slide/__tests__/__snapshots__/Caption-test.js.snap
client/src/components/frontend/ResourceList/Slideshow.js
client/src/components/frontend/ResourceList/__tests__/__snapshots__/Slideshow-test.js.snap
client/src/components/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap

Resolves #1072
Updates slide advance button language and alerts AT of slide type and title when it changes
The slider now meets the basic WAI guidelines for carousels: https://www.w3.org/WAI/tutorials/carousels/
1) User's control the rate of slides' advancing
2) All slider functionality is operable by keyboard
3) when the slide changes a summary of that resource is immediately read by AT
4) Focus is maintained on the slider controls when moving between slides

[F] Update slideshow accessibility

---

client/src/components/frontend/Project/Follow.js
client/src/components/frontend/Project/__tests__/__snapshots__/Following-test.js.snap
client/src/components/frontend/Project/__tests__/__snapshots__/Thumbnail-test.js.snap
client/src/components/frontend/ProjectList/__tests__/__snapshots__/CoversGrid-test.js.snap
client/src/components/frontend/ProjectList/__tests__/__snapshots__/Grid-test.js.snap
client/src/components/frontend/ProjectList/__tests__/__snapshots__/SummaryGrid-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/Featured-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/Following-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/Home-test.js.snap

Resolves #1042 
The follow/unfollow "button" both utilized mouse events to control its state and required a two-phase process for unfollowing which made navigation by only keyboard confusing.  This PR adds a screen reader only button that allows the user to immediately follow/unfollow using only the keyboard (i.e. giving the button focus and then simulating a click using the enter key).

Update follow/unfollow project interaction accessibility

---

client/src/components/global/Overlay.js
client/src/components/global/__tests__/__snapshots__/Overlay-test.js.snap
client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
client/src/containers/reader/Notation/Resource/__tests__/__snapshots__/Detail-test.js.snap

We recently wrapped our overlays in the FocusTrap component as part of
our accessibility efforts. As part of that implementation, we adjusted
the overlay so that it automatically triggers its close handler when
it loses focus. This is a problem because the close handler generally
will trigger a "back" action in history, or will redirect the user to
the URL from which the overlay was opened. The unintended side effect of
this is that if there is a link in the overlay (as in the case of the
resource notation overlay in the reader), clicking that link will
trigger the close behavior rather than going to the intended link
target.
Fixes #1183

[B] Overlay de-focus should not trigger close

---

client/src/components/reader/Annotation/Popup/Wrapper.js
client/src/components/reader/Notation/Viewer/Fader.js
client/src/components/reader/Notation/Viewer/List.js

Resolves #1194
These were not positioned or styled correctly due to the use of an unsupported property: scrollY. Since the only uses of this property were on the window (i.e. window.scrollY) I replaced it with window.pageYOffset which has total support across browsers (and in  most cases is just an alias for scrollY).

[B] Fix the positioning and styles for the left side notation thumbnails in the reader

---

client/src/components/global/Utility/SkipLink.js
client/src/components/global/Utility/index.js
client/src/containers/backend/Backend.js
client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
client/src/containers/frontend/Frontend.js
client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
client/src/containers/reader/Reader.js
client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap

Resolves #1146 
These skip links are only visible to screen readers and provide the user with the means to skip over the main navigation on page load (as the screen reader always starts reading from the top).

[F] Adds "skip to main content" links for Reader, Admin Backend, and Frontend page templates

---

client/src/theme/Components/reader/_header-reader.scss

Resolves #1202
This menu slides out of sight by its width.  This menu must have changed size (is now wider) since this css transition was introduced and so was not sliding off all of the way.  This updates that amount by which it slides (the menu's new width).

[B] Fix search menu slide off transition

---

client/package.json
client/src/components/frontend/ResourceCollection/__tests__/Detail-test.js
client/src/components/frontend/ResourceList/Slide/Caption.js
client/src/components/frontend/ResourceList/Slide/__tests__/Caption-test.js
client/src/components/frontend/ResourceList/__tests__/Slideshow-test.js
client/src/components/reader/Notation/Collection/__tests__/Detail-test.js
client/src/components/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
client/src/components/reader/Notes/Partial/Group.js
client/src/components/reader/Notes/Partial/__tests__/__snapshots__/Group-test.js.snap
client/src/components/reader/Notes/__tests__/__snapshots__/FilteredList-test.js.snap
client/src/containers/frontend/__tests__/CollectionDetail-test.js
client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
client/src/containers/reader/Notation/Collection/__tests__/Detail-test.js
client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
client/src/theme/Components/browse/collection/_resource-slideshow.scss
client/src/theme/Components/reader/notation/_detail.scss
client/yarn.lock

We're only using `velocity-react` in two places and the same effect can be easily achieved with `react-collapse`.  This PR came as a result of trying to solve #972.  
We rely on the height of the children of `<VelocityComponent>` to determine when a description can be expanded.  Since we accomplish this by using refs on the children, the are undefined until the async component is loaded.  When component loads asynchronously, there is no re-render triggered, so we never get those child refs.
Using `react-collapse` we achieve the same behavior, but with a much smaller package, allowing us to remove the `velocity-react` dependency entirely.  This allow allows us to not have to use code-splitting.
In it's current release, `react-collapse` uses `react-motion` for animation, but this dependency …

 [C] Replace velocity-react with react-collapse

---

client/src/theme/Components/browse/layout/_footer-browse.scss

Resolves #1218
Adds padding to the bottom of the browse layout's footer so that the following and projects buttons don't overlap with any footer content.

[B] Fix footer padding on mobile

---

client/src/containers/backend/Collection/Wrapper.js
client/src/containers/backend/Collection/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/Content/Pages/Detail.js
client/src/containers/backend/Content/Wrapper.js
client/src/containers/backend/People/Wrapper.js
client/src/containers/backend/People/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/Project/Wrapper.js
client/src/containers/backend/Project/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/Resource/Wrapper.js
client/src/containers/backend/Resource/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/Settings/Wrapper.js
client/src/containers/backend/Settings/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/Text/Wrapper.js
client/src/containers/backend/Text/__tests__/__snapshots__/Wrapper-test.js.snap

Resolves #1201
Adds anchor links, that are only visible to screen readers, above the sidebar nav of each admin backend page that link to the main panel content.

[F] Add skip links to admin pages with sidebar nav

---

api/app/services/validator/html.rb
api/app/services/validator/tag.rb
api/config/manifold.yml
api/spec/services/validator/html_spec.rb

The primary issue here was that the source html had unlcosed `<source>` tags.  While this is valid HTML 5, Nokogiri adds closing `</source>` tags, which is invalid.  Additionally, Nokogiri adds these closing tags in inconsistent places, resulting in some invalid nesting.
This fix adds a step in the HTML validator that will take void elements and ensure they're closed while maintaining their properties.  It will also remove any closing void tags.  It runs as the last step in the validator because we're manipulating the resulting HTML string, not the parsed nodes, and sending the string back through Nokogiri will add back the removed closing tags.

[B] Self-close void element tags in html validator

---

client/src/components/global/Drawer/Wrapper.js
client/src/components/global/Drawer/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/components/reader/Header.js
client/src/components/reader/Toc.js
client/src/components/reader/__tests__/__snapshots__/Header-test.js.snap
client/src/components/reader/__tests__/__snapshots__/Toc-test.js.snap
client/src/containers/backend/Project/Social/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/reader/Reader.js
client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
client/src/theme/Components/reader/_header-reader.scss

Resolves #1271
Resolves #1275
Updates the focus trap behavior to allow the contents button to toggle the ToC when clicked (even if the ToC is open).
Clears focus when user selects a different section.
Updates the focus state styles to be more subtle (ToC button and Menu button in the reader).
Updates the focus trap to allow interactive items outside of it to be clicked.

[B] Fix ToC drawer and trigger behavior

---

client/src/components/global/Drawer/Wrapper.js
client/src/components/global/Drawer/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/components/reader/Notes/ReaderDrawer.js
client/src/components/reader/__tests__/__snapshots__/Toc-test.js.snap
client/src/containers/backend/Project/Social/__tests__/__snapshots__/Wrapper-test.js.snap

Adds a screen reader only close button to the drawer even if there is no visible drawer header or close button.
Includes update to the Drawer component to optionally not initialize focus trap.  This is used on the "notes" ReaderDrawer as that drawer already lives in another focus trap supplied by its parent UIPanel.

[F] Updates drawers to always include some kind of screen reader accessible close button

---

client/src/theme/Components/global/_header-app.scss

Resolves #1272 
Updates the focus state styles for the user menu button to be less obtrusive and to not engage if the button is also selected (i.e. the menu is open).

[F] Update user nav trigger focus state styles

---

api/app/services/ingestions/strategies/manifest.rb
api/app/services/ingestions/strategy/manifest/inspector.rb
api/spec/services/ingestions/compiler_spec.rb

The solution we use in the Document strategy won't actually work here.
If the manifest is a single file and collection of google docs, the sources count is 1 at the start, but > 1 after docs are downloaded.  This presents the same issue we have now because we would try to determine the manifest by name, which is still changed through paperclip.
example: 
- At ingestion start, `sources = ["paperclip-random-name.yml"]`
- After downloading docs, `sources = ["paperclip-random-name.yml", "doc-1.html", "doc-2.html"]`
This essentially leaves us having to make the determination by file extension for now.  I _do_ think this is acceptable right now, as the use-cases for including additional `yml` files are extremely narrow, if existent at all.
Again, this may be worth revisiting when #1264 is …

[B] Fix single file manifest ingestions failing to detect source

---

api/app/uploaders/ingestion_uploader.rb
api/config/manifold.yml

This is a regression introduced with the change to Shrine.  
Also includes a change to the manifold config file.  Passing regex matchers are deprecated and will be removed in Shrine 3.

[B] Ingestion uploader should validate file ext instead of mime type

---

client/src/containers/reader/Reader.js

The Section container will fetch the TextSection model for the Reader.
Fixes #1283.

[B] Remove extraneous API call from Reader Container

---

api/app/services/ingestions/strategy/epub/toc/v2.rb
api/lib/tasks/project.rake
api/spec/services/ingestions/strategy/epub/toc_spec.rb

The EPUB v2 node structure was selecting _all_ matching child nodes.  This meant that for every item with children, the entire branch was run through the structure generator.
The fix is to only select the direct descendants of each branch.

[B] Fix EPUB v2 TOC tree generation

---

client/src/theme/Components/backend/text/_list.scss

Inconsistent line-height of children was causing category headers to be too tall.
Resolves #1321

[B] Fix layout of backend text category headers

---

client/src/containers/backend/Ingestion/Ingest.js
client/src/containers/backend/Ingestion/__tests__/__snapshots__/Ingest-test.js.snap

Flips order of icon and text in "Restart ingestion" button for
consistency with v2.0 backend UI updates.
Resolves #1329

[B] Fix position of icon in text reingest button

---

client/src/components/backend/Form/Header.js
client/src/components/backend/Form/index.js
client/src/components/backend/Ingestion/Form/Upload.js
client/src/components/backend/Ingestion/Form/Wrapper.js
client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Upload-test.js.snap
client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/containers/backend/Project/ProjectPage.js
client/src/containers/backend/Project/Text/Ingestion/New.js
client/src/containers/backend/Project/Text/Ingestion/__tests__/__snapshots__/New-test.js.snap
client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
client/src/containers/backend/Text/General.js
client/src/containers/backend/Text/Ingestion/New.js
client/src/containers/backend/Text/Ingestion/__tests__/__snapshots__/New-test.js.snap
client/src/containers/backend/Text/__tests__/__snapshots__/General-test.js.snap
client/src/theme/Components/global/forms/_form-inputs-secondary.scss
client/src/theme/Components/global/forms/_section.scss
client/src/theme/STACSS/_appearance.scss

This commit adds a new header component for backend forms that currently
lack a clear heading. This better orients the user to the form they are
viewing and improves design coherence across the backend.
Resolves #1331

[F] Implement Form.Header component

---

client/src/theme/Components/global/forms/_form-inputs-secondary.scss

Setting the `color` property explicitly for `:focus` state solves this
issue.
Resolves #1346

[B] Fix form select visibility bug in Firefox

---

client/src/theme/Components/backend/project/_color-picker.scss

The color picker was displaying a green background, which
was coming from the default form-toggle styles.
Fixes #1374

[B] Fix project avatar color picker styles

---

api/config/initializers/20_configuration.rb

There’s a little ENV cleanup that needs to happen at some point. Our
Omnibus packages don't ask the user to set the domain, instead asking
for the URL of the site in /etc/manifold/manifold.rb. That setting
flows into the API environment as CLIENT_URL. In our local dev
environments and installations installed by puppet, we're setting the
DOMAIN environment variable, and building the client URL in an
initializer based on that domain and whether or not Manifodl is
configured to use SSL. This change allows the interal client URL in the
API to be set from either CLIENT_URL or DOMAIN, in the interest of
backwards compatibility. This needs to be set correctly for the
email notifications to have correct image pages.
Fixes #1381

[B] API sets client URL from CLIENT_URL or DOMAIN

---

api/app/models/project.rb
api/config/manifold.yml

Also uses the resource attachment kind to validate project published
text uploads.
Fixes #1373

[B] Broaden acceptable extensions for resource attachments

---

client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
client/src/helpers/router/childRoutes.js

This revision add the concept of "slots" to child routes, which is
useful in cases where a component wants to render some child routes
in one spot, and others in another spot. By default, a childRoutes()
call will render all child routes, as in the past. If a route has a
"slot" property, that route will only render if the childRoute options
hash has a "slot" property with a matching value. For example
```
<div>
{childRoutes(this.props.route, { slot: "drawer", drawer: true })}
{childRoutes(this.props.route)}
</div>
```
The first childRoutes call will render any child routes with a slot
property of "drawer". The second call will render any child routes
with a null or undefined slot property.

[F] Expose concept of “slots” in child routes

---

api/app/lib/updaters/project.rb
api/spec/requests/projects_spec.rb

If `attributes[:purchase_price_money]` is `nil`, it wasn't included in params and we don't want to touch the field.  If it's `""` or true for any other `blank?` check, we should reset it.
Fixes #1424

[B] Fix purchase price being reset on project update

---

client/src/components/backend/Form/HasMany.js
client/src/components/backend/Project/Form/Subjects.js
client/src/containers/backend/Form/Collaborators.js
client/src/containers/backend/Form/Form.js

This commit adjusts Form.HasMany to be wrapped with setter.
Along with this, HasMany will now set records to the relationships
object on a model if `name` prop is passed and `changeHandler` is
not passed.  If `changeHandler` is passed, HasMany will run the
callback function on select.
This allows the HasMany component to be used on a new
record as well as existing ones.

[C] Refactor HasMany to set relationships on model

---

api/app/services/resource_imports/parse_csv.rb
api/spec/data/resource_import/utf-8.csv
api/spec/services/resource_imports/parse_csv_spec.rb

This issue is sort of a few levels deep.
The solution to the issue that Terence opened is to export the csv as a UTF-8 formatted csv, which preserves the curly quotes.  Whatever encoding Excel exports the regular csv type in (ISO-something) results in those curly characters being misinterpreted by ruby's `File.read`.  As far as I can tell, this is the only way to make sure the curly quotes stay as curly quotes as `File.read` does not intereprete them as something we could reliable catch and switch back.
I then found that the first row, the one with the instructions, in Terence's file was causing an error when exported as UTF-8 csv.  Despite its output looking correct, trying to parse it with `CSV.parse` would throw `CSV::MalformedCSVError: Illegal quoting in line 1.`.  His file parses …

[B] Improve CSV parsing during bulk resource import

---

client/src/components/backend/Form/HasMany.js

Since the entities for a HasMany list can now come from a
form model's attributes in addition to a model record, this
prop is empty when the value is set by setter.  As a result,
we should no longer require the entities prop to be present.

[B] HasMany should not require entities prop

---

client/src/components/reader/Section/BodyNodes/LinkNode.js

If a URL fails to parse (most common occurrence would be an
outdated DOI link format), we will now just render the url as
an absolute, external URL.
Fixes #1476

[B] Catch and ignore URI.parse errors in reader

---

api/app/services/ingestions/strategy/document/toc.rb
api/spec/services/ingestions/strategy/document/toc_spec.rb

Improves TOC structure to support cases where headers aren't
consecutive. This commit gets us a little closer to handling
improperly nested headers, although the best way to ensure
good TOC rendering is to keep all headers properly nested.
Fixes #1471

[B] Fix document ingestion TOC nesting

---

client/src/components/reader/Notation/Marker.js
client/src/components/reader/Notation/Viewer/Link.js
client/src/components/reader/Notation/Viewer/__tests__/__snapshots__/Group-test.js.snap
client/src/components/reader/Section/Text.js
client/src/containers/reader/Notation/Resource/Detail.js

This commit moves annotation filtering into getDerivedStateFromProps
while continuing to check if there's an invalid annotation in the URL
after the component has updated. Prior to this change, the check was
happening before the annotations for a new text section were filtered
and stored in state, which cause the annotation hash to be stripped
every time.
Fixes #823

[B] Address regression when navigating between notes

---

client/src/components/backend/ProjectCollection/__tests__/__snapshots__/AddButton-test.js.snap
client/src/components/backend/ProjectCollection/__tests__/__snapshots__/ProjectCover-test.js.snap
client/src/components/frontend/Project/__tests__/__snapshots__/Following-test.js.snap
client/src/components/frontend/Project/__tests__/__snapshots__/Thumbnail-test.js.snap
client/src/components/frontend/ProjectList/__tests__/__snapshots__/Grid-test.js.snap
client/src/components/global/Project/CoverButton.js
client/src/components/global/SVG/Icon/Check.js
client/src/components/global/SVG/Icon/Minus.js
client/src/components/global/SVG/Icon/Plus.js
client/src/components/global/SVG/Icon/index.js
client/src/containers/backend/ProjectCollection/__tests__/__snapshots__/ManageProjects-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/Featured-test.js.snap
client/src/containers/frontend/__tests__/__snapshots__/Following-test.js.snap
client/src/theme/Components/backend/_project-list.scss
client/src/theme/Components/browse/project-list/_project-grid.scss
client/src/theme/Components/global/_buttons.scss
client/src/theme/Components/global/_project-list.scss
client/src/theme/STACSS/_appearance.scss

Replaces font-based icons with SVGs to simplify positioning, shrinks button size and adds padding on mobile, and improves CSS transitions.
Resolves #1512

[B] Improve appearance of project cover button

---

client/src/theme/Components/global/forms/_shared.scss
client/src/theme/STACSS/_appearance.scss

Fixes an issue with some search inputs having default user agent appearance in iOS Safari.
Resolves #1505

[B] Normalize appearance of search inputs

---

client/src/theme/Components/backend/ingestion/_ingest.scss

Opinion PR:
Makes the ingestion log taller.  Breaks to current height when drawer width narrows.

[C] Increase height of ingestion log

---

api/db/schema.rb

The impending Paperclip to Shrine migrations seem to have
been included in the ProjectCollections branch.  This commit
removes the new columns coming in #1487.

[B] Fix schema file

---

client/src/components/reader/Section/BodyNodes/TextNode.js
client/src/utils/smoothScroll.js

Currently this looks for an exact `annotation-ids` match to
the id in the url hash.  This is an issue when a single TextNode
has multiple annotation ids on it.  Ultimately this results in a
null element being passed to `smoothScroll`, which has no protection
against a null element.
This commit adjusts the TextNode `doScroll` function to
query elements by `data-annotation-ids` substring presence and also
adds a guard to `smoothScroll` in any case where a null element is
passed to it
Fixes #1571

[B] TextNode annotation queries substring

---

api/app/services/ingestions.rb
api/app/services/ingestions/concerns/catches_exceptions.rb
api/app/services/ingestions/concerns/file_operations.rb
api/app/services/ingestions/context.rb
api/app/services/ingestions/fetchers.rb
api/app/services/ingestions/fetchers/google_doc.rb
api/app/services/ingestions/pickers/abstract_picker.rb
api/app/services/ingestions/post_processors/text_section_body.rb
api/app/services/ingestions/pre_processors/extract_stylesheets.rb
api/spec/services/ingestions/compiler_spec.rb

This commit adds a new IngestionError class and raises
it in places where ingestions tend to fail.  We now rescue
this error instead of StandardError in the CatchesException
concern.
Fixes #1355
Fixes #1430

[B] Don't rescue StandardError during ingestion

---

api/app/services/ingestions/compiler.rb

Addresses a case where a spine is generated in the post processor
and then lost when the text is reloaded as part of
`#remove_stale_sections`. This commit reloads the text when it is
stable and returned from the Compiler.

[B] Reload text before passing to PostProcessor

---

api/app/authorizers/annotation_authorizer.rb
api/app/authorizers/application_authorizer.rb
api/app/controllers/api/v1/me/relationships/annotations_controller.rb
api/app/controllers/api/v1/me/relationships/favorite_projects_controller.rb
api/app/controllers/api/v1/me/relationships/favorites_controller.rb
api/app/controllers/api/v1/me_controller.rb
api/app/controllers/api/v1/projects_controller.rb
api/app/controllers/api/v1/texts_controller.rb
api/app/controllers/application_controller.rb
api/app/services/ingestions/post_processors/text_section_body.rb
api/app/services/ingestions/strategy/epub/toc.rb
api/config/initializers/authority.rb
api/spec/authorizers/annotation_authorizer_spec.rb
api/spec/authorizers/project_authorizer_spec.rb
api/spec/authorizers/resource_authorizer_spec.rb
api/spec/authorizers/text_authorizer_spec.rb
api/spec/requests/text_sections/relationships/annotations_spec.rb
api/spec/support/helpers/authorization.rb
api/spec/support/shared_examples/authorization.rb
client/src/reader/containers/Reader/index.js
client/src/store/middleware/apiErrorMiddleware.js

This commit addresses a couple issues:
1. We weren't previously authorizing Project/Text#show, which meant
that direct navigation to draft projects and those projects' texts
always succeeded, even when unauthenticated.
2. We were rescuing Authority::MissingUser errors with a 401 error
requiring login.  This is incorrect when an unauthenticated user is
attempting to view a Project or Text and we authorize the action.
Instead, we now create an `anonymous_user` that has reader privileges
and defers its `can_read?` check to the resource we're verifying.
Fixes #1670

[B] Improve unauthenticated authorization

---

client/src/global/components/form/Errorable.js

The serializer returns all errors under an `attributes` pointer.  This
causes issues in the client with form components that are setting
relationships.  This commit changes the errorable component to always
look at the `attributes` pointer regardless of whether the wrapping component
is looking at a relationship or attribute.

[B] Errorable always looks at attributes

---

client/src/frontend/components/project-collection/Detail.js
client/src/frontend/components/project-collection/Filters.js
client/src/frontend/components/project-collection/Summary.js
client/src/frontend/components/project-collection/__tests__/__snapshots__/Detail-test.js.snap
client/src/frontend/components/project-collection/__tests__/__snapshots__/Summary-test.js.snap
client/src/frontend/components/project-list/Filters.js
client/src/frontend/components/project-list/Following.js
client/src/frontend/components/project-list/Grid.js
client/src/frontend/components/project-list/__tests__/__snapshots__/Following-test.js.snap
client/src/frontend/containers/Following/__tests__/__snapshots__/Following-test.js.snap
client/src/frontend/containers/Following/index.js
client/src/frontend/containers/ProjectCollectionDetail/__tests__/__snapshots__/ProjectCollectionDetail-test.js.snap
client/src/frontend/containers/ProjectCollections/__tests__/__snapshots__/ProjectCollections-test.js.snap
client/src/frontend/containers/Projects/index.js
client/src/theme/Components/browse/layout/_entity-section-wrapper.scss
client/src/theme/Components/browse/layout/_index.scss
client/src/theme/Components/browse/project-list/_index.scss

This commit creates .entity-section-wrapper and nested classes to manage a common layout across the frontend of a section title, description, body, pagination, and filters. This change abstracts the existing styles of project list and project collection containers so that these styles may be used generally for any similar high-level layout of page elements.
Components and containers are updated to reflect this change in classNames and also to apply BEM naming conventions (e.g. .entity-section-wrapper__heading), which helps avoid excessive scoping of selectors and leave elements within things like the heading unaffected.

[C] Abstract .project-list-container into general section wrapper

---

client/src/backend/components/form/HasMany/index.js
client/src/backend/components/form/OptionsList.js
client/src/backend/containers/form-inputs/connected-inputs/FetchSelect.js

The HasMany/OptionsList/ConnectedSelect components can likely be
further refactored, but this simply allows HasMany to take an array
of options and avoid fetching when data is already available.

[C] Allow HasMany to accept options array

---

client/src/frontend/components/project/Content/Block/types/Hero.js
client/src/frontend/components/project/Content/Block/types/index.js

This prevents the frontend from breaking due to lacking the required type component.

Add placeholder Hero block

---

client/src/global/components/drawer/Wrapper.js
client/src/helpers/router/childRoutes.js

This commit changes drawer route behavior to never trigger parent
route scrolling. Since the drawer routes should be considered as an
interaction similar to an overlay, they should not change anything
about the page that opens them.

[C] Drawers do not trigger page scrolling

---

api/app/models/text.rb
api/app/services/system_upgrades/upgrades/manifold030000.rb
client/src/frontend/components/TextList/ListItem/Content.js
client/src/frontend/components/TextList/ListItem/__tests__/__snapshots__/Content-test.js.snap
client/src/frontend/components/TextList/ListItem/index.js
client/src/frontend/components/TextList/__tests__/__snapshots__/TextList-test.js.snap
client/src/frontend/components/text/Cover.js

Removes the `no_styles` option from Text cover attachments.  This commit
includes a SystemUpgrade file for V3.0.0 to generate styles for all
existing Text cover attachments.
Closes #1848

[B] Add styles to text cover attachments

---

client/src/backend/components/dashboard/Activity.js
client/src/backend/components/dashboard/__tests__/__snapshots__/Activity-test.js.snap

* Removes space between +/- and number to prevent stat from breaking between lines.
Resolves #1770

[B] Prevent wrapping in activity statistics

---

client/src/theme/Components/backend/_drawer.scss
client/src/theme/Components/backend/project/_action_callout_slot.scss
client/src/theme/Components/backend/project/_content-block.scss
client/src/theme/Components/backend/project/_hero-builder-block.scss
client/src/theme/Components/browse/collection/_list.scss
client/src/theme/Components/browse/project/_hero.scss
client/src/theme/Components/browse/text/_text-block.scss

Fixes various issues detected during device & browser testing:
* Adjusts breakpoint for text block layout change to show cover and
two-column layout until narrower viewport width
* Improves responsive sizing of elements in resource collection thumbs
* Increases min-width of hero right-hand block
* Fixes iOS text selection blocking use of drag handles on backend
* Fixes collapse of callout chip buttons when long title present
* Prevents hero block "Edit" label from showing on very narrow viewports
* Reduces spacing between content block buttons on narrow viewports
* Sets `overflow` to `auto` on drawers to prevent empty scrollbars

[B] Misc style fixes to project hero/content blocks

---

client/src/theme/Components/browse/event/_tile.scss

This is a temporary fix.  This bug is caused by the .vertical-list-primary
styles, which should be refactored to reflect our new styling conventions.
Completing that refactor should resolve the styling issues on the
event tiles.

[B] Fix backend event tile styles

---

client/src/store/middleware/currentUserMiddleware.js

This reverts commit dd2d01bf2eabaa1e42872373a76f13f2b6309de8.
This causing an issue authenticating on refresh.  SSR fails when referencing `document`, which prevents the authentication from continuing.

Revert "[B] Fix OAuth sessions not setting cookie"

---

api/app/controllers/api/v1/projects_controller.rb

This was causing an issue with deleting projects were resource tags
were destroyed early.  Then when ActsAsTaggableOn went to clean up
the unused tags, it would throw an error trying to find the destroyed
tags.
Removing this eager loading does not seem to have any negative impact
on the AR time of projects controller requests. If anything, they seem
to be a hair quicker.
Fixes #1803

[B] Remove tag eager loading from projects

---

client/src/global/components/UserMenuBody/__tests__/__snapshots__/UserMenuBody-test.js.snap
client/src/global/components/UserMenuBody/index.js
client/src/global/components/navigation/mobile-components/UserLinks.js
client/src/theme/Components/global/_header-app.scss
client/src/theme/Components/global/_nested-nav.scss

This also removes the click action from the user's name and adds a
notifications button to the mobile menu.
Fixes #2024
Fixes #2026

[B] Add describedby text to user menu buttons

---

api/app/services/seed.rb

We agreed that regardless of whether Manifold is actually upgrading or a fresh install, these should be run for real.  This prevents us from artificially creating `UpgradeResult` records for fresh installations and actually runs the contents of them.
As an example, going from 2.1 to 3.0 involves creating content blocks for all existing projects.  Currently, when reconfiguring manifold after installation, the 3.0 UpgradeRecord will be created, but content blocks will not.

[B] Remove noop from seed upgrade call

---

client/src/frontend/components/event/List.js
client/src/frontend/components/event/__tests__/List-test.js
client/src/frontend/components/event/__tests__/__snapshots__/List-test.js.snap
client/src/frontend/components/project/Events.js
client/src/frontend/components/project/__tests__/__snapshots__/Events-test.js.snap
client/src/frontend/containers/EventList/__tests__/__snapshots__/EventList-test.js.snap
client/src/theme/styles/components/frontend/event/_events.scss

This PR simplifies frontend event tile lists with a single "event-list" class. This also fixes a bug where the layout for "event-list-primary" was broken.

[R] Standardize frontend event lists with single class "event-list"

---

api/config/initializers/55_shrine.rb
api/db/migrate/20181025181234_migrate_existing_attachments_to_shrine.rb
api/lib/paperclip_migrator.rb

Upgrading from v2.0.x to v3.0.x was failing because the refinment to
ResourceCollections that we wrote wasn't being properly applied to
the PaperclipMigrator class. This all stemmed from an effort to make
our migrations backwards compatible after renaming the Collection model
to ResourceCollection.
Resolves #2148

[C] Address resource collection rename in migrations

---

api/app/models/concerns/citable.rb
api/spec/models/concerns/citable_spec.rb

This was a regression introduced in 96c9e76.  Since the callback for
`update_citable_children` was moved into `after_commit` the comparison
of `citations` to `citations_was` always returned true.  This commit adjusts
that check to see if the previous changes to a record include `:citations`.  If so,
we know that the parent citations changed and can run the children update.
Fixes #2057

[B] Fix citations not being generated on children

---

client/src/backend/components/content-block/TypeForm/types/__tests__/__snapshots__/Markdown-test.js.snap
client/src/backend/components/form/Radio/Label.js
client/src/backend/components/form/Radios.js
client/src/backend/components/form/__tests__/__snapshots__/Radios-test.js.snap
client/src/backend/containers/project/__tests__/__snapshots__/New-test.js.snap
client/src/frontend/containers/Subscriptions/__tests__/__snapshots__/Subscriptions-test.js.snap
client/src/global/components/preferences/NotificationsForm.js
client/src/global/components/preferences/__tests__/__snapshots__/NotificationsForm-test.js.snap
client/src/theme/styles/components/frontend/subscriptions/_subscriptions.scss
client/src/theme/styles/components/global/forms/_form-inputs-primary.scss

* Refactors markup to use `fieldset` and `legend` elements. This establishes connected inputs as radio groups and creates an association between groups and their caption/question.
* Sets `disabled` attribute on collapsed input groups.
Resolves #2195

[R] Improve a11y of radio groups

---

client/src/backend/components/project-collection/__tests__/__snapshots__/AddButton-test.js.snap
client/src/backend/components/project-collection/__tests__/__snapshots__/ProjectCover-test.js.snap
client/src/backend/containers/project-collection/ManageProjects.js
client/src/backend/containers/project-collection/__tests__/__snapshots__/ManageProjects-test.js.snap
client/src/frontend/components/project-collection/__tests__/__snapshots__/Detail-test.js.snap
client/src/frontend/components/project-collection/__tests__/__snapshots__/Summary-test.js.snap
client/src/frontend/components/project-list/Grid.js
client/src/frontend/components/project-list/GridItem.js
client/src/frontend/components/project-list/__tests__/__snapshots__/Following-test.js.snap
client/src/frontend/components/project-list/__tests__/__snapshots__/Grid-test.js.snap
client/src/frontend/components/project-list/__tests__/__snapshots__/GridItem-test.js.snap
client/src/frontend/components/project/Follow.js
client/src/frontend/components/project/__tests__/__snapshots__/Detail-test.js.snap
client/src/frontend/components/project/__tests__/__snapshots__/Following-test.js.snap
client/src/frontend/components/project/__tests__/__snapshots__/Hero-test.js.snap
client/src/frontend/containers/Featured/__tests__/__snapshots__/Featured-test.js.snap
client/src/frontend/containers/Following/__tests__/__snapshots__/Following-test.js.snap
client/src/frontend/containers/ProjectCollectionDetail/__tests__/__snapshots__/ProjectCollectionDetail-test.js.snap
client/src/frontend/containers/ProjectDetail/__tests__/__snapshots__/ProjectDetail-test.js.snap
client/src/global/components/project/Avatar.js
client/src/global/components/project/CoverButton.js
client/src/hoc/with-screen-reader-status/index.js
client/src/theme/styles/components/global/_buttons.scss
client/src/theme/styles/components/global/_project-list.scss

This PR makes a handful of changes to improve the accessibility of project lists on the FE and BE, with a particular emphasis on improving the experience for users accessing Manifold with a screen reader:
* Hides most content within each project link (cover alt-text, metadata, publication status, etc) to make SR readout less verbose
* Un-nests "Follow" button from anchor that wraps each project
* Improves SR text for "Follow" button ("Include" in PC manual collections)
* Adds live region that provides a notification to screen readers when a project is followed/unfollowed (included/excluded in PC manual collections)
Resolves #2188

[B] Improve SR experience for project lists

---

client/src/theme/styles/components/backend/list/entity/_entity-list-search.scss
client/src/theme/styles/components/global/forms/_list-filter.scss

Resolves #2209
Applies `text-overflow: ellipsis` for supporting browsers (Safari, Firefox).

[B] Fix text-wrapping in search filters

---

client/src/frontend/components/content-block/Block/parts/Wrapper.js

This PR applies `<section>` as the outermost element of FE content blocks rather than `<div>`. This removes the implicit `banner` role for the `<header>` element in each content block and thus eliminates unwanted ARIA `banner` landmarks on the page.
Resolves #2262

[B] Use section element to wrap FE content blocks

---

client/src/backend/components/form/HasMany/List.js
client/src/backend/components/form/HasMany/ListItem.js
client/src/backend/components/form/HasMany/index.js
client/src/backend/components/form/TagList.js
client/src/backend/components/form/__tests__/__snapshots__/HasMany-test.js.snap
client/src/backend/components/form/__tests__/__snapshots__/TagList-test.js.snap
client/src/backend/components/project-collection/form/__tests__/__snapshots__/SmartAttributes-test.js.snap
client/src/backend/components/project/form/__tests__/__snapshots__/Subjects-test.js.snap
client/src/backend/containers/form-inputs/composite-inputs/__tests__/__snapshots__/Collaborators-test.js.snap
client/src/backend/containers/form-inputs/connected-inputs/PredictiveInput.js
client/src/backend/containers/project/__tests__/__snapshots__/Collaborators-test.js.snap
client/src/backend/containers/project/__tests__/__snapshots__/General-test.js.snap
client/src/backend/containers/resource/__tests__/__snapshots__/General-test.js.snap
client/src/backend/containers/text/__tests__/__snapshots__/Collaborators-test.js.snap
client/src/theme/styles/base/_z-stack.scss
client/src/theme/styles/components/backend/forms/_has-many-list.scss
client/src/theme/styles/components/backend/forms/_input-predictive.scss

This PR makes two improvements to components contained in Form.HasMany in order to make these components more intelligible to screen readers. First, it adds missing WAI-ARIA attributes to elements of the PredictiveInput component that allow screen readers to utilize the autocomplete functionality of the input. Second, it implements the withScreenReaderStatus HOC in various components to announce when items are added to, removed from, or reordered in the HasMany list.
Resolves #2293

[B] Improve a11y of HasMany lists

---

client/webpack/config/base.config.js

Browsers that don't support this pseudo-class (all at the moment) will ignore any block that uses it. This is especially problematic is production, where minification merges related chunks of CSS. Until wider browser support exists, we're disabling the `preserve` option on the postCSS plugin, so that `:focus-visible` is removed entirely and just `.focus-visible` is used.
See https://github.com/jonathantneal/postcss-focus-visible/issues/6

[B] Don't preserve :focus-visible class in polyfill

---

client/src/global/components/Annotation/Annotation/TextContent/index.js
client/src/global/components/Annotation/Annotation/index.js
client/src/global/components/Annotation/Highlight/index.js
client/src/global/components/Annotation/SourceSummary/index.js
client/src/reader/components/notes/__tests__/__snapshots__/DetailedList-test.js.snap
client/src/reader/containers/ReaderNotes/__tests__/__snapshots__/ReaderNotes-test.js.snap

Fixes a bug where annotations and highlights lacking a text section relationship were throwing an exception in the notes drawer. Also decouples rendering of SourceSummary content from whether the annotation is viewable in the text, and refines how SourceSummary content renders based on data available.

[B] Improve Annotation.SourceSummary rendering

---

client/src/theme/styles/base/_appearance.scss
client/src/theme/styles/base/_typography.scss
client/src/theme/styles/components/backend/_header.scss
client/src/theme/styles/components/backend/category/_text-category-list.scss
client/src/theme/styles/components/backend/category/_text-list.scss
client/src/theme/styles/components/backend/forms/_has-many-list.scss
client/src/theme/styles/components/backend/list/entity/_entity-row.scss
client/src/theme/styles/components/frontend/collection/_list.scss
client/src/theme/styles/components/frontend/collection/_resource-slideshow.scss
client/src/theme/styles/components/frontend/layout/header/standalone-header.scss
client/src/theme/styles/components/frontend/page/_content.scss
client/src/theme/styles/components/frontend/project/_hero.scss
client/src/theme/styles/components/frontend/resource/_card.scss
client/src/theme/styles/components/frontend/resource/_detail.scss
client/src/theme/styles/components/frontend/text/_text-block.scss
client/src/theme/styles/components/global/_asset-thumbnail.scss
client/src/theme/styles/components/global/annotation/_meta.scss
client/src/theme/styles/components/reader/_return-menu.scss
client/src/theme/styles/components/reader/_section-next-section.scss
client/src/theme/styles/components/reader/_toc-drawer.scss

Updates CSS to prevent hyphenation on names of texts, projects, makers, users, and other important pieces of content, such as major headings.
Resolves #1679

[B] Remove hyphenation from key text content

---

client/src/theme/styles/components/backend/list/entity/_entity-list.scss

This commit reverts fd5092cd and solves #2119 by using auto-fill rather than auto-fit grid tracks. This change allows grid items to flow contextually rather than on fixed tracks, while filling extra space with additional grid tracks rather than widening the grid items.
Resolves #2317

[B] Auto-fill columns for grid entity lists

---

client/src/frontend/containers/ProjectDetail/__tests__/__snapshots__/ProjectDetail-test.js.snap
client/src/frontend/containers/ProjectDetail/index.js
client/src/global/components/schema/Project.js
client/src/global/components/schema/index.js

Creates a component, `Schema.Project`, that renders metadata in JSON-LD format on the project homepage in order to improve the quality of information in search results.
We treat these pages as type `WebPage` that describe a `mainEntity` of type `Book`, following https://schema.org/ guidelines.
Resolves #1350

[F] Render structured data for projects

---

client/src/frontend/components/project/Detail.js
client/src/frontend/components/project/__tests__/__snapshots__/Detail-test.js.snap
client/src/frontend/containers/ProjectDetail/__tests__/__snapshots__/ProjectDetail-test.js.snap
client/src/theme/styles/components/frontend/project/_content-block.scss

Originally caught in #2329. Fix implemented in 0a87c2a did not adequately address all cases. This commit revises project detail page markup so that bottom project navigation (when present) is no longer a sibling of content blocks.

[B] Fix content block margins

---

api/spec/requests/resource_collections_spec.rb
api/spec/swagger_definitions/resource_collections.rb
api/spec/swagger_helper.rb

This is almost ready to go, but I'm hitting a failing test on a post.
The `post` test in `api/spec/requests/resource_collections_spec.rb` is throwing a 500 error when trying to create a ResourceCollection.
```
"status": 500,
"error": "Internal Server Error",
"exception": "#<NoMethodError: undefined method `updatable_by?' for nil:NilClass>",
"traces": {
"Application Trace": [
{
"id": 0,
"trace": "app/authorizers/project_child_authorizer.rb:10:in `default'"
},
```

[F] Add swagger documentation for ResourceCollection

---

client/src/backend/containers/project/__tests__/__snapshots__/Events-test.js.snap
client/src/frontend/components/event/Tile.js
client/src/frontend/components/event/__tests__/__snapshots__/List-test.js.snap
client/src/frontend/components/project/__tests__/__snapshots__/Events-test.js.snap
client/src/frontend/containers/EventList/__tests__/__snapshots__/EventList-test.js.snap

* Applies role `link` only when `hasLink` is `true` to prevent unlinked tiles from allowing focus
* Adds `tabIndex` of `0` when `hasLink` is `true` to make tabbable
Fixes #2385

[B] Fix focusability of event tiles

---

client/src/global/components/form/Switch.js

This fixes an issue introduced in ab61beb that caused the label text in Form.Switch to render above the input even when `props.labelPos` was set to `below`.
Resolves #2378

[B] Fix regression in Form.Switch layout

---

client/src/theme/styles/components/frontend/project/_hero.scss

Because we allow Markdown in project subtitles, we need styling for the off-chance that there are nested `em` and `i` tags, such as in https://manifold.umn.edu/projects/wisconsin-breweries-and-brewpubs.
Resolves #2375

[B] Style italics in project hero subtitles

---

client/src/global/components/form/Upload/index.js

Since we do server-side validation of CSV files, we can safely use [this workaround](https://github.com/react-dropzone/react-dropzone/issues/276#issuecomment-278357061)
for react-dropzone that allows CSV files to be uploaded in MS Edge.
Resolves #2409

[B] Add workaround for Windows CSV upload bug

---

api/app/services/system_upgrades/upgrades/manifold030000.rb

The V3 upgrade involves the migration from Paperclip to Shrine. If we're
unable to find the file associated with a model, we will warn the user
instead of failing.

[B] Rescue file not found exception in v3 upgrade

---

api/app/serializers/v1/concerns/user_attributes.rb
api/app/services/types/serializer.rb
api/spec/api_docs/definitions/resource.rb
api/spec/api_docs/definitions/resources/user.rb

Refactors the existing Users API documentation to use the new dry types.
This one should be more straightforward than the changes made to get the Comments API endpoints, and makes far less changes to the associated resources and dry types.
In addition to documenting the Users endpoints, it also:
* removes the relationships or attributes hash from the response if either of them are empty
* makes a few updates to the custom dry types in the dry types serializer module

[F] Document Users API Endpoints

---

api/app/services/types/serializer.rb
api/spec/api_docs/examples/create.rb
api/spec/api_docs/examples/destroy.rb
api/spec/api_docs/examples/update.rb
api/spec/api_docs/helpers/request.rb

* There is at least one case where the resource returned is `null`. Changing the pointer on the resource to be optional gets the test passing in that case.
* `response_description` seemed to be the more comprehensive choice for all route documentation. I changed cases of direct access to `description` in `api_docs/examples` to `response_description`
* I changed the logic in the `response_description` so it combines description sources rather than returning the first one that is not blank. It makes more sense to me that a developer would want to be able to document something for each route that uses a resource in the resource definition, then add to it in the spec on a route-by-route basis. I'm open to doing it a different way though.

[C] Minor changes to rswag internal interfaces

---

client/src/theme/styles/components/reader/annotations/_popup.scss

When the panel is positioned absolutely, the .annotation-popup ancestor
element does not have height. The popup positioner needs to be able to
accurately determine the height off the .annotation-popup container so
that it can determine whether to position it above or below the
selection. One of the jobs of the popup positioner is to prevent the
popup from colliding with the edges of the window, and it cannot do this
without an accurate height measurement.
Fixes #2469

[B] Restore height to annotation popup wrapper

---

client/src/actions/entityEditor.js
client/src/global/containers/form/Form.js
client/src/store/reducers/entityEditor.js

Prior to this change, any change to a model on a form edit session
would re-open the editing session and the user would lose any unsaved
changes to the model. With this change, the form will attempt to
refresh the existing session rather than opening a new editing session.
The refresh action will update the underyling model for the session and
will loop through any dirty values and see if they are still dirty by
comparing them to the model. Any values that are still dirty will be
persisted into the new editing session.
Fixes #2449

[B] Persist dirty form values when model updates

---

api/spec/services/api_documentation/dry_types_parser_spec.rb

The pointer type of a resource was set to optional and the test needs to reflect that.
Feel free to add any other failed tests fixes to this PR before merging it, or merge this as is.

[B] Fix failed API test

---

api/app/serializers/v1/action_callout_serializer.rb
api/app/services/types/serializer.rb
api/spec/api_docs/definitions/resources/action_callout.rb
api/spec/requests/api/v1/action_callouts_spec.rb

On PATCH for an `ActionCallout`, I tried sending in data like this:
```
{
"data": {
"attributes": {
"attachment": {
"filename": "profile_pic.jpg",
"data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPj/HwADBwIAMCbHYQAAAABJRU5ErkJggg==",
"contentType": "image/jpg"
}
}
}
}
```
The `data` value is a base-64 1x1 blue pixel. This works for setting an avatar image for a user and I was assuming it would work similarly in an `ActionCallout,` but all the `AttachmentStyles` in the `ActionCallout` response are still null.

[WIP] Document ActionCallout API endpoints

---

api/app/serializers/v1/resource_collection_serializer.rb
api/spec/api_docs/definitions/resource.rb
api/spec/api_docs/definitions/resources/resource_collection.rb
api/spec/requests/api/v1/resource_collections_spec.rb

I hit two sticking points in documenting these routes.
1. A 500 response on POST for `/resource_collections` route
2. Not knowing how to attach a `resource_collection` to a `text_section`. 
I looked around in the UI as well as the factory bot and there didn't seem to be an obvious place to attach a resource_collection to a text_section. All tests pass as is, I want to make sure that I am using the `/text_sections/{text_section_id}/relationships/resource_collections` route correctly.
I am happy to go back and fix these if you have some suggestions, or move on and leave them to you.

[WIP] Document ResourceCollection API endpoints

---

api/app/serializers/serializer_registry.rb
api/app/serializers/v1/annotation_serializer.rb
api/spec/api_docs/definitions/resources/annotation.rb
api/spec/requests/api/v1/annotations_spec.rb

Two issues for this group of routes:
1. It appears the show method on the controller that manages the `/annotations/{id}` route requests does not exist
2. I get a 500 response on an index request to `/me/relationships/annotations`. I am not sure if there is something wrong with that one or if I am just accessing the route incorrectly.

[WIP] Document Annotation API endpoints

---

api/app/serializers/v1/event_serializer.rb
api/spec/api_docs/definitions/resources/event.rb
api/spec/requests/api/v1/events_spec.rb

As far as I know, there are no routes that create an event. I'm assuming that it goes on behind the scenes when a user does something to their project. So I marked each field as read_only.

[WIP] Document Events API endpoints

---

api/spec/requests/api/v1/contacts_spec.rb

This route was a very special case.
* It does not have a serializer
* It has an irregular model file name in an irregular place (manifold/api/app/services/contacts/send_message.rb)
* It does not provide any json response on success
* It is the only route of its kind (there is no delete, create, update, get)
As such, it would require many modifications to the code that automates the process of testing and documenting routes, so in this case I decided it was best to keep it very simple and interact with the rswag library directly. 
I don't have any attachments to this solution, so any suggestions on how to improve it is welcome. I'm opening this PR for assistance or discussion on desgin more than I am expecting a quick review for errors. 
If you could also point me to where this is used in …

[WIP] Document Contacts API endpoint

---

api/app/serializers/v1/favorite_serializer.rb
api/spec/api_docs/definitions/resource.rb
api/spec/api_docs/definitions/resources/favorite.rb
api/spec/requests/api/v1/favorites_spec.rb

I had to make a few adjustments to the resource module in order to be able to set relationships as a required field in the request. 
I also figured it wise to not attempt to programmatically document the response behavior for creating a favorite.  In the favorites controller, there is a comment that says the response behavior is rather unexpected and should be refactored at some point, so I documented the response behavior with a simple description on the swagger route.

[WIP] Document Favorite API endpoints

---

api/app/serializers/v1/ingestion_serializer.rb
api/spec/api_docs/definitions/resources/ingestion.rb
api/spec/requests/api/v1/ingestions_spec.rb

I'm having a hard time getting an exact definition or example of the structure of the `source` request attribute for an ingestion. Any help would be appreciated.
The structure I have commented out right now was gathered from the validation for an ingestion:
```
def ingestion_params
params.require(:data)
attributes = [
:external_source_url,
:ingestion_type,
{
source: [
:id,
:storage, { metadata: [:filename, :size, :mime_type] }
]
}
]
relationships = [:text]
param_config = structure_params(
attributes: attributes,
relationships: relationships
)
params.permit(param_config)
end
```

[WIP] Document Ingestion API endpoints

---

api/app/serializers/v1/page_serializer.rb
api/spec/api_docs/definitions/resource.rb
api/spec/api_docs/definitions/resources/page.rb
api/spec/requests/api/v1/pages_spec.rb

These pages have are unique in the aspect that the ID is simply an auto incrementing number. The Resource helper module needed to be adjusted to allow an overwrite of the ID type.

[WIP] Document Pages API endpoints

---

api/app/serializers/v1/current_user_serializer.rb
api/app/services/types/serializer.rb
api/spec/api_docs/definitions/resources/current_user.rb
api/spec/api_docs/helpers/request.rb
api/spec/requests/api/v1/me_spec.rb

While trying to document the `Me` resources, I ran into an error on assigning a dry type to a `typed_attribute`.
I made a note in the serializer_registry where the error is being generated. To replicate the error in a test, run `rspec -fd spec/requests/api/v1/me_spec.rb` from the api folder.

[WIP] Document Me API endpoints

---

api/app/controllers/concerns/validation.rb
api/app/serializers/v1/text_serializer.rb
api/spec/api_docs/definitions/resources/text.rb
api/spec/requests/api/v1/texts_spec.rb

I'm having trouble defining the type on the `toc` for a text and would appreciate some assistance. It looks like it's similar to the issue I was running into here (daac39f6355a185c3c6bfec3255242b1f7771c97) where it needs to be converted to a hash prior to serialization.

[WIP] Document Texts API endpoints

---

api/app/serializers/v1/statistics_serializer.rb
api/spec/api_docs/definitions/resources/statistic.rb
api/spec/api_docs/examples/show.rb
api/spec/api_docs/helpers/request.rb
api/spec/requests/api/v1/statistics_spec.rb
api/spec/requests/api/v1/twitter_queries_spec.rb

This PR:
* Documents the Statistics API endpoints
* Creates a new optional parameter called `instantiate_before_test`, which allows the default behavior of creating a resource with FactoryBot before attempting a `show` request. In this case, the app generates the statistics and there is no factory that would create a statistics database entry, so `instantiate_before_test: false` turns off the attempt to create a statistic.
* To make the response success descriptions line up a little better with the route summary (since they are usually very closely related), if the route does not have a custom success description, it will fall back on the provided summary, and finally the default success description

[WIP] Document Statistics API endpoints

---

api/app/serializers/v1/version_serializer.rb
api/spec/api_docs/definitions/resources/version.rb
api/spec/requests/api/v1/versions_spec.rb

I documented this route and the documentation looks good, but I want to check that the route is working as expected. I'm getting a lot of `null` values in my `objectChanges` attribute. For example, here is one of my versions in the local instance of manifold that I'm working on:
```
{
"id": "cb2d0481-c935-40d6-9c01-5ed7bbce0e5c",
"type": "versions",
"attributes": {
"itemType": "ResourceCollection",
"itemId": "002851b7-afcf-42bd-9b7e-1610d0f1dc88",
"event": "destroy",
"createdAt": "2019-12-30T19:11:26.444Z",
"objectChanges": {
"id": [
"002851b7-afcf-42bd-9b7e-1610d0f1dc88",
null
],
"slug": [
"string",
null
],
"title": [
"this",
null
],
"createdAt": [
"2019-12-19T01:48:36.567Z",
null
],
"projectId": [
"023ebc40-174a-4056-b1e7-de1a1f52d666",
null
],
"description": [
null,
null
], …
```

[F] Document Versions API endpoint

---

api/app/models/ingestion.rb
api/app/services/ingestions/strategies/document.rb
api/spec/services/ingestions/ingestor_spec.rb

Prior to V1, we used a different method for calculating the
source_identifier. When ingestion was refactored, we ended up with a
stable source identifier for all document ingestions. This change led
to an edge case bug. If a user reingested a text that had originally
been ingested under v1 and used a document ingestion strategy, Manifold
will insert a new text section instead of updating the existing one
because the source identifiers do not match. This leads to changed URLs
and losing annotations. No good.
If the following conditions are true, this method will make a quick
update to the existing text_section and associated ingestion_source so
that their identifiers match those of the new ingestion. Once the
identifiers match, the compiler will trigger an update instead of an
insert + …

[B] Address pre-v1 ingestion edge case

---

client/src/backend/containers/form-inputs/connected-inputs/FetchSelect.js
client/src/backend/containers/form-inputs/connected-inputs/PredictiveInput.js
client/src/backend/containers/permission/Form.js
client/src/global/components/form/BelongsTo.js
client/src/global/components/form/HasMany/index.js
client/src/global/components/form/OptionsList.js
client/src/global/components/form/TagList.js

This commit refactors the FetchSelect component to use the native HTML `<select>` element, thus enabling keyboard interaction and improving accessibility.
Resolves #2294

[B] Refactor FetchSelect

---

client/src/frontend/components/resource-player/Video.js
client/src/frontend/components/resource-slide/Loading.js
client/src/frontend/components/resource-slide/Slide.js
client/src/frontend/components/resource-slide/SlideImage.js
client/src/frontend/components/resource-slide/SlidePlaceholder.js

Before Manifold used CSS flex, this code was used to center content in resource slides. After some CSS refactoring, this code is no longer needed. In some cases the `componentDidMount` function was removed and the `ref` was left behind.
Resizing these slides were tested on the newest versions of Chrome, Firefox, Edge and Safari and all work as expected.

[B] Remove legacy centering method

---

api/app/models/text.rb

This commit addresses an issue where a text subtitle could not be
deleted. However, there is a broader issue here that still needs to be
addressed. If a user removes a title from a text and saves it, the API
does not return a proper error message and mark the text as invalid,
which leads to a confusing user experience. The change we made in
9e18e818bd20640649e4a6ae8f685ff7e81c08d2 complicates this. On save, the
invalid blank title is not removed, and there is no error message. We
should solve htis by adjusting the refresh method in the store reducer
to take into account whether the response object has errors, and by
ensuring that a missing title on a text invalidates the model.
Resolves #2661

[B] Allow text subtitle to be cleared

---

client/src/global/components/form/Picker/List.js
client/src/global/components/form/Picker/index.js
client/src/global/components/form/__stories__/Form.stories.js

This fixes just a handful of ARIA attributes, and adds a couple missing ones as well. These changes resolved all errors reported in Axe and the Storybook a11y add-on. I also reviewed the accessibility tree for the component in Firefox dev tools and tested it out in VoiceOver/Safari. VoiceOver's read-out was admittedly not great, but given that the component follows the WAI 1.1 combobox design pattern, and it passed all audits, I feel okay with this. Will test with NVDA also to compare.
The last remaining piece is wiring up the picker to the with-screen-reader-status HOC. When entities are added or removed from the multi-select wells, we should expect an announcement for screen readers, like "{entity.label} added."

[B] Resolve a11y issues in Form.Picker

---

api/app/authorizers/entitlement_authorizer.rb
api/app/controllers/api/v1/entitlements_controller.rb
api/app/controllers/api/v1/projects/relationships/entitlements_controller.rb
api/app/controllers/application_controller.rb
api/app/serializers/v1/entitlement_serializer.rb
api/public/api/static/docs/v1/swagger.json
api/spec/api_docs/definitions/resources/entitlement.rb
api/spec/requests/api/v1/entitlements_spec.rb

Only two things out of the ordinary:
1. The rswag docs were out of sync when I started, so there is a single commit that just updates the docs before I made any documentation changes.
2. There are three GET requests relating to entitlements, `/entitlements`, `/entitlements/{id}` and `/projects/{project_id}/relationships/entitlements`. Only `/entitlements/{id}` requires authorization, out of these three GET requests. The reasoning behind restricting this route does not seem obvious to me, so if you happen to know why the route is restricted, I can add that to the route documentation.

[F] Document Entitlements

---

client/src/frontend/components/layout/Splash.js
client/src/theme/styles/components/frontend/project-collection/_header.scss

* Fixes breakpoint for full-bleed hero layout
* Fixes z-index issue when directly below Splash component

[B] Fix minor PC header style bugs

---

client/src/backend/containers/projects/ProjectsList.js

As I was getting the app set up on my local, I noticed these two backend pages (Projects/Records) were rendering with slightly different padding.
As far as I can tell, `Layout.BackendPanel` isn't doing much in this case and seems like it shouldn't be here.  Other way to go might be adding that wrapper to these record child components.

[C] Remove unneeded wrapper from BE ProjectsList

---

api/app/authorizers/comment_authorizer.rb
api/spec/authorizers/comment_authorizer_spec.rb

Resolves #2832
If a user can read an annotation, they can comment on it, even if public engagement is disabled on the project.

[B] Allow annotation comments when engagement is disabled

---

api/app/serializers/v1/annotation_serializer.rb
api/app/serializers/v1/comment_serializer.rb

Includes the full serialized attributes for the annotation and comment so the UI knows that the user has permission to update and delete a comment or annotation they created. This fixes a regression introduced in cce2225 when abilities were simplified for performance reasons.

[B] Correct annotation and comment serialized abilities

---

client/src/global/components/comment/meta/__tests__/__snapshots__/Meta-test.js.snap
client/src/global/components/comment/meta/index.js

This addition synchronizes the functionality between the two meta components so the author of both an annotation and a comment will see the listed author as "Me". 
This resolves a discrepancy between them, but I think it would be a good idea to combine the annotation and comment meta component into a single generic meta component at some point. They both appear to have the same functionality and the comment meta uses the annotation meta classes for styling.

[C] Unify behavior of annotation and comment

---

client/src/theme/styles/base/structure/_index.scss
client/src/theme/styles/base/structure/_mixins.scss

Issue #2831 is a result of the dhdebates manifold instance including the duplicate structure utility classes. The plugin required some mixins, however these mixins came with utility classes that unintentionally took precedence over custom styles in the plugin and caused bugs.
Splitting the utility classes from the mixins allows other files to import mixins without worrying that the structure utilities will overwrite previously defined values.
This issue will be resolved when the dhdebates plugin imports the mixin file rather than the whole structure folder contents.

[C] Split mixins from structure utility classes

---

api/app/models/collection_project_ranking.rb
api/app/models/project.rb
api/spec/models/project_spec.rb

This removes an extraneous join Rails was adding
that caused duplicate records to be aggregated
when counting on the scope.
Resolves #2818

[B] Fix project counts when ranked by collection

---

api/app/services/analytics/reports/top_searches.rb
api/spec/services/analytics/reports/global_spec.rb

Applies sorting for dedicated view (no change needed for global analytics list)

[B] Fix analytics top search results sorting

---

client/src/global/components/search/results/Types/Generic/index.js

Added `tabIndex` prop to `Link` components created with `wrapWithLink` and set the tab index to -1 on figures to solve improve tabs in search results.
Resolves: #2969

[B] Add tabIndex param to wrapWithLink()

---

client/src/global/components/Overlay/Title.js

Change global overlay title from `h3` to `h2`.
Resolves: #2757

[B] Fix heading level in Overlay

---

client/src/global/components/atomic/EntityAvatar/CoverAvatar.js
client/src/global/components/atomic/EntityAvatar/PlaceholderAvatar.js
client/src/global/components/atomic/EntityAvatar/index.js
client/src/global/components/atomic/EntityAvatar/styles.js
client/src/global/components/atomic/EntityThumbnail/avatar/index.js
client/src/global/components/atomic/EntityThumbnail/index.js

Extract `EntityAvatar` from `EntityThumbnail` for use in heroes and other components. Should be able to completely replace `Project.Avatar`.

[F] Make EntityAvatar atomic component

---

client/src/frontend/components/project/Detail.js

Fixes a mistake in the conditions for showing the 'See All Projects' link at the bottom of project detail pages. Previously we were just checking for the existence of the function rather than running it, so the condition was always true and the link never showed up.
```jsx
{!this.context.isStandalone && !this.isLibraryDisabled && (
<Layout.ButtonNavigation />
)}
```
I've just switched the function to a getter to solve this.

[B] Fix See All link render conditions

---

client/src/backend/components/ingestion/form/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/config/app/locale/en/json/messages.json
client/src/frontend/components/resource-collection/__tests__/__snapshots__/Cover-test.js.snap
client/src/frontend/components/resource-list/__tests__/__snapshots__/Slideshow-test.js.snap
client/src/frontend/components/resource-slide/__tests__/__snapshots__/Caption-test.js.snap
client/src/frontend/components/resource/__tests__/__snapshots__/Detail-test.js.snap
client/src/frontend/components/resource/__tests__/__snapshots__/Link-test.js.snap
client/src/frontend/components/resource/__tests__/__snapshots__/Title-test.js.snap
client/src/frontend/components/resourceish/__tests__/__snapshots__/Thumbnail-test.js.snap
client/src/frontend/components/text/__tests__/__snapshots__/Bibliographic-test.js.snap
client/src/frontend/components/text/__tests__/__snapshots__/Counts-test.js.snap
client/src/frontend/components/utility/__tests__/__snapshots__/Toggle-test.js.snap
client/src/global/components/Annotation/Annotation/SourceSummary/TextTitle.js
client/src/global/components/Annotation/Annotation/SourceSummary/index.js
client/src/global/components/Annotation/Annotation/TextContent/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/global/components/FatalError/__tests__/__snapshots__/FatalError-test.js.snap
client/src/global/components/comment/deleted/__tests__/__snapshots__/Deleted-test.js.snap
client/src/global/components/comment/detail/__tests__/__snapshots__/Detail-test.js.snap
client/src/global/components/comment/meta/__tests__/__snapshots__/Meta-test.js.snap
client/src/global/components/dialog/__tests__/__snapshots__/Confirm-test.js.snap
client/src/global/components/drawer/__tests__/__snapshots__/Wrapper-test.js.snap
client/src/reader/components/Header/__tests__/__snapshots__/Header-test.js.snap
client/src/reader/components/control-menu/__tests__/__snapshots__/AppearanceMenuBody-test.js.snap
client/src/reader/components/notation/resource/__tests__/__snapshots__/Detail-test.js.snap
client/src/reader/components/notes/partial/__tests__/__snapshots__/Filters-test.js.snap
client/src/reader/components/section/__tests__/__snapshots__/NextSection-test.js.snap
client/src/reader/components/section/__tests__/__snapshots__/Pagination-test.js.snap

Adds a wrapper component `TextTitle` because elements that use `dangerouslySetInnerHTML` can't be passed as components directly to `Trans`.

[B] Fix Trans implementation in SourceSummary

---

client/src/frontend/containers/IssuesList/index.js
client/src/frontend/containers/MyReadingGroups/List.js
client/src/frontend/containers/ProjectCollections/index.js
client/src/frontend/containers/Projects/index.js
client/src/frontend/containers/PublicReadingGroups/List.js

* Consider filters when showing RG list placeholder
* Use presence of certain filter keys when showing placeholders for
other FE indexes, rather than `location.search`. Since we always show
URL params for pagination, `!!location.search` was always `true`,
meaning that the placeholder wouldn't appear under any circumstances.

[B] Fix placeholder logic on frontend routes

---

client/src/global/containers/Manifold/index.js
client/src/helpers/router/navigation.js
client/src/store/middleware/currentUserMiddleware.js

The change in 9ccfcb8d811062f43bdcff480161e28c7b70e43c wasn’t a good
solution to the problem described in the commit because it’s difficult
to check settings in the current user middleware. This commit moves the
RG loading into the main Manifold app container and triggers it when a
user logs in, or when the app is mounted.

[B] Correct behavior when RGs are disabled

---

client/src/config/app/locale/en/json/reader.json
client/src/reader/components/annotation/popup/hooks/useAnnotationMenu/index.js
client/src/reader/components/annotation/popup/menus/FollowLink.js
client/src/reader/components/annotation/popup/menus/Login.js
client/src/reader/components/annotation/popup/menus/Main/Items/CurrentReadingGroup.js
client/src/reader/components/annotation/popup/menus/Main/Items/Highlight.js
client/src/reader/components/annotation/popup/menus/Main/index.js
client/src/reader/components/annotation/popup/menus/ReadingGroup.js
client/src/reader/components/annotation/popup/menus/Share.js
client/src/reader/components/annotation/popup/parts/Menu/index.js
client/src/reader/components/section/body-nodes/nodes/Link.js
client/src/reader/components/section/body-nodes/nodes/Text.js
client/src/reader/containers/annotation/annotatable-components/CaptureClick.js
client/src/reader/containers/annotation/annotatable-components/CaptureSelection.js
client/src/reader/containers/annotation/annotatable-components/Popup/LinkMenu.js
client/src/reader/containers/annotation/annotatable-components/Popup/LoginMenu.js
client/src/reader/containers/annotation/annotatable-components/Popup/PrimaryMenu.js
client/src/reader/containers/annotation/annotatable-components/Popup/index.js

This PR addresses browser inconsistencies around using the annotation popup that were introduced by 39ae9d0. That commit refactored the menu using the WAI-ARIA menu design pattern and implemented keyboard functionality for the first time. However, due to the way Safari and Firefox interweave the document's focus and selection states (see https://github.com/ManifoldScholar/manifold/pull/3086#issuecomment-1030141362), when focus was moved around the menu it triggered a loss of selection highlighting in these browsers. Because it did this for both pointer and keyboard interactions, we felt that this was an unacceptable visual regression, even if it didn't impact how Manifold internally tracks a selection for annotating, highlighting, sharing, or attaching a resource to.
As a workaround, this …

[F] Finalize Safari/FF keyboard annotation support

---

client/src/reader/components/annotation/popup/hooks/useAnnotationMenu/index.js
client/src/reader/components/annotation/popup/menus/Main/Items/CurrentReadingGroup.js
client/src/reader/components/annotation/popup/parts/MenuItem/index.js

This commit fixes problems with trying to use the reader annotation popup menu on iOS. Previously when a user tapped a menu item, nothing happening, as the interpreted mouse event `onClick` wasn't firing in response to a touch event as expected. I'm wondering whether this relates to the iOS text selection callout appearing simultaneously, but I'm not sure. (Also, I looked into hiding that callout, but it's not possible.) In any case, I've worked around this by attaching the same `onClick` callbacks in the popup menu to `onTouchEnd` events. I've also added `preventDefault()` for all `onTouchEnd` events so that focus isn't moved away from the current text selection, which causes the menu to become invisible.

[B] Fix annotation popup on iOS

---

client/src/store/reducers/entityStore.js

This behavior is necessary for eager loading annotations in the reader.

[B] Restore prior response append behavior

---

client/src/frontend/components/content-block-list/List.js
client/src/frontend/components/content-block/Block/index.js
client/src/frontend/components/content-block/types/TableOfContents.js
client/src/frontend/components/journal/VolumeDetail/index.js

* Refactors TOC block into function component to fix conflict between
withTranslation HOC and getting static icon/title properties of
component
* Adds option to ContentBlockList to hide default block title if one
isn't specified by user, and applies to TOC block in journal volume
detail view

[B] Revise TOC content block header logic

---

client/src/global/components/sign-in-up/UpdateForm.js
client/src/theme/styles/components/backend/project/avatarBuilder.js
client/src/theme/styles/components/global/checkboxes.js
client/src/theme/styles/components/global/forms/formInputsPrimary.js
client/src/theme/styles/components/global/forms/formInputsSecondary.js
client/src/theme/styles/components/global/forms/shared.js

This lightly refactors radios, checkboxes, and file-type inputs so that
the input itself fills the clickable area and receives the click. This
builds on 5cdedb and solves an issue where form controls in drawers
were failing to respond to pointer clicks.
Resolves MNFLD-409
Resolves #3399

[B] Receive form control clicks directly on input

---

api/app/services/packaging/epub_v3/stylesheet_item.rb

Just use the generated stylesheet name rather than the original source identifier when exporting stylesheets, since there are some legacy models that have duplicated stylesheets, and a fix for those will be more involved.

[C] Allow duplicated stylesheets in exports

---

api/app/services/ingestions/strategies/epub.rb
api/app/services/ingestions/strategies/manifest.rb
api/db/migrate/20231010184158_update_text_section_aggregation_to_version2.rb
api/db/structure.sql
api/db/views/text_section_aggregations_v02.sql
api/spec/services/ingestions/strategies/epub_spec.rb
api/spec/services/ingestions/strategies/manifest_spec.rb

There are fixes here for two bugs related to text section order:
1.  When `spine` was [transitioned to a calculated field](https://github.com/ManifoldScholar/manifold/commit/88ec99fa2968db752d3ea3ca75f676496f1b79c8), `position` for a text section could no longer be 0, but array indices are still used in epub and manifest ingestion to set position. Hence, the section at index 0 is getting shifted to the end of the spine.
2. The `text_section_aggregations` view wasn't updated when [text section positions were migrated](https://github.com/ManifoldScholar/manifold/commit/6de0ef7228e29b956281ca824cded80c5c1744e1) in response to the change above, so autogenerated TOCs aren't reflecting section order.

[B] Ensure spine + auto TOC are correctly calculated 

---

api/config/initializers/15_update_settings_from_env.rb

During initialization, we should check to make sure that the settings are refreshed to the latest version of the cache in order to pick up any new defaults that may have been added.

[C] Ensure settings always have up-to-date FA cache

---

api/app/jobs/attachments/process_attachment_job.rb
api/config/initializers/00_libraries.rb

Processing multiple large GIFs at once seems to cause problems with certain installations and Imagemagick. We will now process attachments serially instead of three at a time.

[C] Lower attachment processing concurrency

---

client/src/theme/styles/base/typography.js

* FF + Safari show broken underlines, especially in list views, without  this offset.

[B] Adjust underline position

---

api/app/models/resource.rb
api/app/models/text.rb
api/app/services/packaging/bag_it_spec/compilation.rb
api/app/services/packaging/bag_it_spec/resources/attachment_proxy.rb
api/app/services/packaging/bag_it_spec/resources/proxy.rb
api/app/services/packaging/preservation/export_project_metadata.rb
api/app/services/utility/index_map.rb
api/spec/services/packaging/bag_it_spec/resources/attachment_proxy_spec.rb
api/spec/services/packaging/bag_it_spec/resources/proxy_spec.rb

* Remove remaining simple text files, inline into respective metadata
* Add created_at / updated_at timestamps to various metadata
* Expose external video service url for vimeo / youtube in metadata
* Enumerate text and resource ids in top-level project metadata
* Bump manifold compilation version to 1.2.0 to signify changes

[F] Improve project exportation / Bag-It packaging

---

api/app/models/text_section.rb
api/spec/services/packaging/epub_v3/text_section_item_spec.rb

* Specifically resolves an issue with finding landmarks in the TextSectionItem wrapper for epubs.
Resolves MNFLD-927

[B] Fix epub generation with non-ingested texts

---

api/app/jobs/annotation_jobs/adopt_or_orphan_job.rb
api/app/services/annotations/adopt_or_orphan.rb
api/app/services/annotations/adoption_assignment.rb
api/config/sidekiq.yml

* Add uniqueness to the job to prevent multiple adoptions for a single annotation
* Add cyclical detections and execution time limits
* Restrict an attempt to locate the character positions from iterating endlessly
* Monitor execution time on various iterations / recursions and bail out if it is taking too long
* Any bailout action will orphan the annotation
Resolves RET-1728

[B] Refactor AdoptOrOrphan job

---

api/app/models/application_record.rb
api/app/models/concerns/filterable.rb
api/app/models/concerns/lazy_ordering.rb
api/app/models/concerns/project_ordering.rb
api/app/models/project.rb
api/app/models/project_collection.rb
api/app/models/reading_group.rb
api/app/models/resource.rb
api/app/models/settings.rb
api/app/models/user.rb
api/app/operations/filtering/apply.rb
api/app/serializers/v1/setting_serializer.rb
api/app/services/filtering/applicator.rb
api/app/services/filtering/config.rb
api/app/services/filtering/sort_mapping.rb
api/app/services/filtering/types.rb
api/app/services/project_collections/cache_collection_projects.rb
api/app/services/setting_sections/general.rb
api/spec/models/project_collection_spec.rb
api/spec/models/project_spec.rb

* Add support for a default scope and auto-detecting based on whether or not the model is orderable, and has default scope method defined
* Detect whether the order param was applied, and if not, apply the default scope
* Expose the ability to set the default scope for projects in settings using the same values as ProjectCollections
* Clean up some of the project collection sorting logic not to be so dependent on raw strings and instead actual programmatic calls
* Use sort title for project collections and universally when sorting projects by title
* Blacklist some params that should not be included in filters ever for any reason
Resolves RET-1727

[F] Improve filterable / ordering

---

api/Gemfile
api/Gemfile.lock
api/app/controllers/api/v1/me/relationships/collectable.rb
api/app/controllers/api/v1/projects_controller.rb
api/app/controllers/api/v1/texts_controller.rb
api/app/jobs/soft_deletions/purge_job.rb
api/app/models/annotation.rb
api/app/models/application_record.rb
api/app/models/concerns/soft_deletable.rb
api/app/models/concerns/timestamp_scopes.rb
api/app/models/ingestion_source.rb
api/app/models/project.rb
api/app/models/text.rb
api/config/sidekiq.yml
api/db/migrate/20241001182627_add_soft_deletion_to_projects_and_texts.rb
api/db/structure.sql
api/spec/jobs/soft_deletions/purge_job_spec.rb
api/spec/requests/projects_spec.rb
api/spec/requests/texts_spec.rb

* This adds logic to background the deletion of models that can take a while to actually delete because of the complexity of their association hierarchies.
* When soft-deleting a project, its texts will also be soft-deleted while the project is being deleted in the background, so that any lookups on the text will 404 as we'd like.
* Update controllers, filterable concern to use soft-deletion scopes when applicable
* Add TimestampScopes helper
* Add some missing inverse associations, minor idiomatic cleanup
Resolves MNFLD-937

[F] Add soft deletion to projects and texts

---

.github/actions/setup-ruby/action.yml
api/spec/rails_helper.rb

There is an underlying issue with the cache-apt-pkgs-action we are using that is yet unresolved, so we are switching to just installing packages manually with apt.
Additionally, rspec will now bail out early if imagemagick is not available instead of letting the whole suite run only to fail in 10m.

[B] Fix GHA apt packages

---

client/src/backend/components/project-collection/List.js
client/src/backend/containers/project-collection/Detail/index.js
client/src/backend/containers/project-collection/New.js
client/src/backend/containers/project-collection/Wrapper.js
client/src/backend/containers/route-containers.js
client/src/backend/routes.js
client/src/global/components/form/Switch/styles.js

This PR resolves a bug where the create new project collection drawer would get into an unusable state after successfully saving a new collection. The form would continue to be in a dirty state prompting a confirm unsaved changes modal to appear rather than closing the drawer. This PR adds a `/project-collections/new` route to create parity between this and other new routes in admin and also handle the form state using consistent routing mechanisms rather than a one-off handler.

[B][F] Convert new project collection to route

---

api/app/controllers/api/v1/reading_groups/relationships/reading_group_categories_controller.rb
api/app/serializers/v1/reading_group_category_serializer.rb
api/db/migrate/20250129200019_add_markdown_only_flag_to_reading_group_categories.rb
api/db/structure.sql
client/src/config/app/locale/en-US/json/frontend/forms.json
client/src/config/app/locale/en-US/json/shared/common.json
client/src/config/app/locale/en-US/json/shared/modals.json
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/CategoryCreator/index.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/CategoryCreator/styles.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/Category.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/parts/CategoryEdit.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/parts/CategoryHeader.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/parts/CategoryRemove.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/parts/MarkdownBody.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/parts/index.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/parts/styles.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/SortableCategories/styles.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/index.js
client/src/frontend/components/collecting/reading-group/edit/CollectionEditor/styles.js
client/src/frontend/components/collecting/reading-group/static/Category/index.js
client/src/frontend/components/collecting/reading-group/static/Category/styles.js
client/src/global/components/UserMenuButton/styles.js
client/src/theme/styles/mixins/appearance.js

Also, fixes..
1. Missing focus styles for action buttons in dnd list
2. Keyboard move controls for collectables

[F] Add markdown blocks to RG homepage

---

api/app/authorizers/journal_authorizer.rb
api/app/enums/role_name.rb
api/app/models/journal_issue.rb
api/spec/authorizers/journal_authorizer_spec.rb

This PR adds a new user role, `JournalEditor`, designed to allow users to better control permissions granted to journals and journal issues as a whole. Any user with the role journal editor can read and edit an existing journal, as well as create, read, edit, delete, and control permissions to any issue within that journal.
Journal Editor is a scoped role, like Project Editor. So a user who is a Journal Editor on one journal may not be a journal editor on another journal. This also means that when assigning a journal editor role, front end must include the id of the record to scope the role to.
Some points for discussion:
- How many permissions should a journal editor have over journal issues? Currently they have full control (the same as other relevant roles like ProjectEditor), however …

Add journal editor role to backend

---

api/app/authorizers/entitlement_authorizer.rb
api/app/authorizers/permission_authorizer.rb
api/app/authorizers/project_authorizer.rb
api/app/controllers/api/v1/journal_issues_controller.rb
api/app/controllers/api/v1/journals/relationships/journal_issues_controller.rb
api/app/controllers/concerns/authorizes_json_api_relationships.rb
api/app/services/journal_issues/create.rb
api/config/initializers/authority.rb
api/db/structure.sql
api/spec/authorizers/comment_authorizer_spec.rb
api/spec/authorizers/export_target_authorizer_spec.rb
api/spec/authorizers/journal_authorizer_spec.rb
api/spec/authorizers/permission_authorizer_spec.rb
api/spec/authorizers/project_authorizer_spec.rb
api/spec/factories/journal_issue.rb
api/spec/factories/project.rb
api/spec/requests/journals/relationships/journal_issues_controller_spec.rb
api/spec/support/requests/authenticated_request.rb

This PR fixes some bugs where journal editors were able to view journal issues, but not the projects within the journal issues (which basically means they couldn't view the issues).

[F] Journal editor is allowed to create, read, update, delete projects within journal

---

api/Gemfile
api/Gemfile.lock
api/README.md
api/app/models/annotation.rb
api/app/models/concerns/filterable.rb
api/app/models/concerns/has_keyword_search.rb
api/app/models/event.rb
api/app/models/ingestion_source.rb
api/app/models/journal.rb
api/app/models/journal_issue.rb
api/app/models/maker.rb
api/app/models/project.rb
api/app/models/resource.rb
api/app/models/resource_collection.rb
api/app/models/subject.rb
api/app/models/tag.rb
api/app/models/text.rb
api/app/models/user.rb
api/app/operations/filtering/apply.rb
api/app/services/filtering/postgres/applicator.rb
api/db/migrate/20250312204629_create_pg_search_documents.rb
api/db/structure.sql
api/spec/factories/journal_issue.rb
api/spec/operations/filtering/apply_spec.rb

This implements a separate Filtering applicator that supports using the `pg_search` gem rather than `searchkick`. It also modifies several models to support `pg_search` based filtering. Currently `pg_search` can be activated in an environment by setting an environment variable 'USE_PG_SEARCH' to true.
See the [apply_spec.rb](https://github.com/ManifoldScholar/manifold/pull/3826/files#diff-b30e9927ac51020b121370585eedf262f974a082a2467e8e348beeff4b58b298) for a list of currently supported models
- entitlement
- annotation
- reading group
- comment
- pg_search [can search through associations](https://github.com/Casecommons/pg_search?tab=readme-ov-file#searching-through-associations), but it's somewhat limited. It can't search more than one association deep, and it doesn't index the …

[F] Implement PG search filtering

---

client/src/frontend/components/collecting/Toggle/index.js
client/src/frontend/components/collecting/helpers.js
client/src/hooks/useListQueryParams/index.js
client/src/reader/components/TextTitles/index.js

This PR resolves two bugs:
1. Because of the conditional renders removed to fix Reader SSR, links to the annotation drawer from My Notes can 500 if the relevant text hasn't previously been loaded.
2. The formats filter isn't explicitly set as an array if only one query param is present on first load. If it is sent as a string, the api ignores it and returns unwanted results.

[B] Fix notes links 500 + formats filter

---

client/src/global/components/Annotation/Annotation/TextContent/FromNodes/index.js
client/src/global/components/atomic/Box/index.js
client/src/reader/components/resource-annotation/Block/index.js
client/src/reader/components/resource-annotation/Block/styles.js
client/src/reader/components/resource-annotation/Marker/Thumbnail/Mobile/index.js
client/src/reader/components/resource-annotation/Marker/index.js
client/src/reader/containers/Annotatable/Popup/usePositioner.js
client/src/reader/containers/Annotatable/handlers/CaptureSelection.js

Fixes preexisting bug where multiple ranges in FF selections were ignored and adds support for selection where the content includes a resource annotation.
Known issues:
- Update: I had created an edge case here where the last node in included in the selection grabbed by the highlight click was empty. Added a fix to account for this. The fix also revealed that my previous attempt at omitting resource block content from annotation subjects wasn't nuanced enough. Added a fix for this too.

[POC] Handle selection around resources
