- client/src/components/reader/SectionPagination.js
- client/src/containers/reader/Reader.js
> [F] Adjust pagination to use textSection Array

- api/app/services/validator/constants.rb
- api/app/services/validator/tag.rb
- api/spec/services/validator/html_spec.rb
> [F] Blacklist max-width on EPub images and figures

- client/src/components/reader/Annotatable/AnnotationPopup.js
> [B] Position annotator only when selection exists

- client/src/components/frontend/BackLinkPrimary.js
- client/src/components/frontend/BackLinkSecondary.js
- client/src/components/frontend/FormsStatic.js
- client/src/components/frontend/ResourceList.js
- client/src/components/frontend/index.js
- client/src/containers/frontend/ProjectResources.js
- client/src/theme/Components/browse/_index.scss
- client/src/theme/Components/browse/_list-pagination.scss
- client/src/theme/Components/browse/project-detail/_resource-list.scss
- client/src/theme/Components/browse/project-detail/_resource-listing.scss
- client/src/theme/Components/shared/_buttons.scss
- client/src/theme/Components/shared/forms/_list-filter.scss
- client/src/theme/assets/svg/fonts/manicon/arrow-down.svg
- client/src/theme/assets/svg/fonts/manicon/arrow-long-left.svg
- client/src/theme/assets/svg/fonts/manicon/arrow-long-right.svg
- client/src/theme/assets/svg/fonts/manicon/triangle-right.svg
DELIVERS #131321709
Stub markup/styles are built for full resources list with filters
> [F] Complete styles for resources (all) list

- client/src/containers/frontend/NotFound.js
- client/src/routes.js
- client/src/theme/Components/browse/_404.scss
- client/src/theme/Components/browse/_index.scss
- client/src/theme/assets/svg/fonts/manicon/bang.svg
- client/src/theme/assets/svg/fonts/manicon/octagon.svg
> [F] Built styles and markup for responsive 404

- client/src/components/global/SignInUp/Overlay.js
- client/src/theme/Components/_index.scss
- client/src/theme/Components/_overlay-full.scss
- client/src/theme/Components/login/_index.scss
- client/src/theme/_z-stack.scss
Introduces .overlay-full styles that can be reused in other overlays.
[Delivers #130989129]
> [B] Abstract login overlay styles

- client/src/components/reader/Annotatable/AnnotationPopup.js
- client/src/components/reader/Section/Section.js
- client/src/theme/Components/reader/_annotation-popup.scss
- client/src/theme/Components/reader/_text-section.scss
- client/src/theme/STACSS/_typography.scss
> [B] Add responsive font-styles to reader

- client/src/components/frontend/Maker/Avatar.js
- client/src/theme/Components/browse/project-detail/_hero.scss
- client/src/theme/STACSS/_appearance.scss
[F] Add placeholder avatar to makers
FEATURE #134522099
> [F] Add placeholder avatar to makers

- client/src/components/backend/ProjectList/SearchableList.js
- client/src/components/backend/UserList/SearchableList.js
- client/src/containers/backend/Users/List.js
- client/src/theme/Components/backend/_index.scss
- client/src/theme/Components/backend/_vertical-list.scss
- client/src/theme/Components/backend/project/_index.scss
FEATURE #136446591
Fold user list into refactored vertical list
> [F] Fold user list into refactored vertical list

- client/src/components/backend/Project/Header.js
- client/src/components/frontend/Utility/BackLinkPrimary.js
- client/src/theme/Components/shared/_buttons.scss
> [B] Update back-link width in backend

- client/src/components/backend/ProjectList/SearchableList.js
- client/src/components/backend/UserList/SearchableList.js
- client/src/theme/Components/backend/_vertical-list.scss
- client/src/theme/Components/shared/forms/_form-inputs-custom.scss
- client/src/theme/Components/shared/forms/_index.scss
> [F] Complete backend drawer markup/styles

- client/src/components/backend/Form/Switch.js
- client/src/components/backend/Form/index.js
- client/src/theme/Components/backend/_dialog.scss
- client/src/theme/Components/shared/forms/_form-inputs-custom.scss
- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
> [F] Add stub component for boolean switch

- client/src/components/backend/Form/Dropdown.js
- client/src/components/backend/Form/index.js
- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
Add stub component for Form.Dropdown
FEATURE DELIVERS #136447267
> [F] Add stub component for Form.Dropdown

- client/src/components/backend/Form/__tests__/__snapshots__/HasMany-test.js.snap
- client/src/containers/backend/Form/PredictiveInput.js
- client/src/theme/Components/backend/forms/_input-predictive.scss
FEATURE DELIVERS #136445707
Also fix 1px jump on input focus
> [F] Add keyboard controls to has many dropdown

- client/src/components/backend/Form/Dropdown.js
- client/src/components/backend/Form/HasMany.js
- client/src/components/backend/Form/Helpers/SwitchInput.js
- client/src/components/backend/Form/Helpers/index.js
- client/src/components/backend/Form/MaskedTextInput.js
- client/src/components/backend/Form/README.md
- client/src/components/backend/Form/Radios.js
- client/src/components/backend/Form/Save.js
- client/src/components/backend/Form/Select.js
- client/src/components/backend/Form/Switch.js
- client/src/components/backend/Form/TextArea.js
- client/src/components/backend/Form/TextInput.js
- client/src/components/backend/Form/Upload.js
- client/src/components/backend/Form/index.js
- client/src/theme/Components/shared/forms/_form-inputs-custom.scss
> [F] Wire up switch component

- api/app/serializers/collection_serializer.rb
- api/app/serializers/resource_serializer.rb
- api/app/serializers/text_partial_serializer.rb
- client/src/components/frontend/Event/Body/Added.js
- client/src/components/frontend/Event/Body/Attributable.js
- client/src/components/frontend/Event/Body/Created.js
- client/src/components/frontend/Project/Thumbnail.js
- client/src/components/frontend/Resource/Card.js
- client/src/components/frontend/Resource/Hero.js
- client/src/components/frontend/Resource/Meta.js
- client/src/components/frontend/ResourceCollection/Detail.js
- client/src/components/frontend/ResourceList/Slide/Slide.js
- client/src/components/frontend/Text/Thumbnail.js
- client/src/components/global/FormattedDate.js
- client/src/components/global/__tests__/FormattedDate-test.js
- client/src/components/global/index.js
- client/src/containers/backend/ProjectDetail/Texts.js
> [C] Refactor date-fns into utility component

- client/src/components/backend/Form/Helpers/SwitchInput.js
> [B] Fix issue with switches only going one way

- api/app/controllers/api/v1/settings_controller.rb
- api/app/controllers/concerns/validation.rb
- api/app/lib/updaters/settings.rb
- api/app/models/settings.rb
- api/app/serializers/settings_serializer.rb
- api/db/migrate/20170126191544_add_attachment_press_logo_to_settings.rb
- api/db/schema.rb
- client/src/components/backend/Layout/Header.js
- client/src/components/backend/Settings/Navigation.js
- client/src/components/frontend/Layout/Header.js
- client/src/components/global/PressLogo.js
- client/src/components/global/index.js
- client/src/containers/backend/Backend.js
- client/src/containers/backend/Settings/General.js
- client/src/containers/backend/Settings/PressLogo.js
- client/src/containers/backend/Settings/Wrapper.js
- client/src/containers/backend/Settings/index.js
- client/src/containers/frontend/Frontend.js
- client/src/routes.js
- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
- client/src/theme/STACSS/_structure.scss
> [F] Allow press logos to be uploaded

- api/app/controllers/concerns/validation.rb
- api/app/lib/statistics.rb
- api/app/serializers/settings_serializer.rb
- api/app/services/factory/analytics_session.rb
- client/src/containers/backend/Settings/Theme.js
- client/src/helpers/Html.js
> [F] Set Typekit ID through admin settings

- client/src/containers/frontend/Home.js
> [C] Use lamp icon for featured projects on home

- client/src/components/frontend/ResourceList/Slideshow.js
> [F] Add keyboard controls to slideshow

- api/app/controllers/api/v1/projects_controller.rb
- api/app/controllers/api/v1/text_sections/relationships/annotations_controller.rb
- api/app/controllers/api/v1/text_sections/relationships/resources_controller.rb
- api/app/models/annotation.rb
- api/app/models/concerns/collaborative.rb
- api/app/models/resource.rb
- api/app/models/text_section.rb
- api/app/serializers/annotation_serializer.rb
- api/app/serializers/resource_partial_serializer.rb
- api/app/serializers/resource_serializer.rb
- api/app/services/serializer/html.rb
- api/config/environments/development.rb
- api/config/locales/services/ingestor/strategy/epub/en.yml
- api/config/routes.rb
- api/db/migrate/20170131172250_add_resource_to_annotations.rb
- api/db/migrate/20170131211446_add_resources_to_annotations.rb
- api/db/schema.rb
- api/lib/tasks/db.rake
- api/lib/tasks/import.rake
- api/lib/tasks/ingest.rake
- api/spec/factories/annotations.rb
- api/spec/models/annotation_spec.rb
- api/spec/services/serializer/html_spec.rb
- client/src/actions/entityStore.js
- client/src/api/resources.js
- client/src/components/reader/Annotatable/Annotatable.js
- client/src/components/reader/Annotatable/AnnotationPopup.js
- client/src/components/reader/Section/BodyNodes/TextNode.js
- client/src/components/reader/Section/ResourceMarker.js
- client/src/containers/reader/Reader.js
> [F] Add validation to annotations model

- api/app/services/demonstration/data_loader.rb
- api/spec/services/demonstration/data_loader.rb
[Delivers #138663937]
[Delivers #138667707]
> [F] Add settings and reindexing into dev load

- api/app/controllers/api/v1/statistics_controller.rb
> [C] Cache statistics for 3 hours

- api/app/services/ingestor.rb
- api/app/services/ingestor/inspector/html/html.rb
- api/app/services/ingestor/inspector/html/ingestion_source.rb
- api/app/services/ingestor/inspector/html/stylesheet.rb
- api/app/services/ingestor/inspector/html/text_section.rb
- api/app/services/ingestor/inspector/html/title.rb
- api/app/services/ingestor/strategy/abstract_builder.rb
- api/app/services/ingestor/strategy/gitbook/inspector/gitbook.rb
- api/app/services/ingestor/strategy/google_doc/builder.rb
- api/app/services/ingestor/strategy/google_doc/inspector/google_doc.rb
- api/app/services/ingestor/strategy/google_doc/inspector/ingestion_source.rb
- api/app/services/ingestor/strategy/google_doc/inspector/stylesheet.rb
- api/app/services/ingestor/strategy/google_doc/inspector/text_section.rb
- api/app/services/ingestor/strategy/google_doc/inspector/title.rb
- api/app/services/ingestor/strategy/google_doc/strategy.rb
- api/app/services/ingestor/strategy/word/builder.rb
- api/app/services/ingestor/strategy/word/inspector/ingestion_source.rb
- api/app/services/ingestor/strategy/word/inspector/stylesheet.rb
- api/app/services/ingestor/strategy/word/inspector/text_section.rb
- api/app/services/ingestor/strategy/word/inspector/title.rb
- api/app/services/ingestor/strategy/word/inspector/word.rb
- api/app/services/ingestor/strategy/word/strategy.rb
- api/config/initializers/add_ingestor_strategies.rb
- api/lib/tasks/ingest.rake
- api/spec/services/ingestor/strategy/word/builder.rb
- api/spec/services/ingestor/strategy/word/inspector/ingestion_source_spec.rb
- api/spec/services/ingestor/strategy/word/inspector/text_section_spec.rb
- api/spec/services/ingestor/strategy/word/inspector/title_spec.rb
- api/spec/services/ingestor/strategy/word/inspector/word_spec.rb
- api/spec/support/ingestion/word_ingestion.rb
[Delivers #114696225]
[Delivers #138742601]
> [F] Ingests a word/google doc as HTML

- client/src/containers/backend/ProjectDetail/Resources.js
- client/src/theme/Components/shared/_section-heading-secondary.scss
> [F] Add header to backend resource list

- api/app/controllers/concerns/validation.rb
- api/app/serializers/text_partial_serializer.rb
- client/src/components/global/Helper/SimpleFormat.js
- client/src/components/reader/Footer.js
- client/src/components/reader/__tests__/Footer-test.js
- client/src/components/reader/__tests__/__snapshots__/Footer-test.js.snap
- client/src/containers/backend/TextDetail/General.js
- client/src/containers/reader/Reader.js
> [F] Use text's rights attribute for reader footer

- api/app/serializers/text_partial_serializer.rb
- api/app/services/ingestor/strategy/gitbook/inspector/gitbook.rb
- api/spec/factories/text.rb
- client/src/components/reader/Section/NextSection.js
- client/src/components/reader/Section/__tests__/NextSection-test.js
- client/src/components/reader/Section/__tests__/__snapshots__/NextSection-test.js.snap
- client/src/components/reader/Section/index.js
- client/src/containers/reader/Reader.js
- client/src/theme/Components/reader/_index.scss
- client/src/theme/Components/reader/_section-next-section.scss
> [F] Display next section title in reader

- client/src/components/frontend/Project/Hero.js
> [B] Hide hashtag symbol when hashtag not present

- api/Gemfile
- api/Gemfile.lock
- api/app/controllers/concerns/validation.rb
- api/app/models/resource.rb
- api/app/serializers/resource_serializer.rb
- api/app/services/importer/drive_resources.rb
- api/config/initializers/acts_as_taggable_on.rb
- api/db/migrate/20170213172354_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
- api/db/migrate/20170213172355_add_missing_unique_indices.acts_as_taggable_on_engine.rb
- api/db/migrate/20170213172356_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
- api/db/migrate/20170213172357_add_missing_taggable_index.acts_as_taggable_on_engine.rb
- api/db/migrate/20170213172358_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
- api/db/migrate/20170213172359_add_missing_indexes.acts_as_taggable_on_engine.rb
- api/db/schema.rb
- api/spec/models/resource_spec.rb
- client/src/components/frontend/Resource/Meta.js
- client/src/containers/backend/ResourceDetail/General.js
> [F] Adds tagging to resources

- api/app/serializers/text_partial_serializer.rb
- client/src/components/frontend/Text/Thumbnail.js
> [F] Implement text annotation counts on text thumb

- api/app/services/ingestor/strategy/google_doc/inspector/google_doc.rb
> [B] Fix Google Doc ingestion strategy

- api/app/authorizers/annotation_authorizer.rb
- api/app/controllers/api/v1/text_sections/relationships/annotations_controller.rb
- api/config/routes.rb
- api/spec/requests/text_sections/relationships/annotations_spec.rb
- client/src/api/requests.js
- client/src/api/resources/annotations.js
- client/src/components/frontend/Resource/Thumbnail.js
- client/src/components/global/Developer/Debugger.js
- client/src/components/global/Developer/index.js
- client/src/components/global/index.js
- client/src/components/reader/Annotation/Popup.js
- client/src/components/reader/Resource/Viewer/Group.js
- client/src/components/reader/Resource/Viewer/List.js
- client/src/components/reader/Resource/Viewer/Single.js
- client/src/components/reader/Resource/Viewer/Wrapper.js
- client/src/containers/backend/Form/Form.js
- client/src/containers/global/HigherOrder/RequireRole.js
- client/src/theme/Components/browse/resource/_thumbnail.scss
- client/src/theme/Components/reader/_resource-viewer.scss
- client/src/theme/assets/svg/fonts/manicon/x-bold.svg
> [F] Add delete icon on resource viewer singles

- api/app/services/ingestor/strategy/abstract_builder.rb
- api/app/services/ingestor/strategy/epub/inspector/text_section.rb
> [B] Fix ePub TOC page identification

- client/src/components/frontend/Resource/Detail.js
> Hide “view in text” button on resources [#140527515]

- api/app/models/concerns/attachments.rb
- api/app/models/resource.rb
- api/config/manifold.yml
[Delivers #141530937, #141530925, #141530919]
> [F] Generate thumbnails for PDFs

- client/src/containers/frontend/Following.js
> [B] Reset followed project filters if no results

- client/src/components/reader/Annotation/Editor.js
- client/src/containers/global/Comment/Editor.js
> [C] Display errors in annotation/comments form

- client/src/actions/entityEditor.js
- client/src/components/backend/Form/Save.js
- client/src/components/backend/Form/Select.js
- client/src/components/backend/Form/setter.js
- client/src/containers/backend/NewProject/Wrapper.js
- client/src/containers/backend/NewResource/Wrapper.js
- client/src/store/reducers/entityEditor.js
- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
> Backend Form component fixes and updates

- client/src/containers/frontend/Following.js
- client/src/containers/frontend/Home.js
- client/src/theme/Components/reader/annotation/_detail.scss
> A couple small fixes

- api/app/models/project.rb
- api/app/models/text.rb
- api/app/serializers/project_partial_serializer.rb
- client/src/components/frontend/Project/Thumbnail.js
- client/src/theme/Components/browse/project-list/_grid-project.scss
> [F] Display updated alert in project grid

- api/app/controllers/api/v1/passwords_controller.rb
- api/app/mailers/reset_password_mailer.rb
- api/app/models/user.rb
- api/app/views/reset_password_mailer/admin_reset_email.html.erb
- api/app/views/reset_password_mailer/admin_reset_email.text.erb
- api/config/routes.rb
- api/spec/models/user_spec.rb
- client/src/api/resources/passwords.js
- client/src/components/backend/Dialog/ResetPassword.js
- client/src/components/backend/Dialog/index.js
- client/src/containers/backend/People/Makers/Edit.js
- client/src/containers/backend/People/Users/Edit.js
> [F] Implement admin password reset abilities

- client/src/components/frontend/ResourceList/Filters.js
- client/src/containers/frontend/ProjectResources.js
> [F] Update URL when resource filters are changed

- bin/manifold
- bin/puma
* Improve how the puma script finds its Gemfile
* Use locally-installed eslint & jest rather than
relying on globals
> [C] Finesse executables

- api/Gemfile
- api/Gemfile.lock
- api/app/lib/render_without_wrap.rb
- api/app/models/concerns/has_formatted_attributes.rb
- api/app/models/concerns/with_markdown.rb
- api/app/models/project.rb
- api/app/models/resource.rb
- api/app/services/formatted_attributes/definition.rb
- api/app/services/formatted_attributes/methods.rb
- api/app/services/simple_formatter.rb
- api/config/application.rb
- api/config/cable.yml
- api/config/environments/development.rb
- api/config/initializers/00_libraries.rb
- api/config/initializers/sidekiq_and_redis.rb
- api/db/migrate/20170404222122_remove_formatted_attributes.rb
- api/db/schema.rb
- api/lib/manifold_env.rb
- api/lib/manifold_env/redis_config.rb
- api/spec/services/formatted_attributes/definition_spec.rb
- api/spec/services/formatted_attributes/methods_spec.rb
- api/spec/services/simple_formatter_spec.rb
- api/spec/support/matchers/be_wrapped_with.rb
> [F] Store formatted attributes in Redis

- client/src/components/reader/Resource/Marker.js
- client/src/theme/Components/reader/_index.scss
- client/src/theme/Components/reader/_resource-marker.scss
- client/src/theme/Components/reader/_text-section.scss
- client/src/theme/_variables.scss
> [B] Fix issue with resource markers not highlighting

- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
> [B] Fix long file names overflowing dropzone

- client/src/theme/Components/shared/_drawer.scss
> [B] Reset default text color in dark reading mode

- api/app/controllers/concerns/validation.rb
- api/app/models/user.rb
- api/app/services/seed.rb
- api/db/migrate/20170406200143_add_default_role_to_users.rb
- api/db/schema.rb
- api/spec/factories/user.rb
- api/spec/models/user_spec.rb
- api/spec/requests/users_spec.rb
- client/src/containers/backend/People/Users/Edit.js
- client/src/theme/Components/backend/_drawer.scss
> [F] Allow admin to change a user's role

- client/src/components/global/Utility/EdgeLockScroll.js
- client/src/theme/_z-stack.scss
> [B] Fix backend drawer scroll-to-bottom

- client/src/components/reader/Annotation/Popup/Wrapper.js
> [B] Fix popup position in Firefox

- client/src/components/backend/Form/Upload.js
- client/src/theme/Components/browse/resource/_thumbnail.scss
- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
> [B] Fix upload display in FF/Safari

- api/app/services/ingestor/strategy/gitbook/inspector/gitbook.rb
> [B] Add root dir detection in Gitbook ingestion

- client/src/theme/Components/browse/event/_events.scss
[Fixes #241]
Also fixes es linter error in annotation popup
> [B] Fix events list responsive regressions

- client/src/theme/Components/browse/resource/_thumbnail.scss
- client/src/theme/Components/reader/_resource-viewer.scss
> [B] Remove text transition on resource previews

- api/app/serializers/project_partial_serializer.rb
- api/app/serializers/project_serializer.rb
- client/src/components/backend/List/Searchable.js
- client/src/containers/backend/ProjectDetail/Resources.js
- client/src/theme/Components/backend/forms/_search-filter.scss
> [F] Add toggleable filters to backend search

- api/app/models/text_section.rb
- api/app/serializers/text_section_partial_serializer.rb
- api/db/migrate/20170414235108_convert_body_json.rb
- api/db/schema.rb
> [F] Convert `TextSection#body_json` to JSONB

- api/app/services/ingestor/transformer/text_section.rb
- api/app/services/serializer/html.rb
* Small demeter fix in `Serializer::Html`
> [B] Fix ingestion of serialized body nodes

- client/src/components/frontend/ResourceList/Slide/SlideVideo.js
> [B] Don't show related videos in youtube player

- client/src/components/frontend/ResourceCollection/Detail.js
- client/src/components/frontend/ResourceCollection/__tests__/Detail-test.js
- client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/containers/frontend/CollectionDetail.js
- client/src/test/fixtures/build.js
- client/src/test/fixtures/entity.js
- client/src/test/fixtures/pagination.js
- client/src/test/fixtures/store.js
> [F] Append collection resource filters as url params

- client/src/components/frontend/Project/Resources.js
- client/src/containers/frontend/CollectionDetail.js
- client/src/containers/frontend/ProjectResources.js
- client/src/containers/frontend/__tests__/CollectionDetail-test.js
- client/src/containers/frontend/__tests__/ProjectResources-test.js
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ProjectResources-test.js.snap
- client/src/utils/entityUtils.js
> [B] Fix resource pagination losing filters

- api/app/services/ingestor/strategy/google_doc/inspector/google_doc.rb
> [B] Ensure valid UTF-8 encoding for google doc ingestion

- api/app/serializers/collection_serializer.rb
- api/app/serializers/project_partial_serializer.rb
> [B] Sort resource tags alphabetically

- client/src/theme/Components/backend/_vertical-list.scss
> [B] Fix variance in backend list icon size

- client/src/components/backend/Dialog/Confirm.js
- client/src/theme/Components/shared/_buttons.scss
> [B] Add hover states to modal buttons

- client/src/theme/Components/backend/_panel.scss
> [B] Fix alignment in backend secondary nav

- client/src/theme/Components/backend/ingestion/_output.scss
- client/src/theme/Components/backend/project/_header.scss
> [B] Remove generic <span> styles in entity header

- client/src/components/reader/FooterMenu.js
- client/src/containers/reader/Reader.js
- client/src/theme/Components/reader/_header-reader.scss
- client/src/theme/Components/reader/_visibility-button.scss
> [B] Move reader visibility to footer on mobile

- api/app/jobs/fetch_resource_thumbnail.rb
- api/app/models/concerns/resource_attribute_resets.rb
- api/app/models/resource.rb
- api/app/models/thumbnail_fetch_attempt.rb
- api/app/services/thumbnail/fetcher.rb
- api/db/migrate/20170503180816_create_thumbnail_fetch_attempts.rb
- api/db/schema.rb
- api/spec/models/resource_spec.rb
- client/src/components/backend/Resource/Form/Kind/Variants.js
> [F] Add job to fetch external video thumbnails

- api/app/controllers/concerns/validation.rb
- api/app/models/resource.rb
- api/db/migrate/20170426230747_add_comments_count_to_resources.rb
- api/lib/tasks/ingest.rake
- api/spec/requests/comments_spec.rb
- client/src/components/frontend/Resource/Detail.js
- client/src/components/global/Comment/Detail.js
- client/src/containers/backend/ProjectDetail/Events.js
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ProjectResources-test.js.snap
- client/src/containers/global/Comment/Editor.js
- client/src/theme/Components/backend/_panel.scss
- client/src/theme/Components/browse/resource/_detail.scss
- client/src/theme/Components/browse/resource/_meta.scss
> [F] Implement comments on resource detail

- client/src/components/global/HeaderNotifications.js
- client/src/components/reader/Resource/Viewer/Group.js
- client/src/components/reader/Resource/Viewer/Single.js
- client/src/components/reader/ReturnMenu/Body.js
> [B] Correct firefox resource icon hover in FF

- api/app/controllers/api/v1/texts_controller.rb
- api/app/controllers/concerns/validation.rb
- api/lib/tasks/ingest.rake
- client/src/api/notifications.js
- client/src/containers/backend/Form/Collaborators.js
- client/src/containers/backend/TextDetail/Collaborators.js
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/theme/Components/backend/_panel.scss
Also includes lint/test snapshot fixes
> Fixes issue with a text's contributors/authors not updating

- client/src/theme/Components/browse/project/_hero.scss
> [B] Fix social icon sizing on project detail hero

- api/app/models/concerns/attachments.rb
> [B] Fix manifold attachments to preserve transparency

- api/app/lib/updaters/text.rb
- client/src/containers/backend/ProjectDetail/Texts.js
> [B] Fix issue with project text position not updating

- api/app/serializers/page_partial_serializer.rb
- client/src/components/frontend/Layout/Footer.js
- client/src/components/frontend/Layout/__tests__/Footer-tests.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/Footer-tests.js.snap
Only show Page records in footer if they have the attribute `show_in_footer`
> [B] Footer text nav has incorrect top margin

- client/src/components/backend/Dialog/Confirm.js
- client/src/components/backend/Dialog/ResetPassword.js
- client/src/components/backend/Dialog/__tests__/Confirm-test.js
- client/src/components/backend/Dialog/__tests__/__snapshots__/Confirm-test.js.snap
- client/src/components/backend/Drawer/Wrapper.js
> [F] Enable keyboard controls for modals

- client/src/theme/Components/shared/forms/_form-inputs-primary.scss
Gracefully degrades the width of the year input in the date form field so that the date fits on one line all the way down to mobile screen sizes
Fixes #326
> [B] Makes date form field responsive

- api/app/serializers/resource_partial_serializer.rb
- api/app/serializers/resource_serializer.rb
- client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/components/frontend/ResourceList/Slide/Caption.js
- client/src/components/frontend/ResourceList/Slide/__tests__/__snapshots__/Caption-test.js.snap
- client/src/components/frontend/ResourceList/__tests__/__snapshots__/Slideshow-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/theme/Components/shared/forms/_form-inputs-primary.scss
> [B] Enable download link and fix SSR mismatch

- client/src/components/backend/Project/Form/AvatarBuilder.js
- client/src/theme/Components/backend/project/_avatar-builder.scss
> [B] Fix missing margin in BackendProjectDetail form

- client/src/containers/backend/Settings/Theme.js
> [B] Fix incorrect attributes on PressLogo upload

- api/app/services/factory/event.rb
> [B] Fix resource event url

- client/src/containers/reader/Annotation/Annotatable.js
- client/src/store/middleware/entityStoreMiddleware.js
- client/src/store/reducers/entityStore.js
> [B] Fix issue with resource marker not updating on delete

- api/app/models/text.rb
> [F] Destroy text_created event when text is removed

- api/app/models/concerns/metadata.rb
- api/spec/models/project_spec.rb
- client/src/components/frontend/Project/Detail.js
> [B] Don't display project metadata if no entries

- api/app/models/resource.rb
- api/spec/models/resource_spec.rb
> [B] Delete associated annotations with resource

- client/src/components/frontend/ProjectList/Following.js
- client/src/components/frontend/ProjectList/__tests__/Following-test.js
- client/src/components/frontend/ProjectList/__tests__/__snapshots__/Following-test.js.snap
- client/src/components/frontend/ProjectList/index.js
- client/src/containers/frontend/Following.js
> [B] Make followed projects into a component

- api/app/services/ingestor/strategy/google_doc/strategy.rb
- api/spec/services/ingestor/strategy/google_doc/strategy_spec.rb
> [B] Replace invalid chars in gdoc ingestion

- client/src/containers/frontend/Following.js
> [B] Fix missing dispatch prop pass in Follow container

- client/src/components/backend/Ingestion/Form/Type.js
- client/src/components/backend/Ingestion/Form/Upload.js
- client/src/components/backend/Ingestion/Form/Wrapper.js
- client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Type-test.js.snap
- client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/containers/backend/ProjectDetail/Text/Ingestion/New.js
- client/src/containers/backend/ProjectDetail/Text/Ingestion/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/ProjectDetail/Text/Ingestion/__tests__/__snapshots__/New-test.js.snap
- client/src/containers/backend/TextDetail/Ingestion/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/TextDetail/Ingestion/__tests__/__snapshots__/New-test.js.snap
> [B] Correct ingestion cancel button behavior

- client/src/components/backend/Maker/ListItem.js
- client/src/components/backend/Maker/__tests__/__snapshots__/ListItem-test.js.snap
- client/src/components/backend/User/ListItem.js
- client/src/components/backend/User/__tests__/__snapshots__/ListItem-test.js.snap
- client/src/containers/backend/People/Makers/__tests__/__snapshots__/List-test.js.snap
- client/src/containers/backend/People/Users/__tests__/__snapshots__/List-test.js.snap
> [B] Remove checkboxes from backend user lists

- api/app/controllers/api/v1/comments_controller.rb
- client/src/components/frontend/Resource/__tests__/__snapshots__/Detail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/CollectionResourceDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ResourceDetail-test.js.snap
- client/src/containers/global/Comment/Editor.js
- client/src/containers/global/Comment/__tests__/Editor-test.js
- client/src/containers/global/Comment/__tests__/__snapshots__/Editor-test.js.snap
- client/src/test/helpers/auth.js
- client/src/theme/Components/browse/resource/_detail.scss
- client/src/theme/Components/reader/annotation/comment/_editor.scss
> [B] Fix resource comment not appearing on create

- client/src/components/frontend/ResourceList/Slide/Caption.js
- client/src/containers/frontend/CollectionDetail.js
- client/src/containers/frontend/__tests__/CollectionDetail-test.js
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/test/setup.js
> [B] Fix Velocity render error in ResourceListSlideCaption

- client/src/components/backend/Ingestion/Form/Type.js
- client/src/components/backend/Ingestion/Form/Upload.js
- client/src/components/backend/Ingestion/Form/__tests__/Type-test.js
- client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Type-test.js.snap
- client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Upload-test.js.snap
- client/src/components/backend/Ingestion/Form/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/containers/backend/ProjectDetail/Text/Ingestion/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/ProjectDetail/Text/Ingestion/__tests__/__snapshots__/New-test.js.snap
- client/src/containers/backend/TextDetail/Ingestion/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/TextDetail/Ingestion/__tests__/__snapshots__/New-test.js.snap
> [B] Hide cancel button on reingestion page

- client/src/components/frontend/ProjectList/Grid.js
- client/src/containers/frontend/Home.js
- client/src/theme/Components/browse/project-list/_grid-project.scss
> [B] Paginate projects on home

- api/app/services/ingestor/strategy/epub/inspector/text_section.rb
> [B] Fix EPUB ingestion failing with unnamed text section

- client/__mocks__/password-generator.js
- client/src/components/backend/Form/__tests__/GeneratedPasswordInput-test.js
- client/src/components/backend/Form/__tests__/__snapshots__/GeneratedPasswordInput-test.js.snap
- client/src/containers/backend/NewUser/__tests__/Wrapper-test.js
- client/src/containers/backend/NewUser/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/test/setup.js
> [C] Add tests for new user components

- client/package.json
- client/src/theme/STACSS/_appearance.scss
- client/webpack/base.config.js
- client/yarn.lock
> [B] Fix postcss webpack config

- client/src/theme/Components/browse/project/_hero.scss
> [B] Fix project hero buttons wrapping

- client/src/components/backend/Form/GeneratedPasswordInput.js
- client/src/components/backend/Form/__tests__/__snapshots__/GeneratedPasswordInput-test.js.snap
- client/src/containers/backend/NewUser/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/theme/Components/shared/forms/_shared.scss
> [B] Fix password toggle markup to prevent form submit

- client/src/components/reader/Section/Text.js
> [F] Scroll to various anchors in reader text

- client/src/components/reader/Section/Label.js
- client/src/components/reader/Section/__tests__/__snapshots__/Label-test.js.snap
- client/src/containers/reader/Section.js
- client/src/theme/Components/reader/_section-category-label.scss
- client/src/theme/_z-stack.scss
> [B] Fix footer category label position

- client/webpack/base.config.js
> [B] Extract styles to css file in prod build

- client/src/theme/Components/reader/_section-next-section.scss
- client/src/theme/Components/reader/_section-pagination.scss
> [B] Prevent padding on text section pagination when not showing

- api/db/schema.rb
- api/lib/dynamic_mailer/mailer.rb
- client/src/components/reader/Section/Label.js
- client/src/components/reader/Section/__tests__/Label-test.js
- client/src/containers/reader/Section.js
> [B] Refactor section label to use only text

- api/config/manifold.yml
- api/spec/services/validator/stylesheet_spec.rb
> [B] Strip normal font weights during ingestion

- api/app/controllers/api/v1/stylesheets_controller.rb
- api/spec/models/stylesheet_spec.rb
> [B] Return errors for stylesheets

- api/app/controllers/api/v1/users_controller.rb
> [B] Fix error on user sign up

- client/src/components/frontend/Layout/ButtonNavigation.js
> [B] Ensure nav button widths are always equal

- client/src/components/reader/Section/Label.js
- client/src/components/reader/Section/__tests__/__snapshots__/Label-test.js.snap
- client/src/theme/Components/reader/_section-category-label.scss
> [B] Hide fixed footer label on load

- client/src/theme/_z-stack.scss
> [B] Stack reader footer behind resource overlays

- client/src/components/reader/Section/NextSection.js
- client/src/components/reader/Section/__tests__/__snapshots__/NextSection-test.js.snap
> [B] Remove 'chapter' from reader next section footer

- client/src/components/backend/Project/ListItem.js
> [B] Fix project list image displaying wrong image

- api/app/controllers/concerns/validation.rb
> [B] Fix maker avatar not being removed

- client/__mocks__/password-generator.js
- client/package.json
- client/src/components/backend/Form/GeneratedPasswordInput.js
- client/src/helpers/passwordGenerator.js
- client/src/test/setup.js
- client/yarn.lock
This issue was coming from the password-generator library we were using.  We've removed the library and wrote our own password generator that does not require any other modules.
Fixes #487
> [B] Fix broken password generation on production

- client/src/components/frontend/Project/Thumbnail.js
> [B] Don't show updated badge for draft projects

- api/app/controllers/concerns/validation.rb
- client/src/components/frontend/Layout/Footer.js
- client/src/components/frontend/Layout/__tests__/Footer-tests.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/Footer-tests.js.snap
- client/src/containers/backend/Settings/General.js
- client/src/containers/backend/Settings/__tests__/General-test.js
- client/src/containers/backend/Settings/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
- client/src/test/fixtures/entity.js
> [B] Allow footer copyright to be set by installation

- client/src/theme/Components/reader/_return-menu.scss
> [B] Reduce reader return menu text on mobile

- api/app/serializers/resource_partial_serializer.rb
- api/app/serializers/resource_serializer.rb
- client/src/components/frontend/Project/__tests__/Resources-test.js
- client/src/components/frontend/Project/__tests__/__snapshots__/Resources-test.js.snap
- client/src/components/frontend/Resource/Card.js
- client/src/components/frontend/Resource/Detail.js
- client/src/components/frontend/Resource/Meta.js
- client/src/components/frontend/Resource/TagList.js
- client/src/components/frontend/Resource/__tests__/Card-test.js
- client/src/components/frontend/Resource/__tests__/Detail-test.js
- client/src/components/frontend/Resource/__tests__/Meta-test.js
- client/src/components/frontend/Resource/__tests__/__snapshots__/Card-test.js.snap
- client/src/components/frontend/Resource/__tests__/__snapshots__/Detail-test.js.snap
- client/src/components/frontend/Resource/__tests__/__snapshots__/Meta-test.js.snap
- client/src/components/frontend/Resource/index.js
- client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/components/frontend/ResourceList/__tests__/Cards-test.js
- client/src/components/frontend/ResourceList/__tests__/__snapshots__/Cards-test.js.snap
- client/src/containers/frontend/__tests__/CollectionDetail-test.js
- client/src/containers/frontend/__tests__/CollectionResourceDetail-test.js
- client/src/containers/frontend/__tests__/ProjectResources-test.js
- client/src/containers/frontend/__tests__/ResourceDetail-test.js
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/CollectionResourceDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ProjectResources-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ResourceDetail-test.js.snap
- client/src/theme/Components/browse/resource/_card.scss
- client/src/theme/Components/browse/resource/_index.scss
- client/src/theme/Components/browse/resource/_meta.scss
- client/src/theme/Components/browse/resource/_tag-list.scss
> [F] Refactor resource tag list into component

- client/src/components/reader/Header.js
- client/src/components/reader/__tests__/__snapshots__/Header-test.js.snap
- client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/theme/Components/reader/_header-reader.scss
> [F] Update header to match new comps

- client/src/components/reader/Notation/Collection/PickerListItem.js
- client/src/components/reader/Notation/Collection/__tests__/__snapshots__/PickerListItem-test.js.snap
- client/src/components/reader/Notation/Resource/PickerListItem.js
- client/src/components/reader/Notation/Resource/__tests__/__snapshots__/PickerListItem-test.js.snap
- client/src/containers/reader/Notation/__tests__/__snapshots__/Picker-test.js.snap
- client/src/theme/Components/backend/_vertical-list.scss
> [B] Truncate long resourceish names in drawer

- client/src/theme/Components/backend/project/_header.scss
Fixes #555 
Just a little CSS add! Please test.
> [B] Add hover states to entity header utility

- client/src/theme/Components/browse/text/_asset-thumb.scss
> Fix text icon alignment on asset status

- client/src/theme/Components/backend/_vertical-list.scss
Not sure what caused this initially, but this mini fix seems to do the trick. I've checked it anywhere I think Vertical Lists might appear, but please QA and merge when ready!
> [B] Fix list width regression

- client/src/components/frontend/Project/Detail.js
- client/src/components/frontend/Project/index.js
- client/src/components/global/MetaList.js
- client/src/components/global/Overlay.js
- client/src/components/global/__tests__/MetaList-test.js
- client/src/components/global/__tests__/__snapshots__/MetaList-test.js.snap
- client/src/components/global/index.js
- client/src/components/reader/TextMeta.js
- client/src/components/reader/Toc.js
- client/src/components/reader/__tests__/__snapshots__/Header-test.js.snap
- client/src/components/reader/__tests__/__snapshots__/Toc-test.js.snap
- client/src/components/reader/__tests__/__snapshots__/TocDrawer-test.js.snap
- client/src/components/reader/index.js
- client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/theme/Components/reader/_index.scss
- client/src/theme/Components/reader/_section-category-label.scss
- client/src/theme/Components/reader/_text-meta.scss
- client/src/theme/Components/reader/_toc-drawer.scss
- client/src/theme/Components/shared/_key-value-list.scss
- client/src/theme/_z-stack.scss
Closes #601
Refactor meta list to global component.
Update column styles and alphabetize meta section.
> [F] Add text meta overlay

- client/src/components/reader/Notation/Viewer/Group.js
- client/src/components/reader/Notation/Viewer/__tests__/__snapshots__/Group-test.js.snap
> [B] Obey formatting on notation group titles

- .env.sample
- api/app/mailers/application_mailer.rb
- api/app/models/concerns/attachments.rb
- api/config/application.rb
- api/config/initializers/20_configuration.rb
- api/lib/middleware/omniauth_stack.rb
- api/spec/requests/users_spec.rb
- bin/manifold
- client/src/api/client.js
- client/src/components/backend/Ingestion/ConnectionError.js
- client/src/config.js
- client/src/store/middleware/websocketMiddleware.js
- client/src/utils/oauth/index.js
- client/webpack/build-client.config.js
- client/webpack/servers/dev.js
- client/webpack/templates/node_env.ejs
- client/webpack/templates/www_env.ejs
Additionally, refactor env variables around URLs and domain.
Fixes #631
> [F] Manifold supports SSL

- client/src/theme/Components/backend/forms/_has-many-list.scss
- client/src/theme/Components/backend/forms/_input-predictive.scss
- client/src/theme/Components/shared/_buttons.scss
- client/src/theme/Components/shared/forms/_form-inputs-custom.scss
- client/src/theme/Components/shared/forms/_form-inputs-primary.scss
- client/src/theme/Components/shared/forms/_form-inputs-secondary.scss
- client/src/theme/STACSS/_structure.scss
- client/src/theme/STACSS/_typography.scss
> [F] Adjust form styles for mobile

- api/config/manifold.yml
> [C] Prevent letter spacing CSS in ingestion

- client/src/theme/Components/shared/forms/_form-inputs-primary.scss
- client/src/theme/STACSS/_appearance.scss
> [B] Remove iOS styles from login overlay

- client/src/theme/Components/backend/_panel.scss
> [B] Add spacing to right of backend scrolling menu

- client/src/containers/backend/ProjectDetail/Texts.js
- client/src/containers/backend/ProjectDetail/__tests__/__snapshots__/Texts-test.js.snap
- client/src/theme/Components/backend/text/_list.scss
- client/src/theme/Components/shared/_buttons.scss
Note that this PR is blocked as its dependent on new button styles in #619. Once that PR is accepted, this one can be QA'd (by Naomi), rebased, and then released for review.
> Update text list button/table styles for mobile

- client/src/theme/Components/backend/_drawer.scss
- client/src/theme/STACSS/_typography.scss
Closes #595 
NB: This is blocked by #619 as it interacts with those new styles.
Once that PR has been accepted, this one can be QA'd by Naomi and changed to "needs review."
> [B] Tighten spacing on mobile person drawer header

- api/app/services/factory/event.rb
- api/config/locales/services/ingestor/en.yml
- api/spec/services/factory/event_spec.rb
> [B] Use installation name in project created event

- api/app/models/resource.rb
- api/spec/models/resource_spec.rb
> [B] Resources should destroy associated added event

- api/app/models/collection.rb
- api/spec/models/collection_spec.rb
> [B] Add title validation to collections

- client/src/components/frontend/Project/Detail.js
> [B] Rename project detail metadata section label

- client/src/containers/Manifold.js
- client/src/containers/backend/Backend.js
- client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/containers/frontend/Frontend.js
> [B] Prevent scroll to top on reader route change

- client/src/components/reader/ReturnMenu/Body.js
- client/src/components/reader/ReturnMenu/__tests__/__snapshots__/Body-test.js.snap
- client/src/components/reader/__tests__/__snapshots__/Header-test.js.snap
- client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/theme/Components/reader/_return-menu.scss
- client/src/theme/STACSS/_typography.scss
> [B] Highlight "learn more..." in reader menu

- api/app/controllers/concerns/validation.rb
- api/app/serializers/text_partial_serializer.rb
- api/db/migrate/20171120190035_add_section_kind_to_texts.rb
- api/db/schema.rb
- client/src/components/reader/Section/NextSection.js
- client/src/components/reader/Section/Pagination.js
- client/src/components/reader/Section/__tests__/Pagination-test.js
- client/src/components/reader/Section/__tests__/__snapshots__/NextSection-test.js.snap
- client/src/components/reader/Section/__tests__/__snapshots__/Pagination-test.js.snap
- client/src/containers/backend/TextDetail/General.js
- client/src/containers/backend/TextDetail/__tests__/__snapshots__/General-test.js.snap
> [F] Allow text section type to be changed

- bin/manifold
Updates the references to rake tasks in the manifold CLI that have changed
Note: I updated and tested these to the best of my knowledge but I don't have the most familiarity with this project so please take a look and confirm that these are the correlating analogues
> [C] Update manifold CLI rake task references

- api/Gemfile
- api/Gemfile.lock
- api/app/models/user.rb
> [B] User validation fixes

- api/config/manifold.yml
- client/src/components/global/SignInUp/UpdateForm.js
> [B] Fix attachment extension validation

- api/app/controllers/api/v1/users_controller.rb
> [B] Don't send welcome email if user validation fails

- api/app/services/validator/stylesheet.rb
- api/spec/services/validator/stylesheet_spec.rb
> [C] Adjust base font-size used in stylesheet validator

- client/src/store/middleware/currentUserMiddleware.js
Logged out notification is still in place, let me know if we want that removed as well.
Closes #676.
> [C] Remove login notification

- api/app/services/ingestor/strategy/abstract_builder.rb
- client/src/components/reader/Annotation/Popup/Share.js
> [B] Fixes Twitter share text; Fix incorrect Text slugs

- api/app/models/upgrade_result.rb
- api/app/services/system_upgrades/abstract_version.rb
- api/app/services/system_upgrades/has_logger.rb
- api/app/services/system_upgrades/perform.rb
- api/app/services/system_upgrades/upgrades/manifold000400.rb
- api/config/initializers/00_libraries.rb
- api/db/migrate/20180102232442_create_upgrade_results.rb
- api/db/schema.rb
- api/lib/tasks/upgrade.rake
- api/spec/rails_helper.rb
- api/spec/services/system_upgrades/abstract_version_spec.rb
- api/spec/services/system_upgrades/perform_spec.rb
> [F] Add task and service to upgrade a Manifold installation

- api/app/models/resource.rb
- api/app/services/importer/drive_resources.rb
- api/app/services/importer/helpers/logger.rb
> [B] Fix drive resource importing

- api/app/services/ingestor/strategy/google_doc/strategy.rb
> [B] Fail with error if google doc is unavailable

- client/src/components/backend/Form/FieldGroup.js
- client/src/components/backend/Form/Instructions.js
- client/src/components/backend/Form/MaskedTextInput.js
- client/src/components/backend/Form/TextArea.js
- client/src/components/backend/Form/TextInput.js
- client/src/components/backend/Form/Upload.js
- client/src/components/backend/Form/__tests__/__snapshots__/MaskedTestInput-test.js.snap
- client/src/components/backend/Form/index.js
- client/src/containers/backend/Project/ProjectPage.js
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
- client/src/containers/backend/Settings/__tests__/__snapshots__/Integrations-test.js.snap
- client/src/containers/backend/Stylesheet/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/Text/__tests__/__snapshots__/Metadata-test.js.snap
Note this PR includes https://github.com/ManifoldScholar/manifold/commit/21c217ef5674affedd3e6299ad797fa50ed08d16, which is a part of #694.
Closes #713
> [C] Add image size guide to project hero image input

- client/src/components/backend/TwitterQuery/__tests__/Form-test.js
- client/src/containers/backend/People/Users/New.js
- client/src/containers/backend/People/Users/__tests__/__snapshots__/New-test.js.snap
- client/src/routes.js
> [C] Render new user route in drawer

- api/app/models/concerns/has_formatted_attributes.rb
- api/app/models/concerns/metadata.rb
- api/app/models/event.rb
- api/app/models/resource.rb
- api/app/serializers/resource_partial_serializer.rb
- api/app/services/formatted_attributes/definition.rb
- api/app/services/formatted_attributes/methods.rb
- api/spec/services/formatted_attributes/methods_spec.rb
> [F] Allow metadata values to be formatted with markdown

- client/src/components/frontend/Resource/Preview/Video.js
- client/src/theme/Components/browse/resource/_preview.scss
> [B] Fix sizing of external videos in preview overlay

- CODE_OF_CONDUCT.md
> [C] Add Code of Conduct to Manifold

- api/app/models/concerns/citable.rb
- api/app/models/project.rb
- api/app/models/text.rb
- api/spec/models/project_spec.rb
- api/spec/models/shared_examples/citable.rb
- api/spec/models/text_section_spec.rb
- api/spec/models/text_spec.rb
- api/spec/rails_helper.rb
> [F] Citable updates dependent citations after save

- api/app/models/event.rb
- api/app/models/text.rb
- api/db/migrate/20180202210107_add_text_index_to_text_sections.rb
- api/db/migrate/20180202211536_remove_subject_slug_from_events.rb
- api/db/schema.rb
- client/src/components/frontend/Event/Tile.js
- client/src/components/frontend/Event/__tests__/List-test.js
- client/src/components/frontend/Event/__tests__/__snapshots__/List-test.js.snap
- client/src/components/frontend/Project/__tests__/__snapshots__/Detail-test.js.snap
- client/src/components/frontend/Project/__tests__/__snapshots__/Events-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/EventList-test.js.snap
> [B] Correct URLs in event prompts

- api/app/models/concerns/metadata.rb
- client/src/theme/Components/global/_key-value-list.scss
> [C] Allow links in metadata markdown

- client/src/components/reader/Section/BodyNodes/HigherOrder/ValidatedNode.js
> [B] Handle reader scroll to React component

- api/app/services/ingestor/strategy/epub/inspector/epub.rb
- api/app/services/ingestor/strategy/epub/inspector/toc.rb
- api/spec/data/ingestion/epubs/minimal-v3/EPUB/nav.xhtml
- api/spec/data/ingestion/epubs/minimal-v3/EPUB/package.opf
- api/spec/data/ingestion/epubs/minimal-v3/EPUB/xhtml/an item with spaces.xhtml
> [B] Correct handling of encoded URIs in EPUBs

- api/app/services/validator/html.rb
- api/spec/data/ingestion/fragments/ascii_section.html
- api/spec/services/ingestor/transformer/text_section.rb
- api/spec/services/validator/html_spec.rb
> [B] Coerce ASCII epub body to UTF-8 during transform

- api/app/controllers/api/v1/me/relationships/favorites_controller.rb
Fixes #801
Signed-off-by: Zach Davis <zach@castironcoding.com>
> [C] Correct me/relationships/favorites serializer

- client/src/containers/reader/Annotation/Annotatable.js
Resolves #635. Most issues in #635 were addressed in 2f1e64.
> [B] Remove source breaks from annotation subject

- api/.rspec
- api/app/lib/search/filter_scope.rb
- api/app/models/concerns/filterable.rb
- api/spec/models/event_spec.rb
- api/spec/models/project_spec.rb
- api/spec/models/user_spec.rb
- api/spec/rails_helper.rb
> [C] Refactor Filterable and FilterScope

- client/src/containers/backend/Ingestion/Ingest.js
- client/src/containers/backend/Ingestion/__tests__/__snapshots__/Ingest-test.js.snap
- client/src/theme/Components/backend/ingestion/_ingest.scss
- client/src/theme/Components/backend/project/_header.scss
> [B] Adjust ingestion reset button text/position

- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
> [B] Fix link color in form instructions

- client/src/components/global/MetaList.js
- client/src/components/global/__tests__/__snapshots__/MetaList-test.js.snap
- client/src/theme/Components/global/_key-value-list.scss
> [F] Hoist longer metadata above columnar list

- client/src/components/reader/Header.js
- client/src/components/reader/Section/NextSection.js
- client/src/components/reader/Section/__tests__/__snapshots__/NextSection-test.js.snap
- client/src/containers/reader/Section.js
- client/src/theme/Components/reader/_header-reader.scss
- client/src/theme/Components/reader/_section-next-section.scss
- client/src/theme/_variables.scss
> [B] Fix inconsistencies in reader dark mode

- client/src/theme/Components/reader/_text-section.scss
Closes #837
Prevents overlap caused by annotation underlines and highlights
> [B] Increase text header line height

- client/src/containers/backend/ResourceImport/Results.js
- client/src/theme/Components/backend/forms/_results-list.scss
Closes #843
Also update secondary label placement for smaller screens
> [B] Update results list styles/padding

- api/app/controllers/api/v1/projects_controller.rb
- client/src/containers/frontend/Home.js
> [B] Fix API project ordering

- client/src/containers/backend/People/Makers/Edit.js
- client/src/containers/backend/Project/Collaborators.js
- client/src/containers/backend/Project/__tests__/Collaborators-test.js
- client/src/containers/backend/Text/Collaborators.js
- client/src/containers/backend/Text/__tests__/Collaborators-test.js
> [B] Fix maker drawer redirect after destroy

- client/src/components/backend/Navigation/Secondary.js
- client/src/containers/backend/Collection/Wrapper.js
- client/src/containers/backend/Content/Pages/Detail.js
- client/src/containers/backend/Content/Wrapper.js
- client/src/containers/backend/People/Wrapper.js
- client/src/containers/backend/People/__tests__/Wrapper-test.js
- client/src/containers/backend/Settings/Wrapper.js
- client/src/containers/backend/Settings/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/containers/backend/Text/Wrapper.js
- client/src/containers/backend/Text/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/routes.js
> [B] Fix backend nav link active states and routing

- api/app/models/twitter_query.rb
- api/app/services/tweet/fetcher.rb
> [B] Fix tweet fetcher pull inactive tweets

- api/app/models/annotation.rb
- api/app/models/category.rb
- api/app/models/comment.rb
- api/app/models/resource.rb
- api/app/models/subject.rb
- api/app/models/text_section.rb
> [B] Add missing dependent destroy behavior

- api/config/routes.rb
> [B] Fix permission routing concern

- api/app/models/concerns/metadata.rb
- client/src/config.js
> [B] Fix metadata keyword display formatting

- client/src/components/backend/Form/Upload.js
- client/src/components/backend/Form/__tests__/__snapshots__/Upload-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Document-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Image-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Presentation-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Spreadsheet-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Variants-test.js.snap
- client/src/components/backend/Resource/Form/__tests__/__snapshots__/KindAttributes-test.js.snap
- client/src/containers/backend/Collection/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Collection/__tests__/__snapshots__/New-test.js.snap
- client/src/containers/backend/People/Makers/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
- client/src/containers/backend/Resource/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Resource/__tests__/__snapshots__/New-test.js.snap
- client/src/containers/backend/Resource/__tests__/__snapshots__/Variants-test.js.snap
- client/src/containers/backend/Settings/__tests__/__snapshots__/Integrations-test.js.snap
- client/src/containers/backend/Settings/__tests__/__snapshots__/Theme-test.js.snap
> [B] Correct upload input image format label

- client/src/components/reader/Annotation/Popup/Secondary/Share.js
- client/src/containers/reader/Annotation/Annotatable.js
> [F] Include text node with tweet

- client/src/components/frontend/Layout/Footer.js
- client/src/components/frontend/Layout/__tests__/Footer-tests.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/Footer-tests.js.snap
- client/src/components/global/Search/Query/Form.js
- client/src/components/reader/Footer.js
- client/src/components/reader/__tests__/__snapshots__/Footer-test.js.snap
- client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/containers/frontend/Search.js
- client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
- client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/theme/Components/browse/layout/_footer-browse.scss
- client/src/theme/Components/reader/_footer-reader.scss
> [F] Add search and built by link to footer

- api/app/authorizers/annotation_authorizer.rb
- api/app/serializers/annotation_serializer.rb
- api/app/serializers/application_serializer.rb
- client/src/components/reader/Annotation/Meta.js
- client/src/components/reader/Annotation/Popup/Menu/Annotate.js
- client/src/components/reader/Section/BodyNodes/TextNode.js
- client/src/components/reader/Section/Text.js
- client/src/theme/Components/reader/_annotation-popup.scss
> [B] Fix highlight/annotation creator checks

- api/app/jobs/fetch_project_tweets.rb
> [C] Rescue from BadRequest error during tweet fetch

- client/src/api/notifications.js
- client/src/containers/backend/People/Makers/Edit.js
- client/src/containers/backend/People/Makers/Form.js
- client/src/containers/backend/People/Makers/List.js
- client/src/containers/backend/People/Makers/New.js
- client/src/containers/backend/People/Makers/__tests__/New-test.js
- client/src/containers/backend/People/Makers/__tests__/__snapshots__/New-test.js.snap
- client/src/containers/backend/People/Makers/index.js
- client/src/routes.js
> [F] Implement new maker interface

- client/src/components/global/SignInUp/Overlay.js
- client/src/components/global/SignInUp/__tests__/__snapshots__/Overlay-test.js.snap
- client/src/theme/Components/global/_overlay-full-primary.scss
> [B] Scroll overlay primary behind header

- client/src/containers/backend/Text/General.js
- client/src/containers/backend/Text/__tests__/__snapshots__/General-test.js.snap
> [C] Remove inaccurate field instructions

- api/app/models/concerns/has_sort_title.rb
- api/app/models/project.rb
- api/app/models/resource.rb
- api/db/migrate/20180329220543_add_sort_title_to_resources.rb
- api/db/schema.rb
- api/spec/models/resource_spec.rb
- client/src/components/frontend/Project/__tests__/__snapshots__/Resources-test.js.snap
- client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/components/frontend/ResourceList/Filters.js
- client/src/components/frontend/ResourceList/__tests__/__snapshots__/Filters-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ProjectResources-test.js.snap
> [B] Add sort title to resources and fix ordering

- client/src/components/reader/Annotation/Popup/Secondary/Share.js
> [B] Handle empty selection share messages

- client/src/components/reader/Section/BodyNodes/LinkNode.js
> [B] Fix broken external links in reader

- api/app/models/collection.rb
- api/app/models/resource.rb
- api/app/serializers/collection_serializer.rb
- api/app/services/formatted_attributes/definition.rb
- client/src/components/frontend/ResourceCollection/Detail.js
- client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/theme/Components/browse/_splash.scss
- client/src/theme/Components/browse/collection/_detail.scss
- client/src/theme/Components/browse/project/_hero.scss
- client/src/theme/Components/browse/resource/_detail.scss
> [F] Allow links in formatted fields

- api/app/lib/updaters.rb
- api/app/lib/updaters/concerns/has_sortable_collaborators.rb
- api/app/lib/updaters/project.rb
- api/app/lib/updaters/text.rb
> [B] Fix text collaborator sorting in updater

- client/src/theme/Components/global/forms/_list-filter.scss
> [C] Refactor list filter mobile styles

- client/package.json
- client/src/components/backend/Form/CodeArea.js
- client/src/components/frontend/Event/Event.js
- client/src/components/frontend/ResourceList/Slide/Caption.js
- client/src/components/reader/Notes/Partial/Group.js
- client/yarn.lock
> [B] Fix setState errors on code-splitting components

- api/app/models/user.rb
- api/db/migrate/20180406215931_add_reader_role_to_roleless_users.rb
- api/db/schema.rb
- api/spec/factories/user.rb
> [B] Fix reader role not being assigned when role is not specified

- api/app/models/resource_import.rb
> [B] Remove unused resource attributes from import

- api/config/manifold.yml
> [B] Allow application/zip mime type for ppt

- client/src/containers/backend/Settings/Subjects/List.js
- client/src/containers/backend/Settings/Subjects/New.js
- client/src/containers/backend/Settings/Subjects/__tests__/__snapshots__/New-test.js.snap
- client/src/routes.js
> [B] Fix missing backend settings subject create

- api/app/models/concerns/filterable.rb
> [B] Fix filtering when using keyword on empty collection

- client/src/containers/frontend/Frontend.js
- client/src/server-client.js
> Correct server-client redirect response

- client/src/theme/Components/global/forms/_form-inputs-primary.scss
Closes #953
Also truncate overlong column titles in mapping UI
> [B] Fix resource mapping button styles/padding

- client/src/components/backend/Form/MaskedTextInput.js
- client/src/components/backend/Metadata/Form.js
- client/src/components/frontend/ResourceCollection/__tests__/Detail-test.js
- client/src/components/global/Meta/DOI.js
- client/src/components/global/Meta/__tests__/DOI-test.js
- client/src/components/global/Meta/__tests__/Item-test.js
- client/src/components/global/Meta/__tests__/List-test.js
- client/src/components/reader/Notation/Collection/__tests__/Detail-test.js
- client/src/components/reader/__tests__/Footer-test.js
- client/src/config.js
- client/src/containers/backend/Project/__tests__/__snapshots__/Permissions-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
- client/src/containers/backend/Settings/__tests__/__snapshots__/Integrations-test.js.snap
- client/src/containers/frontend/__tests__/CollectionDetail-test.js
- client/src/test/fixtures/entity.js
> [C] Add text mask to DOI input fields

- client/src/theme/Components/backend/_vertical-list.scss
> [B] Fix name wrap in vertical list meta

- client/src/components/frontend/Resource/Player/Video.js
> [B] Fix video resource preview throwing exception

- api/app/models/project.rb
- api/app/models/role.rb
- api/app/models/user.rb
- api/app/models/users_roles.rb
> [B] Fix issue with roles preventing project destroy

- api/app/controllers/concerns/validation.rb
- api/app/serializers/project_serializer.rb
- client/src/containers/backend/Project/General.js
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
> [F] Expose project slug in backend

- api/app/services/ingestor/strategy/google_doc/strategy.rb
> [C] Add error message when ingesting docs without config

- api/app/models/concerns/attachments.rb
- api/app/models/concerns/resource_attachment_validation.rb
- api/config/manifold.yml
- client/src/components/backend/Form/Upload.js
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Document-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Presentation-test.js.snap
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Spreadsheet-test.js.snap
Also changes resource attachment type names to be generic, rather than
MS Office types
> [C] Add mimetypes and extensions for OpenOffice files

- api/app/controllers/concerns/validation.rb
- api/app/models/concerns/fingerprinted.rb
- api/app/models/resource.rb
- api/app/models/resource_import_row.rb
- api/spec/models/resource_spec.rb
- client/src/containers/backend/Resource/General.js
- client/src/containers/backend/Resource/__tests__/__snapshots__/General-test.js.snap
> [C] Expose slug and fingerprint in backend

- api/app/controllers/concerns/validation.rb
- api/app/models/collection.rb
- api/app/models/maker.rb
- client/src/components/backend/List/Searchable.js
- client/src/components/backend/List/__tests__/__snapshots__/Searchable-test.js.snap
- client/src/components/frontend/Project/__tests__/__snapshots__/Resources-test.js.snap
- client/src/components/frontend/ResourceCollection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/components/frontend/ResourceList/Filters.js
- client/src/components/frontend/ResourceList/__tests__/__snapshots__/Filters-test.js.snap
- client/src/containers/backend/Collection/__tests__/__snapshots__/Resources-test.js.snap
- client/src/containers/backend/Dashboards/__tests__/__snapshots__/Admin-test.js.snap
- client/src/containers/backend/Dashboards/__tests__/__snapshots__/Author-test.js.snap
- client/src/containers/backend/People/Makers/List.js
- client/src/containers/backend/People/Makers/__tests__/__snapshots__/List-test.js.snap
- client/src/containers/backend/People/Users/List.js
- client/src/containers/backend/People/Users/__tests__/__snapshots__/List-test.js.snap
- client/src/containers/backend/Project/Resource/CollectionsList.js
- client/src/containers/backend/Project/Resource/ResourcesList.js
- client/src/containers/backend/Project/Resource/__tests__/__snapshots__/CollectionsList-test.js.snap
- client/src/containers/backend/Project/Resource/__tests__/__snapshots__/ResourcesList-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/Collections-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/Events-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/Resources-test.js.snap
- client/src/containers/backend/Settings/Subjects/__tests__/__snapshots__/List-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/CollectionDetail-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/ProjectResources-test.js.snap
- client/src/containers/reader/Notation/__tests__/__snapshots__/Picker-test.js.snap
- client/src/theme/Components/backend/forms/_search-filter.scss
- client/src/theme/Components/global/forms/_list-filter.scss
- client/src/theme/assets/svg/fonts/manicon/caret-up.svg
> [F] Implement list ordering

- api/app/models/user.rb
- api/db/migrate/20180510161730_change_users_email_to_citext.rb
- api/db/schema.rb
- api/spec/models/user_spec.rb
> [B] Store emails in case-insensitive column

- client/.eslintrc
- client/package.json
- client/yarn.lock
Includes the linter as well as currently applicable rules
> [F] Add jsx linter to address WCAG concerns

- client/.eslintrc
- client/src/components/backend/Form/HasMany.js
- client/src/components/backend/Form/Upload.js
- client/src/components/backend/Form/__tests__/__snapshots__/Upload-test.js.snap
- client/src/components/backend/Project/Form/AvatarBuilder.js
- client/src/components/backend/Project/Form/ColorPicker.js
- client/src/components/backend/Project/ListItem.js
- client/src/components/frontend/Layout/NoFollow.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/NoFollow-test.js.snap
- client/src/components/frontend/Maker/Avatar.js
- client/src/components/frontend/Project/Hero.js
- client/src/components/frontend/ProjectList/__tests__/__snapshots__/Following-test.js.snap
- client/src/components/global/PressLogo.js
- client/src/components/global/__tests__/__snapshots__/PressLogo-test.js.snap
- client/src/components/reader/StaticTextSample.js
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
Resolves #1059
Includes updated Client Tests
> [F] Add descriptive alt text to all image tags and elements with background images

- api/app/controllers/concerns/validation.rb
- client/src/containers/backend/Project/General.js
- client/src/containers/backend/Project/Wrapper.js
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/theme/Components/backend/_panel.scss
> [C] Expose social fields in project backend

- client/src/containers/backend/Content/Features/Detail.js
- client/src/containers/backend/Content/Pages/Detail.js
> [B] Fix authorization check on Page/Feature

- client/src/theme/Components/browse/collection/_resource-slideshow.scss
Resolves #1080 
Includes minor fixes to the css properties ordering to reflect current style-lint rules
> [B] Style links in resource slide captions

- api/.gitignore
- api/app/services/external_auth/provisioners/abstract.rb
- api/app/services/external_auth/provisioners/user.rb
- api/app/services/external_auth/upsert_user.rb
- api/config/oauth_sample.yml
- api/lib/manifold_env.rb
- api/lib/manifold_env/custom_oauth_endpoint.rb
- api/lib/manifold_env/custom_oauth_provider.rb
- api/lib/manifold_env/oauth_config.rb
- api/lib/manifold_env/oauth_provider.rb
- api/lib/middleware/omniauth_stack.rb
- client/src/components/global/SignInUp/Login.js
> [F] Implement Custom OAuth 2.0 Strategies

- client/src/components/frontend/Resource/Player/Audio.js
- client/src/components/global/SignInUp/Create.js
- client/src/components/global/SignInUp/Login.js
- client/src/components/global/SignInUp/UpdateForm.js
- client/src/components/global/SignInUp/__tests__/__snapshots__/Create-test.js.snap
- client/src/components/global/SignInUp/__tests__/__snapshots__/CreateUpdate-test.js.snap
- client/src/components/global/SignInUp/__tests__/__snapshots__/Login-test.js.snap
- client/src/components/global/SignInUp/__tests__/__snapshots__/Overlay-test.js.snap
- client/src/components/global/SignInUp/__tests__/__snapshots__/Update-test.js.snap
- client/src/components/global/SignInUp/__tests__/__snapshots__/UpdateForm-test.js.snap
- client/src/containers/frontend/PasswordReset.js
- client/src/containers/frontend/__tests__/__snapshots__/PasswordReset-test.js.snap
> All range and password inputs have labels or other descriptive text

- client/.eslintrc
- client/package.json
- client/src/actions/helpers/commonActions.js
- client/src/components/global/Overlay.js
- client/src/components/global/SignInUp/Overlay.js
- client/src/components/global/SignInUp/__tests__/__snapshots__/Overlay-test.js.snap
- client/src/components/global/__tests__/__snapshots__/Overlay-test.js.snap
- client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/containers/reader/Notation/Resource/__tests__/__snapshots__/Detail-test.js.snap
- client/src/test/setup.js
- client/yarn.lock
> Redirect Focus when Overlays open/close

- client/src/components/backend/Form/Upload.js
- client/src/components/backend/Resource/Form/Kind/__tests__/__snapshots__/Video-test.js.snap
> [B] Fix .flv files not being selectable in upload

- client/src/theme/Components/reader/_text-section.scss
> [B] Add default paragraph margins in reader

- client/src/components/frontend/Resource/Player/Audio.js
- client/src/theme/Components/browse/resource/_audio-player.scss
- client/src/theme/assets/svg/fonts/manicon/octagon-bang.svg
> [B] Add error state to audio player

- client/src/components/frontend/Resource/Player/Audio.js
> [B] Stop audio playback when reader overlay closes

- client/src/containers/backend/Project/ProjectPage.js
- client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
> [B] Remove duplicate social fields from project backend

- client/src/containers/global/Comment/Editor.js
> [B] Close comment editor after successful post

- client/src/components/global/Utility/EntityCount.js
> [B] Fix incorrect entity count when 0 exist

- api/app/models/resource.rb
- client/src/components/backend/Form/TextInput.js
> [B] Fix error on TextInput component with numbers

- client/src/containers/reader/Notation/Collection/Detail.js
- client/src/containers/reader/Notation/Collection/__tests__/__snapshots__/Detail-test.js.snap
- client/src/containers/reader/Notation/Resource/Detail.js
- client/src/containers/reader/Notation/Resource/__tests__/__snapshots__/Detail-test.js.snap
> [B] Fix reader overlay close routes

- api/app/controllers/concerns/validation.rb
- api/app/models/project.rb
- api/db/migrate/20180710155830_rename_settings_default_place_of_publication.rb
- api/db/schema.rb
- api/spec/models/project_spec.rb
- client/src/containers/backend/Project/General.js
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Settings/General.js
> [B] Implement default publisher/place behavior

- client/src/components/frontend/Resource/Player/Audio.js
- client/src/theme/Components/browse/resource/_audio-player.scss
Resolves #1180
Includes updated styles for the progress bar and controls for the audio player.
Includes update to not load the wavform if the Web Audio API is not supported by the browser.
> [B] Update audio player styles for ie11

- api/app/services/ingestions/strategies/document.rb
- api/app/services/ingestions/strategy/document/ingestion_source.rb
- api/app/services/ingestions/strategy/document/inspector.rb
- api/spec/services/ingestions/compiler_spec.rb
- api/spec/services/ingestions/ingestor_spec.rb
- api/spec/services/ingestions/strategies/document_spec.rb
> [B] Fix document ingestion text section/source identifiers

- client/src/theme/Components/backend/_dialog.scss
> [B] Fixes the layout of the dialog overlays in ie11

- client/src/actions/helpers/commonActions.js
- client/src/components/backend/Layout/Header.js
- client/src/components/backend/Layout/__tests__/__snapshots__/Header-test.js.snap
- client/src/components/frontend/Layout/Header.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/Header-test.js.snap
- client/src/components/global/UIPanel.js
- client/src/components/global/__tests__/__snapshots__/UIPanel-test.js.snap
- client/src/components/reader/Header.js
- client/src/components/reader/__tests__/__snapshots__/Header-test.js.snap
- client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
- client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/theme/Components/global/_user-menu.scss
> [F] Redirect focus when UIPanels open/close

- client/src/components/frontend/Resource/Player/Audio.js
- client/src/theme/Components/browse/resource/_audio-player.scss
> [C] Make audio player error message clearer

- api/app/serializers/text_partial_serializer.rb
> [B] Always show total annotation count on text thumbnail

- client/src/components/backend/Form/__tests__/__snapshots__/HasMany-test.js.snap
- client/src/components/backend/Project/Form/__tests__/__snapshots__/Subjects-test.js.snap
- client/src/containers/backend/Form/PredictiveInput.js
- client/src/containers/backend/Form/__tests__/__snapshots__/Collaborators-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/Collaborators-test.js.snap
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/backend/Text/__tests__/__snapshots__/Collaborators-test.js.snap
> [B] Fix nested form button submitting on 'enter' press

- api/spec/data/ingestion/manifest/section_1.html
- api/spec/data/ingestion/manifest/section_1_1.html
- api/spec/data/ingestion/manifest/section_1_1a.md
> [B] Remove meta tags from manifest spec fixture files

- api/app/models/concerns/attachments.rb
> [B] Add attachment validation by type

- client/src/components/backend/Dialog/Wrapper.js
- client/src/components/backend/Dialog/__tests__/__snapshots__/Confirm-test.js.snap
- client/src/components/backend/Dialog/__tests__/__snapshots__/ResetPassword-test.js.snap
- client/src/components/backend/Dialog/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/components/frontend/Static/Form.js
- client/src/components/frontend/Static/__tests__/__snapshots__/Form-test.js.snap
- client/src/containers/global/Comment/Editor.js
- client/src/containers/global/Comment/__tests__/__snapshots__/Editor-test.js.snap
- client/src/theme/Components/browse/resource/_detail.scss
- client/src/theme/Components/global/_buttons.scss
- client/src/theme/Components/global/forms/_form-inputs-primary.scss
- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
- client/src/theme/Components/reader/annotation/comment/_editor.scss
- client/yarn.lock
> Redirect Focus when Dialog boxes open/close

- api/app/controllers/concerns/validation.rb
- api/app/services/ingestions/compilers/text.rb
- api/db/migrate/20180731223301_add_reingestion_to_ingestions.rb
- api/db/schema.rb
- client/src/components/backend/Ingestion/Form/Wrapper.js
> [B] Create new text on every new ingestion

- client/src/components/frontend/ProjectList/Grid.js
> [B] Fix ProjectList.Grid throwing error when prevProps.projects is null

- client/src/theme/Components/backend/_panel.scss
- client/src/theme/Components/global/_buttons.scss
- client/src/theme/Components/global/_header-app.scss
- client/src/theme/Components/global/forms/_shared.scss
Contributes to #1257  
Includes updated "subtle" focus styles for buttons.
Includes updated dotted-outline focus styles for navigational links.
Includes updated hover styles for buttons (conditional on background color of parent element).
Updated hover and focus styles for some types of "dull" buttons against dark background colors.
> [F] Improve button focus and hover state styles

- client/src/containers/backend/Collection/Wrapper.js
- client/src/containers/backend/Content/Pages/Detail.js
- client/src/containers/backend/Content/Wrapper.js
- client/src/containers/backend/People/Wrapper.js
- client/src/containers/backend/Project/Wrapper.js
- client/src/containers/backend/Resource/Wrapper.js
- client/src/containers/backend/Settings/Wrapper.js
- client/src/containers/backend/Text/Wrapper.js
- client/src/helpers/router/RedirectToFirstMatch.js
> [B] Correct RedirectToFirstMatch behavior

- api/app/services/ingestions/converters/html.rb
- api/spec/data/ingestion/html/with_inline_styles/a-stylesheet.css
- api/spec/data/ingestion/html/with_inline_styles/index.html
- api/spec/services/ingestions/compiler_spec.rb
- api/spec/services/ingestions/converters/html_spec.rb
- api/spec/services/ingestions/pre_processors/extract_stylesheets_spec.rb
> [B] Fix inline styles missing from ingestion stylesheets

- api/app/models/concerns/attachments.rb
- api/app/models/ingestion.rb
> [B] Don't validate content type for ingestions

- api/app/services/ingestions/concerns/file_operations.rb
- api/app/services/ingestions/context.rb
- api/app/services/ingestions/fetchers/google_doc.rb
- api/app/services/ingestions/strategies/manifest.rb
- api/spec/services/ingestions/compiler_spec.rb
- api/spec/services/ingestions/strategies/document_spec.rb
> [B] Use source path to map google doc files in manifest ingestion

- api/app/controllers/concerns/validation.rb
- api/app/models/ingestion.rb
- api/app/services/ingestions/compilers/text.rb
- api/app/services/ingestions/ingestor.rb
- api/app/services/ingestions/post_processor.rb
- api/app/services/ingestions/post_processors/spine.rb
- api/db/migrate/20180809232509_remove_reingestion_from_ingestions.rb
- api/db/schema.rb
- api/spec/services/ingestions/compiler_spec.rb
- api/spec/services/ingestions/post_processor_spec.rb
- client/src/components/backend/Ingestion/Form/Wrapper.js
> [B] Fix reingestions failing to identify text

- api/app/services/validator/stylesheet.rb
- api/spec/services/validator/stylesheet_spec.rb
> [B] Improve ingestion relative font-size conversion

- api/app/services/importer/project.rb
- api/app/services/ingestions/create_manually.rb
- api/lib/tasks/project.rake
- api/spec/services/ingestions/create_manually_spec.rb
> [B] Fix api ingestion creation through CLI

- client/src/theme/Components/backend/_grid-list.scss
- client/src/theme/Components/backend/_vertical-list.scss
- client/src/theme/Components/backend/project/_header.scss
- client/src/theme/Components/backend/text/_list.scss
- client/src/theme/Components/global/_nested-nav.scss
> [B] Fix display of borders for active vertical list items

- client/src/components/backend/Form/FieldGroup.js
- client/src/containers/backend/Project/Social/__tests__/__snapshots__/TwitterQueries-test.js.snap
- client/src/containers/backend/Text/__tests__/__snapshots__/Metadata-test.js.snap
- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
> [B] Move Form.FieldGroup instructions above form inputs

- client/src/theme/Components/backend/_grid-list.scss
- client/src/theme/Components/backend/_vertical-list.scss
> [B] Fix vertical list headers overflowing in IE 11

- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
> [B] Fix backend form select text being cut off

- api/app/lib/updaters/project.rb
- api/app/services/formatted_attributes/methods.rb
- client/src/components/backend/Navigation/__tests__/Secondary-test.js
- client/src/components/backend/Page/ListItem.js
- client/src/containers/backend/Pages/Detail.js
- client/src/containers/frontend/__tests__/Following-test.js
> [B] Allow blank project purchase price value

- client/src/theme/Components/browse/project-list/_grid-project.scss
> [B] Adjust frontend project grid hover styles

- api/app/services/annotations/adopt_or_orphan.rb
- api/app/services/ingestions/strategies/document.rb
- api/app/services/ingestions/strategy/document/ingestion_source.rb
- api/app/services/ingestions/strategy/document/inspector.rb
- api/app/views/notification_mailer/digest/daily/_text_event.html.erb
- api/app/views/notification_mailer/digest/daily/_text_event.text.erb
- api/spec/data/ingestion/html/reingestion/after.html
- api/spec/data/ingestion/html/reingestion/before.html
- api/spec/mailers/previews/notification_mailer_preview.rb
- api/spec/services/annotations/adopt_or_orphan_spec.rb
- api/spec/services/ingestions/ingestor_spec.rb
- api/spec/services/ingestions/integration/reingestion.rb
- api/spec/services/ingestions/strategies/document_spec.rb
- client/src/containers/backend/Project/ProjectPage.js
- client/src/containers/backend/Project/__tests__/__snapshots__/ProjectPage-test.js.snap
> Minor v2.0.0-rc.2 fixes

- api/app/services/ingestions/pre_processors/extract_text_section_bodies.rb
- api/spec/data/ingestion/markdown/special-characters.md
- api/spec/services/ingestions/ingestor_spec.rb
- api/spec/services/ingestions/integration/encoding.rb
- api/spec/services/ingestions/pre_processors/add_ids_to_headers.rb
> [B] Fix special characters breaking during ingestion

- api/app/services/search/query.rb
> [B] Specify model attributes in search query

- api/app/models/stylesheet.rb
- api/app/models/text_section.rb
- api/spec/models/stylesheet_spec.rb
- api/spec/models/text_section_spec.rb
> [B] Fix text section/stylesheet relationship behavior

- api/app/controllers/concerns/validation.rb
- api/app/models/concerns/taggable.rb
- api/app/models/project.rb
- api/app/models/resource.rb
- api/app/serializers/project_partial_serializer.rb
- api/spec/requests/projects_spec.rb
- client/src/containers/backend/Project/General.js
- client/src/containers/backend/Project/__tests__/__snapshots__/General-test.js.snap
Also refactors model tag behaviors into a concern
Closes #1376
> [C] Allow Projects to be tagged

- client/src/components/frontend/ProjectList/Grid.js
- client/src/theme/Components/browse/project-list/_grid-project.scss
> [B] Fix home page pagination arrow styles

- api/app/services/tweet/fetcher.rb
`query` is a reference to the entire `TwitterQuery` record.  We need to be passing just the query string to the twitter client.
Fixes #1412
> [B] Fix tweet fetcher passing entire object to query

- api/app/services/validator/html.rb
- api/spec/services/validator/html_spec.rb
> [B] Validator::Html should close void tags without attributes

- client/src/theme/Components/global/_nested-nav.scss
> [B] Fix vertical alignment of mobile header caret

- api/app/models/project.rb
- api/app/serializers/project_partial_serializer.rb
- client/src/components/frontend/Project/Hero.js
- client/src/theme/Components/browse/project/_hero.scss
> [B] Don't italicize <em> tags in project hero subtitle

- client/src/components/reader/Header.js
- client/src/containers/reader/Reader.js
- client/src/store/reducers/ui/transitory/visibility.js
> [B] Close reader TOC when clicked outside of

- api/app/services/validator/stylesheet.rb
> [B] Catch invalid hex exception in SS validator

- client/src/helpers/router/navigation.js
> [B] Fix records/features nav link permissions

- client/src/theme/Components/global/forms/_form-inputs-custom.scss
> [B] Override button focus state border for toggles

- api/app/services/ingestions/pre_processors/extract_stylesheets.rb
> [B] Derelativize stylesheet paths when determining source file

- api/app/lib/updaters/project.rb
- api/spec/requests/projects_spec.rb
> [B] Fix purchase price being reset on project update

- client/src/containers/backend/Dashboards/Admin.js
- client/src/containers/backend/Dashboards/__tests__/__snapshots__/Admin-test.js.snap
- client/src/theme/Components/global/_list-total.scss
- client/src/theme/Components/global/_section-heading-secondary.scss
> [B] Fix secondary header link styles

- client/src/containers/backend/Pages/Detail.js
- client/src/containers/backend/Text/Wrapper.js
- client/src/containers/backend/Text/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/containers/backend/Users/List.js
- client/src/containers/backend/Users/__tests__/__snapshots__/List-test.js.snap
> [B] Replace remaining .backend-panel usages with component

- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
> [B] Fix alignment of dropzone form content in IE11

- client/src/theme/Components/global/_list-total.scss
> [B] Fix leading of entity count in backend header

- client/src/theme/Components/backend/_vertical-list.scss
> [B] Fix overflow bug in IE 11 with tile-style list items

- client/src/components/backend/Feature/ListItem.js
- client/src/components/backend/Page/ListItem.js
These now use the IconComposer component
Fixes #1510
> [B] Remove remaining Resource.Icon usages

- api/app/controllers/api/v1/resources_controller.rb
> [B] Fix resource show not returning project

- client/src/components/backend/Form/Select.js
> [B] Consistently position form input instructions

- api/app/services/validator/stylesheet.rb
- api/spec/services/validator/stylesheet_spec.rb
> [B] Accept UTF8 chars in ingestion source styles

- client/src/theme/Components/backend/project-collection/_wrapper.scss
> [B] Adjust padding on Project Collection header

- client/src/theme/Components/reader/notation/_detail.scss
> [B] Fix button layout in reader resource modal

- client/src/components/reader/Notation/Marker.js
- client/src/components/reader/Notation/Viewer/Link.js
- client/src/components/reader/Notation/Viewer/__tests__/__snapshots__/Group-test.js.snap
- client/src/containers/reader/Notation/Resource/Detail.js
> [B] Maintain scroll pos in reader resource overlay

- client/src/components/frontend/Layout/Header.js
- client/src/components/global/Navigation/Mobile/Breadcrumb.js
- client/src/helpers/router/navigation.js
> [B] Address active state matching in mobile nav

- client/src/containers/backend/ProjectCollection/Detail.js
> [B] Fix pagination class in backend Project Collections

- client/src/theme/Components/_base.scss
- client/src/theme/Components/backend/_button-switch.scss
- client/src/theme/Components/global/forms/_form-inputs-custom.scss
> [B] Normalize global focus appearance

- client/src/components/frontend/ProjectCollection/Summary.js
- client/src/containers/frontend/__tests__/__snapshots__/ProjectCollections-test.js.snap
- client/src/theme/Components/browse/project-list/_project-grid.scss
- client/src/theme/Components/browse/project-list/_project-list-container.scss
> [F] Implement message for empty project collections

- client/src/containers/frontend/Home.js
- client/src/containers/frontend/ProjectCollections.js
> [B] Show project collections without projects

- client/src/store/reducers/fatalError.js
> [B] Handle API 502 errors in client

- client/src/theme/Components/global/_drawer.scss
> [B] Fix focus appearance of close button in annotation drawer

- api/app/models/resource_import_row.rb
- client/src/components/backend/ResourceImport/Control.js
- client/src/components/backend/ResourceImport/Controls/Imported.js
- client/src/components/backend/ResourceImport/Controls/Importing.js
- client/src/components/backend/ResourceImport/Controls/Parsed.js
- client/src/components/backend/ResourceImport/Controls/index.js
- client/src/components/backend/ResourceImport/Result.js
- client/src/components/backend/ResourceImport/Results/Failed.js
- client/src/components/backend/ResourceImport/Results/Imported.js
- client/src/components/backend/ResourceImport/Results/Importing.js
- client/src/components/backend/ResourceImport/Results/Pending.js
- client/src/components/backend/ResourceImport/Results/Queued.js
- client/src/components/backend/ResourceImport/Results/Skipped.js
- client/src/components/backend/ResourceImport/Results/index.js
- client/src/components/backend/ResourceImport/index.js
- client/src/components/backend/index.js
- client/src/containers/backend/ResourceImport/Results.js
> [C] Break ResourceImportResults into components

- client/src/containers/frontend/Projects.js
> [B] Fix duplicate request on projects search

- api/app/controllers/concerns/validation.rb
- api/app/models/settings.rb
- client/src/components/frontend/Project/__tests__/Events-test.js
- client/src/components/global/HeadContent.js
- client/src/components/global/SignInUp/Create.js
- client/src/config.js
- client/src/containers/Manifold.js
- client/src/containers/backend/Settings/General.js
- client/src/containers/backend/Settings/__tests__/__snapshots__/General-test.js.snap
- client/src/containers/frontend/Page.js
> [B] Improve open graph meta tags

- api/app/models/text.rb
- api/app/models/text_title.rb
- api/app/serializers/text_serializer.rb
- api/spec/models/text_spec.rb
- client/src/components/frontend/Text/Cover.js
- client/src/components/frontend/Text/Thumbnail.js
- client/src/components/frontend/Text/__tests__/__snapshots__/Thumbnail-test.js.snap
- client/src/components/frontend/TextList/__tests__/__snapshots__/Grouped-test.js.snap
- client/src/components/frontend/TextList/__tests__/__snapshots__/Published-test.js.snap
- client/src/components/reader/Annotation/Popup/Secondary/Share.js
- client/src/components/reader/Header.js
- client/src/components/reader/TextTitles.js
- client/src/components/reader/__tests__/__snapshots__/TextTitles-test.js.snap
- client/src/containers/backend/Project/Texts.js
- client/src/containers/backend/Project/__tests__/__snapshots__/Texts-test.js.snap
- client/src/containers/backend/Text/Wrapper.js
- client/src/containers/reader/Reader.js
- client/src/containers/reader/Section.js
- client/src/containers/reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/test/fixtures/entity.js
> [B] Allow text titles to be formatted

- api/app/authorizers/application_authorizer.rb
- api/app/authorizers/project_collection_authorizer.rb
- api/spec/authorizers/project_collection_authorizer_spec.rb
> [B] Allow marketeer CRUD abilities on ProjectCollection

- api/app/controllers/concerns/validation.rb
- client/src/containers/backend/ProjectCollection/Settings.js
- client/src/containers/backend/ProjectCollection/__tests__/__snapshots__/Settings-test.js.snap
> [B] Allow project collection slugs to be edited

- client/src/containers/backend/ProjectCollection/New.js
- client/src/containers/backend/ProjectCollection/Settings.js
> [B] Focus on input in project collection drawer

- api/app/serializers/project_collection_serializer.rb
- client/src/components/frontend/ProjectCollection/Detail.js
- client/src/components/frontend/ProjectCollection/Summary.js
- client/src/containers/frontend/ProjectCollectionDetail.js
> [B] Use formatted project collection descriptions

- api/app/models/concerns/validates_slug_presence.rb
- api/config/initializers/30_monkeypatches.rb
- api/lib/patches/friendly_id_uniqueness.rb
> [B] Validate slug uniqueness

- client/src/containers/frontend/Projects.js
> [B] FE projects container respects query filters

- api/app/models/concerns/attachments.rb
- api/app/models/ingestion_source.rb
- api/app/models/text.rb
- api/app/services/demonstration/data_loader.rb
- api/app/services/importer/project.rb
- api/app/services/ingestions/post_processor.rb
- api/app/services/ingestions/post_processors/set_text_cover.rb
- api/app/uploaders/attachment_uploader.rb
- api/app/uploaders/resource_uploader.rb
- api/config/locales/services/ingestions/en.yml
- api/db/migrate/20181112224435_add_cover_data_to_texts.rb
- api/db/migrate/20181113020917_migrate_existing_covers_to_texts.rb
- api/db/schema.rb
- api/spec/models/concerns/attachment_spec.rb
> [B] Adjust AttachmentUploader storage paths/cache

- api/app/services/ingestions/converters/abstract_converter.rb
- api/config/locales/services/ingestions/en.yml
> [C] Report file conversion during ingestion

- api/app/services/ingestions/compilers/text_section.rb
> [B] Text sections without names are valid

- api/app/controllers/concerns/validation.rb
- api/app/lib/updaters/settings.rb
- api/app/models/concerns/attachments.rb
- api/app/models/settings.rb
- api/app/serializers/settings_serializer.rb
- api/app/services/attachments/style_configurer.rb
- api/config/manifold.yml
- api/db/migrate/20181109165055_add_favicon_to_settings.rb
- api/db/schema.rb
- client/src/containers/backend/Settings/Theme.js
- client/src/containers/backend/Settings/__tests__/__snapshots__/Theme-test.js.snap
- client/src/helpers/Html.js
> [F] Allow favicon to be set per installation

- client/src/components/frontend/Layout/Footer.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/Footer-tests.js.snap
- client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
> [B] Remove hard-coded copyright symbol from footer

- client/src/theme/_z-stack.scss
> [B] Correct section-category-label z-index

- api/app/models/settings.rb
- api/app/serializers/settings_serializer.rb
- client/src/components/frontend/Layout/Footer.js
- client/src/components/frontend/Layout/__tests__/__snapshots__/Footer-tests.js.snap
- client/src/containers/backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/containers/frontend/__tests__/__snapshots__/Frontend-test.js.snap
- client/src/test/fixtures/entity.js
> [B] Allow markdown in footer copyright text

- api/app/controllers/concerns/validation.rb
- api/app/models/concerns/with_parsed_name.rb
- api/app/models/maker.rb
- api/app/models/user.rb
- api/app/serializers/maker_serializer.rb
- api/app/services/ingestions/strategy/epub/maker.rb
- api/db/migrate/20181114164356_add_prefix_to_makers.rb
- api/db/migrate/20181114164450_add_maker_index_on_names.rb
- api/db/migrate/20181114170950_remove_sort_name_from_makers.rb
- api/db/schema.rb
- api/spec/models/concerns/with_parsed_name_spec.rb
- api/spec/models/maker_spec.rb
- api/spec/services/ingestions/strategies/epub_spec.rb
- client/src/containers/backend/Makers/Form.js
- client/src/containers/backend/Makers/__tests__/__snapshots__/Edit-test.js.snap
- client/src/containers/backend/Makers/__tests__/__snapshots__/New-test.js.snap
- client/src/helpers/fakeData.js
> [B] Improve Maker name parsing and ordering

- api/app/controllers/concerns/validation.rb
- api/app/serializers/feature_serializer.rb
- api/db/migrate/20181114185600_add_include_sign_up_to_features.rb
- api/db/schema.rb
- client/src/components/frontend/Layout/Splash.js
- client/src/containers/backend/Features/General.js
> [F] Allow sign up link to be disabled per feature

- api/app/services/ingestions/compilers/text.rb
- api/config/locales/services/ingestions/en.yml
> [B] Fix reingestion failing on cover source report

- client/src/store/reducers/fatalError.js
> [B] Handle penging migration errors in client

- api/spec/requests/project_collections_spec.rb
- client/src/containers/backend/Form/Form.js
> [B] Fix model creation with associations

- client/src/containers/backend/Form/Form.js
- client/src/containers/backend/Permission/Form.js
> [B] Fix regression in Permission creation

- api/app/services/ingestions/concerns/file_operations.rb
> [B] Improve ingestion file rejection criteria

- api/app/services/search/query.rb
> [B] Global search consults metadata fields

- api/app/controllers/api/proxy/ingestion_sources_controller.rb
- api/app/models/ingestion_source.rb
- api/app/models/text.rb
- api/config/routes.rb
- api/spec/services/ingestions/post_processors/text_section_body_spec.rb
- client/src/servers/common/app.js
> [B] Proxy IS attachments through API controller

- client/src/backend/containers/permission/Form.js
> [B] Sort users by name in permissions form

- api/app/models/project.rb
> [B] Fix Project#resource_tags returning relationship

- client/src/theme/Components/global/forms/_form-inputs-primary.scss
- client/src/theme/Components/global/forms/_list-filter.scss
> [B] Fix FF dropdown option styles

- client/src/backend/components/form/Upload/Base.js
- client/src/backend/components/form/Upload/Preview.js
- client/src/backend/components/form/Upload/index.js
- client/src/backend/components/resource/form/kind/File.js
- client/src/backend/containers/project/ProjectPage.js
> [B] Improve upload file name previews

- client/src/theme/Components/global/_header-app.scss
> [B] Fix frontend header menu positions

- api/app/authorizers/flag_authorizer.rb
- api/app/models/annotation.rb
- api/app/models/comment.rb
- api/app/serializers/annotation_serializer.rb
- api/app/serializers/comment_serializer.rb
- api/config/routes.rb
- api/db/migrate/20181207201023_add_flags_count_to_annotations.rb
- api/db/schema.rb
- client/src/api/requests.js
- client/src/api/resources/annotations.js
- client/src/global/components/comment/meta/index.js
- client/src/reader/components/annotation/Detail.js
- client/src/reader/components/annotation/Meta.js
- client/src/reader/components/annotation/__tests__/__snapshots__/Detail-test.js.snap
- client/src/reader/containers/annotation/__tests__/__snapshots__/List-test.js.snap
- client/src/theme/Components/reader/annotation/_meta.scss
> [B] Implement flagging on annotations

- api/app/services/tweet/fetcher.rb
- client/src/backend/containers/twitter-query/Edit.js
- client/src/backend/containers/twitter-query/__tests__/__snapshots__/Edit-test.js.snap
> [B] Hide tweet fetching if not configured

- client/src/reader/routes.js
> [B] Fix typo in route component name

- api/app/models/concerns/resource_attribute_resets.rb
- client/src/backend/components/resource/form/kind/Variants.js
- client/src/backend/components/resource/form/kind/Variants/Default.js
- client/src/backend/components/resource/form/kind/Variants/Image.js
- client/src/backend/components/resource/form/kind/Variants/Interactive.js
- client/src/backend/components/resource/form/kind/Variants/Pdf.js
- client/src/backend/components/resource/form/kind/Variants/Video.js
- client/src/frontend/components/resource-player/Video.js
- client/src/frontend/components/resource-preview/__tests__/Video-test.js
Also refactors variant form components and adds support for a video
file poster image.
> [B] Fix video thumbnail attachments not saving

- client/src/backend/components/project/Content/Block/in-list/Current.js
- client/src/backend/components/project/Content/Block/parts/Drag.js
- client/src/theme/Components/backend/project/_content-block-grid.scss
- client/src/theme/Components/backend/project/_content-block-list.scss
- client/src/theme/Components/backend/project/_content-block.scss
* Fixes issue with blocks lacking padding while dragging
* Replaces dropzone border color with background color
* Fixes regression in block heading layout
* Better centers block titles vertically
* Fixes some layout issues in IE11
* Fixes a bug with current blocks not dragging in IE11
> [B] Fix backend content block UI bugs

- client/src/helpers/passwordGenerator.js
> [B] Fix password generator throwing exception

- api/app/serializers/content/markdown_block_serializer.rb
- client/src/frontend/components/project/Content/Block/parts/Wrapper.js
- client/src/frontend/components/project/Content/Block/types/Markdown.js
- client/src/theme/Components/browse/layout/_entity-section-wrapper.scss
- client/src/theme/Components/browse/page/_content.scss
* Builds markup and styles for block wrapper and style attribute
* Exposes body_formatted attribute for block
* Updates page-content styles for markdown content
> Build out frontend for Markdown content block

- client/package.json
- client/src/backend/components/form/DatePicker.js
- client/src/backend/components/form/DatePicker/Header.js
- client/src/backend/components/form/MaskedTextInput.js
- client/src/backend/components/form/__tests__/DatePicker-test.js
- client/src/backend/components/form/__tests__/__snapshots__/DatePicker-test.js.snap
- client/src/backend/components/form/index.js
- client/src/global/components/form/Errorable.js
- client/src/theme/Components/global/forms/_form-inputs-primary.scss
- client/src/theme/theme.scss
- client/yarn.lock
> [F] Add DatePicker form component

- api/app/controllers/concerns/validation.rb
- api/app/models/project_collection.rb
- api/app/serializers/project_collection_serializer.rb
- api/db/migrate/20190117215354_add_homepage_count_to_project_collections.rb
- api/db/schema.rb
- client/src/backend/components/form/NumberInput.js
- client/src/backend/components/form/__tests__/__snapshots__/NumberInput-test.js.snap
- client/src/backend/components/project-collection/form/Fields.js
- client/src/backend/components/project-collection/form/SmartAttributes.js
- client/src/backend/components/project-collection/form/__tests__/__snapshots__/SmartAttributes-test.js.snap
- client/src/frontend/components/project-collection/Summary.js
- client/src/frontend/components/project-list/Grid.js
- client/src/frontend/containers/Home/Collections.js
Built on #1788 because of the form refactor.
> [F] Allow PC's to specify visible HP projects

- client/src/theme/STACSS/_structure.scss
- client/src/theme/_variables.scss
> [C] Update .container padding on narrow viewports

- client/src/theme/Components/global/_buttons.scss
Adjusts vertical padding, font-size, and letter-spacing slightly.
Resolves #1820
> [C] Adjust button-primary & button-secondary styles

- client/src/theme/Components/browse/layout/_footer-browse.scss
> [B] Correct social footer links padding

- client/src/reader/components/notation/viewer/List.js
> [B] Fix Reader crashing when updating notations

- client/src/backend/components/event/ListItem.js
- client/src/backend/components/event/__tests__/__snapshots__/ListItem-test.js.snap
- client/src/backend/containers/project/__tests__/__snapshots__/Events-test.js.snap
- client/src/theme/Components/backend/_vertical-list.scss
- client/src/theme/Components/browse/event/_tile.scss
* Fixes hover/focus state appearance
* adds scoping for colors and spacing on backend
> Minor adjustments to Event tile styling

- config/dev/nginx.conf.erb
- script/setup
> [B] Fix nginx conf template upstreams

- api/app/controllers/api/v1/texts_controller.rb
- api/app/models/text.rb
> [F] Make Text#toc_section an AR relationship

- client/src/backend/containers/project-collection/Settings.js
> [B] Address project collection edit premature close

- api/app/controllers/concerns/validation.rb
- api/app/models/project.rb
- api/app/serializers/project_serializer.rb
- api/db/migrate/20190205175552_add_image_credits_to_projects.rb
- api/db/schema.rb
- client/src/backend/components/project/hero/Builder/forms/Description.js
- client/src/backend/containers/project/__tests__/__snapshots__/Permissions-test.js.snap
- client/src/frontend/components/project/Hero/Callout/types/Link.js
- client/src/frontend/components/project/Hero/Credits.js
- client/src/frontend/components/project/Hero/index.js
- client/src/frontend/components/project/__tests__/__snapshots__/Detail-test.js.snap
- client/src/frontend/components/project/__tests__/__snapshots__/Hero-test.js.snap
- client/src/frontend/containers/ProjectDetail/__tests__/__snapshots__/ProjectDetail-test.js.snap
- client/src/test/fixtures/entity.js
- client/src/theme/Components/browse/project/_action-callout-list.scss
- client/src/theme/Components/browse/project/_hero.scss
* Adds Credits component & adds styles for markup
* Revises markup & styles of project hero to handle revised layout
* Improves prefixing of layout styles to handle grid layout in IE11
Resolves #1689
> [F] Add image credits to project hero

- client/src/backend/containers/project-collection/New.js
> [B] Set default PC number of projects to 8

- client/src/frontend/containers/ResourceCollectionDetail/index.js
> [B] Load slideshow resources on all pages

- client/src/theme/Components/browse/project/_action-callout-list.scss
> [B] Fix action callout list margin

- client/src/frontend/components/TextList/ListItem/Bibliographic.js
> [B] Fix TextsBlock not showing subtitles

- api/app/models/action_callout.rb
> [B] ActionCallout attachment does not generate styles during processing

- client/src/theme/Components/backend/project/_content-block.scss
> [B] Fix current content blocks cursor styles

- client/src/global/components/sign-in-up/Create.js
- client/src/global/components/sign-in-up/Login.js
- client/src/global/components/sign-in-up/LoginExternal.js
- client/src/global/components/sign-in-up/__tests__/__snapshots__/Create-test.js.snap
- client/src/test/fixtures/entity.js
> [B] Fix OAuth login options text

- client/src/helpers/Html.js
> [B] Correct body class application on SSR

- client/src/store/middleware/currentUserMiddleware.js
This commit refactors the auth cookie setting into its own function.
This function responds to the `LOGIN_SET_AUTH_TOKEN` action, which sets
the auth token in state.  With this change, the auth token will also be
set in a cookie to persist login sessions.  This will fix an issue where
logging in with OAuth would not set an auth token cookie and thus
would log users out on a refresh.
Fixes #1898
> [B] Fix OAuth sessions not setting cookie

- api/app/serializers/version_serializer.rb
- client/src/backend/components/log/ListItem.js
> [B] Fix issue with deleted log items throwing error

- client/src/frontend/components/content-block/Block/parts/Incomplete.js
- client/src/servers/proxies/renderer.js
- client/src/store/middleware/currentUserMiddleware.js
> [B] Update method arguments

- api/app/models/text.rb
- client/src/backend/components/metadata/Form.js
- client/src/config/app/locale.js
> [F] Add original publication date to texts meta

- client/src/global/components/sign-in-up/__tests__/Login-test.js
> [B] Fix proptype error in Login component test

- api/app/services/ingestions/strategies/epub.rb
- api/app/services/ingestions/strategies/manifest.rb
- client/src/backend/containers/ingestion/Ingest.js
> [B] Improve performance for ingestions with many sources

- client/src/backend/components/content-block/TypeForm/types/__tests__/__snapshots__/Markdown-test.js.snap
- client/src/backend/components/form/Radio/Label.js
- client/src/backend/components/form/Radio/Option.js
- client/src/backend/components/form/Radios.js
- client/src/backend/components/form/__tests__/Radios-test.js
- client/src/backend/components/form/__tests__/__snapshots__/Radios-test.js.snap
- client/src/hoc/with-form-options/index.js
- client/src/theme/Components/global/forms/_form-inputs-primary.scss
- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
- client/src/theme/Components/global/forms/_section.scss
> [F] Add prompt and option instructions to Radios

- api/app/controllers/api/v1/projects_controller.rb
- api/app/services/content/scaffold_configured.rb
- api/app/services/content/scaffold_project_content.rb
- api/app/services/content/scaffold_template.rb
- api/spec/services/content/scaffold_project_content_spec.rb
- client/src/backend/containers/project/New.js
- client/src/backend/containers/project/__tests__/__snapshots__/New-test.js.snap
- client/src/theme/Components/global/_utilities.scss
- client/src/theme/Components/global/forms/_form-inputs-primary.scss
- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
- client/src/theme/Components/global/forms/_section.scss
Note 254de18 is in its own PR at #1962
> [F] Add layout config options to new project form

- api/app/services/system_upgrades/upgrades/manifold030000.rb
> [C] Adjust v3.0 system upgrade content blocks

- client/src/backend/components/content-block/helpers/draggableEvent.js
> [B] Don't show warnings on pending blocks

- api/app/services/content/scaffold_template.rb
> [C] Remove duplicate ScaffoldTemplate constant

- api/app/authorizers/permission_authorizer.rb
- api/app/authorizers/project_authorizer.rb
- api/spec/authorizers/permission_authorizer_spec.rb
- api/spec/authorizers/project_authorizer_spec.rb
> [B] Adjust permissions authorization

- api/app/models/concerns/with_parsed_name.rb
- api/spec/models/concerns/with_parsed_name_spec.rb
> [B] Restrict first and last names to 50 characters

- client/src/backend/containers/project/General.js
- client/src/backend/containers/project/__tests__/__snapshots__/General-test.js.snap
> [B] Adjust project draft switch label text

- client/src/backend/components/list/__tests__/__snapshots__/Orderable-test.js.snap
- client/src/backend/components/list/__tests__/__snapshots__/SimpleList-test.js.snap
- client/src/backend/components/project/ListItem.js
- client/src/backend/components/project/__tests__/__snapshots__/ListItem-test.js.snap
- client/src/backend/containers/dashboards/__tests__/__snapshots__/Admin-test.js.snap
- client/src/backend/containers/dashboards/__tests__/__snapshots__/Author-test.js.snap
- client/src/global/components/svg/ProjectPlaceholder.js
- client/src/theme/Components/global/_accessibility.scss
- client/src/theme/Components/global/_index.scss
Removes alt-text and adds an aria-describedby attribute to the anchors.
Fixes #2012
> [B] Fix backend project list item accessibility

- api/app/models/application_record.rb
- api/app/models/resource.rb
- api/app/services/resources/extract_external_video_id.rb
- api/spec/models/resource_spec.rb
- api/spec/services/resources/extract_external_video_id.rb
- client/src/backend/components/resource/form/kind/Video.js
- client/src/backend/components/resource/form/kind/__tests__/__snapshots__/Video-test.js.snap
> [F] Improvements to external video external_id

- client/src/backend/components/list/Searchable.js
- client/src/backend/components/list/SimpleList.js
- client/src/backend/components/list/__tests__/__snapshots__/Searchable-test.js.snap
- client/src/backend/components/list/__tests__/__snapshots__/SimpleList-test.js.snap
- client/src/backend/containers/dashboards/__tests__/__snapshots__/Admin-test.js.snap
- client/src/backend/containers/dashboards/__tests__/__snapshots__/Author-test.js.snap
- client/src/backend/containers/makers/__tests__/__snapshots__/List-test.js.snap
- client/src/backend/containers/permission/__tests__/__snapshots__/List-test.js.snap
- client/src/backend/containers/project-collection/Detail/__tests__/__snapshots__/Manual-test.js.snap
- client/src/backend/containers/project-collection/Detail/__tests__/__snapshots__/Smart-test.js.snap
- client/src/backend/containers/project-collection/__tests__/__snapshots__/ManageProjects-test.js.snap
- client/src/backend/containers/project/__tests__/__snapshots__/Events-test.js.snap
- client/src/backend/containers/project/__tests__/__snapshots__/Log-test.js.snap
- client/src/backend/containers/project/resource/__tests__/__snapshots__/ResourceCollectionsList-test.js.snap
- client/src/backend/containers/project/resource/__tests__/__snapshots__/ResourcesList-test.js.snap
- client/src/backend/containers/project/social/__tests__/__snapshots__/TwitterQueries-test.js.snap
- client/src/backend/containers/resource-collection/__tests__/__snapshots__/Resources-test.js.snap
- client/src/backend/containers/settings/subjects/__tests__/__snapshots__/List-test.js.snap
- client/src/backend/containers/users/__tests__/__snapshots__/List-test.js.snap
- client/src/reader/containers/notation/__tests__/__snapshots__/Picker-test.js.snap
- client/src/theme/Components/backend/_dashboard.scss
- client/src/theme/Components/backend/_project-list.scss
- client/src/theme/Components/backend/_vertical-list.scss
- client/src/theme/Components/backend/ingestion/_ingest.scss
- client/src/theme/Components/global/_list-total.scss
> [B] Adjust list margins between button/content

- client/src/backend/components/content-block/TypeForm/types/__tests__/__snapshots__/TableOfContents-test.js.snap
- client/src/backend/components/form/Switch.js
- client/src/backend/components/form/__tests__/__snapshots__/Switch-test.js.snap
- client/src/backend/components/form/__tests__/__snapshots__/SwitchArray-test.js.snap
- client/src/backend/components/project-collection/form/__tests__/__snapshots__/SmartAttributes-test.js.snap
- client/src/backend/components/resource/form/kind/__tests__/__snapshots__/Video-test.js.snap
- client/src/backend/components/twitter-query/__tests__/__snapshots__/Form-test.js.snap
- client/src/backend/containers/permission/__tests__/__snapshots__/Edit-test.js.snap
- client/src/backend/containers/permission/__tests__/__snapshots__/Form-test.js.snap
- client/src/backend/containers/permission/__tests__/__snapshots__/New-test.js.snap
- client/src/backend/containers/project-collection/__tests__/__snapshots__/New-test.js.snap
- client/src/backend/containers/project-collection/__tests__/__snapshots__/Settings-test.js.snap
- client/src/backend/containers/project/__tests__/__snapshots__/General-test.js.snap
- client/src/backend/containers/project/__tests__/__snapshots__/ProjectPage-test.js.snap
- client/src/backend/containers/text/__tests__/__snapshots__/General-test.js.snap
- client/src/backend/containers/twitter-query/__tests__/__snapshots__/Edit-test.js.snap
- client/src/backend/containers/twitter-query/__tests__/__snapshots__/New-test.js.snap
- client/src/theme/Components/browse/subscriptions/_subscriptions.scss
- client/src/theme/Components/global/forms/_form-inputs-primary.scss
- client/src/theme/Components/global/forms/_form-inputs-secondary.scss
> [B] Use label tags for form switch labels

- client/src/backend/containers/Backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/backend/containers/Backend/index.js
- client/src/backend/containers/Records/index.js
- client/src/backend/containers/pages/Detail.js
- client/src/backend/containers/project/Wrapper.js
- client/src/backend/containers/project/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/backend/containers/projects/Wrapper.js
- client/src/backend/containers/resource-collection/Wrapper.js
- client/src/backend/containers/resource-collection/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/backend/containers/resource/Wrapper.js
- client/src/backend/containers/resource/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/backend/containers/settings/Wrapper.js
- client/src/backend/containers/settings/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/backend/containers/text/Wrapper.js
- client/src/backend/containers/text/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/frontend/containers/Frontend/__tests__/__snapshots__/Frontend-test.js.snap
- client/src/frontend/containers/Frontend/index.js
- client/src/global/components/utility/SkipLink.js
- client/src/reader/containers/Reader/__tests__/__snapshots__/Reader-test.js.snap
- client/src/reader/containers/Reader/index.js
- client/src/theme/Components/global/_index.scss
- client/src/theme/Components/global/_skip-to-main.scss
- client/src/theme/_z-stack.scss
> [B] Remove secondary skip-to links

- client/src/theme/Components/backend/_drawer.scss
> [B] Show close text in backend drawers

- client/src/backend/components/content-block/Builder/Block/parts/Identity.js
> [B] Fix incomplete content block icon

- api/app/models/resource.rb
- api/app/models/version.rb
- api/app/serializers/version_serializer.rb
> [B] Ignore attachment changes in resource versions

- client/src/theme/Components/backend/category/_text-list.scss
> [B] Add margin to text subtitle in list item

- client/src/theme/Components/global/_buttons.scss
> [B] Fix backend drawer button widths

- client/src/reader/components/Header/index.js
- client/src/reader/components/section/NextSection.js
- client/src/reader/components/section/Pagination.js
- client/src/reader/components/section/__tests__/__snapshots__/NextSection-test.js.snap
- client/src/reader/containers/Reader/index.js
- client/src/reader/containers/Section/index.js
- client/src/theme/Components/reader/_footer-menu.scss
- client/src/theme/Components/reader/_header-reader.scss
- client/src/theme/Components/reader/_section-category-label.scss
- client/src/theme/Components/reader/_section-next-section.scss
- client/src/theme/Components/reader/_section-pagination.scss
> [F] Improve reader dark scheme styles

- client/src/theme/Components/browse/project/_hero.scss
> [B] Remove italic styling from hero image credits

- api/app/models/content/texts_block.rb
- api/app/models/text.rb
- api/spec/models/content/texts_block_spec.rb
> [B] Fix TextsBlock texts scoping

- client/src/frontend/components/utility/__tests__/Toggle-test.js
- client/src/frontend/components/utility/__tests__/__snapshots__/Toggle-test.js.snap
> [B] Fix Utility.Toggle test prop type error

- client/src/theme/Components/global/forms/_form-inputs-primary.scss
> [B] Fix form radio label text colors

- client/src/backend/containers/dashboards/Admin.js
- client/src/backend/containers/dashboards/__tests__/__snapshots__/Admin-test.js.snap
> [B] Add new project button back to dashboard

- client/src/store/middleware/currentUserMiddleware.js
> [B] Fix incorrect feedback on invalid login

- client/src/reader/containers/notation/Picker.js
- client/src/reader/containers/notation/__tests__/__snapshots__/Picker-test.js.snap
> [B] Add search back to reader notations drawer

- client/src/theme/styles/components/backend/_activity_stats.scss
> [B] Fix font-family in BE dashboard stats

- client/src/theme/styles/components/frontend/layout/_entity-section-wrapper.scss
> [B] Fix size of project block header icon

- client/src/theme/styles/components/backend/list/entity/_entity-list.scss
- client/src/theme/styles/components/frontend/event/_events.scss
> [B] Fix layout of FE & BE event tiles

- client/src/backend/containers/ingestion/Actions.js
- client/src/backend/containers/ingestion/Heading.js
- client/src/backend/containers/ingestion/Ingest.js
- client/src/backend/containers/ingestion/__tests__/__snapshots__/Ingest-test.js.snap
- client/src/theme/styles/components/backend/ingestion/_ingest.scss
- client/src/theme/styles/components/global/_buttons.scss
> [R] Improve ingestion UI

- client/src/theme/styles/components/global/forms/_form-inputs-primary.scss
> [B] Use correct font in DatePicker

- client/src/theme/styles/components/backend/project-collection/_form.scss
Prevents form elements from unexpectedly increasing the size of the drawer.
Resolves #2116
> [B] Set max-width on PC drawer form

- api/app/controllers/concerns/validation.rb
- api/app/models/concerns/filterable.rb
- api/app/models/project.rb
- api/spec/models/project_spec.rb
- api/spec/models/user_spec.rb
- client/src/backend/containers/dashboards/__tests__/__snapshots__/Admin-test.js.snap
- client/src/backend/containers/project-collection/__tests__/__snapshots__/ManageProjects-test.js.snap
- client/src/hoc/with-filtered-lists/project-filters.js
> [F] Add created by me filter to projects lists

- api/app/models/content_block.rb
- api/app/serializers/project_serializer.rb
- client/src/backend/components/content-block/Builder/Block/in-list/Available.js
- client/src/backend/components/content-block/Builder/Block/in-list/Current.js
- client/src/backend/components/content-block/Builder/Block/parts/Delete.js
- client/src/backend/components/content-block/Builder/Block/parts/Edit.js
- client/src/backend/components/content-block/Builder/Block/parts/Identity.js
- client/src/backend/components/content-block/Builder/Block/parts/VisibilityToggle.js
- client/src/backend/components/content-block/DrawerHeader.js
- client/src/backend/components/list/EntitiesList/Entity/FeatureRow.js
- client/src/backend/components/list/__stories__/Entities.stories.js
- client/src/backend/containers/features/List.js
- client/src/frontend/components/content-block/index.js
- client/src/theme/styles/components/backend/list/entity/_entity-list-search.scss
- client/src/theme/styles/components/backend/list/entity/_entity-row.scss
- client/src/theme/styles/components/backend/project/_content-block.scss
> [F] Add publish toggle to feature list

- client/src/theme/styles/components/backend/list/entity/_entity-list.scss
> [B] Set fixed columns on grid entity lists

- client/src/frontend/components/content-block/Block/types/Resources.js
> [B] Do not show collections link of no collections exist

- client/src/theme/styles/components/frontend/collection/_list.scss
- client/src/theme/styles/components/frontend/event/_tile.scss
- client/src/theme/styles/components/global/_asset-thumbnail.scss
> [B] Prevent hyphens in FE resource & event tiles

- api/db/migrate/20160511233642_add_attachment_avatar_to_users.rb
- api/db/migrate/20180726223400_add_shrine_source_to_ingestions.rb
Fresh DB migrations will fail without this commit.
> [B] Require paperclip migrator in missed files

- api/app/models/action_callout.rb
- api/app/serializers/action_callout_serializer.rb
- api/spec/models/action_callout_spec.rb
- client/src/frontend/components/project/Hero/Callout/types/Link.js
- client/src/frontend/components/project/__tests__/Hero-test.js
- client/src/test/fixtures/entity.js
> [B] Open relative CTA links in same tab

- api/app/models/concerns/proxied_associations.rb
- api/app/models/content_block.rb
> [B] Handle deleted associations in content blocks

- client/src/theme/styles/components/frontend/event/_events.scss
- client/src/theme/styles/components/frontend/text/_text-block.scss
- client/src/theme/styles/components/global/_metadata.scss
> [B] Fix IE11 content block issues

- client/src/theme/styles/components/frontend/project/_resource-thumbnail-list.scss
> [B] Fix hidden resource thumbnails

- client/src/theme/styles/base/_z-stack.scss
- client/src/theme/styles/base/structure/_index.scss
- client/src/theme/styles/components/global/_header-app.scss
Fixes a bug that was hiding the close button in the mobile navigation.
> [B] Fix regression in mobile nav overlay

- client/src/theme/styles/components/backend/list/entity/_entity-list-search.scss
> [B] Fix vertical alignment of list filter icon

- api/app/models/collection_project.rb
- api/app/models/collection_project_ranking.rb
- api/app/models/concerns/materialized_view.rb
- api/app/models/concerns/view.rb
- api/app/models/project.rb
- api/app/models/project_collection.rb
- api/app/models/project_collection_sort_order.rb
- api/app/serializers/project_collection_serializer.rb
- api/db/migrate/20190506192451_create_project_collection_sort_orders.rb
- api/db/migrate/20190506192655_create_collection_project_rankings.rb
- api/db/schema.rb
- api/db/views/collection_project_rankings_v01.sql
- api/db/views/project_collection_sort_orders_v01.sql
- api/spec/models/project_collection_spec.rb
> [B] Correct project collection project sorting

- client/src/frontend/components/layout/NoFollow.js
- client/src/frontend/components/layout/__tests__/__snapshots__/NoFollow-test.js.snap
- client/src/frontend/components/project-list/__tests__/__snapshots__/Following-test.js.snap
Provides more descriptive alt-text for screen readers.
Resolves #2191
> [B] Revise alt-text for NoFollow graphic

- client/src/backend/components/list/EntitiesList/Entity/ProjectRow.js
- client/src/backend/containers/project-collection/ManageProjects.js
- client/src/backend/containers/project-collection/__tests__/__snapshots__/ManageProjects-test.js.snap
- client/src/theme/styles/components/global/_buttons.scss
* Renders projects in Manage Projects drawer without links
* Fixes icon size in project cover button
Resolves #2204
> [B] Fix PC Manual Collection bugs

- client/src/backend/components/layout/__tests__/__snapshots__/Header-test.js.snap
- client/src/backend/containers/Backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/frontend/components/layout/__tests__/__snapshots__/Header-test.js.snap
- client/src/frontend/containers/Frontend/__tests__/__snapshots__/Frontend-test.js.snap
- client/src/global/components/navigation/Mobile.js
- client/src/global/components/navigation/Static.js
- client/src/global/components/navigation/mobile-components/UserLinks.js
* Adds `aria-label` attribute to page and user link lists to differentiate
* Improves SR experience for buttons toggling mobile nav menu and submenus by providing SR text and `aria-haspopup` and `aria-expanded` attributes
> [B] Improve header nav accessibility

- api/app/serializers/project_serializer.rb
- client/src/backend/containers/project-collection/__tests__/__snapshots__/ManageProjects-test.js.snap
> [B] Restore hero styles in project serializer

- client/src/frontend/components/project/Hero/Callout/index.js
- client/src/frontend/components/project/Hero/Callout/types/Error.js
- client/src/frontend/components/project/Hero/Callout/types/Read.js
- client/src/frontend/components/project/Hero/Callout/types/TOC.js
- client/src/frontend/components/project/Hero/CalloutList.js
- client/src/frontend/components/project/Hero/index.js
- client/src/theme/styles/components/frontend/project/_action-callout-list.scss
> [B] Prevent CTAs with deleted texts causing exceptions

- client/src/theme/styles/base/_appearance.scss
- client/src/theme/styles/components/backend/list/entity/_entity-row.scss
> [B] Show overflow of project cover placeholders

- client/src/theme/styles/components/backend/list/entity/_entity-list-search.scss
> [B] Fix padding collapse on BE dashboard filters

- client/src/reader/components/notation/viewer/List.js
> [B] Ensure early resource notations are visible

- client/src/reader/components/control-menu/AppearanceMenuBody.js
- client/src/theme/styles/components/reader/_appearance-menu.scss
- client/src/theme/styles/components/reader/_ui-panel-menu.scss
- client/src/theme/styles/components/reader/_visibility-menu.scss
* Replaces font style and color scheme buttons with radio controls.
* Applies WAI-ARIA role "group" to panel sections to group related controls and adds labels.
* Uses `aria-disabled` rather than `disabled` attribute for margin and font size buttons when min or max setting has been reached. This allows button to remain visible to SRs while removing interaction.
Resolves #2251
> [B] Improve a11y of reader appearance panel

- client/src/store/reducers/ui/persistent/reader/typography.js
- client/src/theme/styles/base/_typography.scss
- client/src/theme/styles/base/structure/_index.scss
Adds 2 larger margin size options and 1 larger font size option to reader appearance settings.
Resolves #2253
> [F] Add additional font and margin sizes to reader

- client/src/frontend/components/utility/ConfirmableButton.js
- client/src/global/components/Annotation/Annotation/UserContent/index.js
- client/src/theme/styles/components/global/_confirmable-buttons.scss
- client/src/theme/styles/components/reader/annotation/_detail.scss
This refactors the ConfirmableButton component to improve keyboard navigation:
1. revises the conditional rendering of button elements, which was causing focus to be lost on user interaction
2. moves "confirm" and "cancel" buttons to a nested list to provide hierarchy
3. adds more verbose screen reader text to buttons
4. shifts focus to the appropriate element when user interacts with a button
Resolves #2246
> [B] Improve a11y of ConfirmableButton

- api/app/models/action_callout.rb
- api/app/models/project.rb
- api/app/serializers/action_callout_serializer.rb
- api/app/services/importer/project.rb
- api/clock.rb
- api/spec/models/action_callout_spec.rb
- client/src/frontend/components/project/Hero/Callout/types/Link.js
- client/src/global/components/helper/UserLink.js
- client/src/global/components/helper/index.js
> [B] Improve call-to-action absolute link behavior

- api/app/models/settings.rb
- api/app/serializers/settings_serializer.rb
- client/src/api/resources/settings.js
- client/src/bootstrap.js
- client/src/frontend/components/project-collection/Placeholder.js
- client/src/frontend/components/project-collection/__tests__/__snapshots__/Placeholder-test.js.snap
- client/src/frontend/components/project-list/Placeholder.js
- client/src/frontend/components/project-list/__tests__/__snapshots__/Placeholder-test.js.snap
- client/src/frontend/containers/Home/__tests__/__snapshots__/Home-test.js.snap
- client/src/frontend/containers/Home/index.js
- client/src/frontend/containers/Projects/index.js
- client/src/hoc/authorize/index.js
- client/src/store/middleware/entityStoreMiddleware.js
> [C] Improve project placeholder content

- client/src/global/components/drawer/Wrapper.js
- client/src/global/components/drawer/__tests__/__snapshots__/Wrapper-test.js.snap
- client/src/theme/styles/components/global/_drawer.scss
> [B] Fix drawer close with keyboard

- client/src/frontend/components/content-block/Block/parts/Wrapper.js
> [B] Fix padding between FE project content blocks

- client/src/theme/styles/components/frontend/layout/header/library-header.scss
- client/src/theme/styles/components/frontend/layout/header/press-header.scss
- client/src/theme/styles/components/global/_footer.scss
- client/src/theme/styles/components/global/_user-menu.scss
* Applies consistent background color to dropdowns
* Applies shadow to library header
* Updates focus styles in standalone footer
Issue #2304
> [B] Revisions to standalone project feature

- api/app/models/concerns/collaborative.rb
- api/spec/requests/projects_spec.rb
> [B] Include middle names in collaborative concern

- client/src/theme/styles/components/reader/_appearance-menu.scss
> [B] Fix style issues in reader appearance drawer

- client/src/theme/styles/components/global/header/_user-nav.scss
> [B] Fix alignment regression in library header

- client/package.json
- client/src/global/components/drawer/Wrapper.js
- client/yarn.lock
Implements more robust scroll-lock solution in Drawer.Wrapper using body-scroll-lock library.
Resolves #1506
> [B] Improve scroll-locking in drawers

- client/src/global/components/Annotation/Annotation/UserContent/Meta.js
- client/src/global/components/Annotation/Annotation/UserContent/index.js
- client/src/global/components/Annotation/Annotation/index.js
- client/src/theme/styles/components/global/annotation/_meta.scss
* hide markers in context of reading group list
* truncate long markers
* style links inside of markers
> [B] Revise annotation markers

- client/src/backend/containers/project/__tests__/__snapshots__/New-test.js.snap
- client/src/backend/containers/resource-collection/__tests__/__snapshots__/New-test.js.snap
- client/src/backend/containers/resource/__tests__/__snapshots__/New-test.js.snap
- client/src/backend/containers/settings/subjects/__tests__/__snapshots__/New-test.js.snap
- client/src/backend/containers/stylesheet/__tests__/__snapshots__/Edit-test.js.snap
- client/src/backend/containers/text/__tests__/__snapshots__/Metadata-test.js.snap
- client/src/frontend/components/reading-group/Form/index.js
- client/src/global/components/form/Save.js
- client/src/global/components/form/__tests__/__snapshots__/Save-test.js.snap
- client/src/theme/styles/_variables.scss
- client/src/theme/styles/components/frontend/groups/_page-heading.scss
- client/src/theme/styles/components/global/_buttons.scss
> [B] Improve color contrast for some FE buttons

- client/src/backend/containers/Backend/__tests__/__snapshots__/Backend-test.js.snap
- client/src/global/components/UIPanel/index.js
- client/src/theme/styles/base/_animations.scss
- client/src/theme/styles/components/global/drawer/_drawer.scss
- client/src/theme/styles/components/global/drawer/_overlay.scss
- client/src/theme/styles/components/global/header/_user-nav.scss
- client/src/theme/styles/components/reader/_header-reader.scss
- client/src/theme/styles/components/reader/_ui-panel-menu.scss
> [B] Fix regressions in UIPanel transitions

- api/app/models/text.rb
- api/app/serializers/text_full_serializer.rb
- api/app/uploaders/ingestion_uploader.rb
- client/package.json
- client/src/backend/containers/ingestion/Heading.js
- client/src/backend/containers/text/Wrapper.js
- client/src/theme/styles/components/global/_buttons.scss
> [F] Allow backend users to access ingestion source

- api/app/services/ingestions/compilers/maker.rb
- api/config/locales/services/ingestions/en.yml
- api/spec/services/ingestions/compilers/maker_spec.rb
> [B] Improve handling of unparsable maker names

- client/src/frontend/components/project-collection/Placeholder.js
- client/src/frontend/components/project-collection/__tests__/__snapshots__/Placeholder-test.js.snap
> [B] Fix FE Project Collections placeholder

- .gitignore
- api/app/controllers/concerns/validation.rb
- api/app/models/resource.rb
- api/app/serializers/resource_serializer.rb
- api/app/services/system_upgrades/upgrades/manifold040100.rb
- api/db/migrate/20191025200842_add_pending_sort_title_to_resources.rb
- api/db/schema.rb
- client/script/build-browser-config.js
- client/src/backend/containers/resource/General.js
- client/src/backend/containers/resource/__tests__/__snapshots__/General-test.js.snap
- client/src/frontend/components/event/Tile.js
- client/src/frontend/containers/Home/Projects.js
- client/src/reader/components/return-menu/Button.js
> [B] Improve resource and project sorting

- client/package.json
- client/src/backend/components/project/hero/Builder/Block.js
- client/src/global/components/search/results/Types/Generic/Excerpts.js
- client/src/reader/components/notes/partial/Group.js
- client/src/theme/styles/components/global/_index.scss
- client/src/theme/styles/components/global/_react-collapse.scss
- client/yarn.lock
> [C] Upgrade react-collapse to v5

- client/src/hoc/with-reading-groups/index.js
- client/src/reader/components/Header/__tests__/__snapshots__/Header-test.js.snap
- client/src/reader/components/annotation/__tests__/__snapshots__/Editor-test.js.snap
- client/src/reader/components/control-menu/__tests__/__snapshots__/VisibilityMenuBody-test.js.snap
The reader is wrapped in this HOC, and it only fetches RGs on the
client. Preventing render is a problem, then, because it breaks the
server-side-render of the reader.
Fixes #2453
> [B] Restore SSR of full text in reader

- api/app/serializers/serializer_registry.rb
> [B] Camelize metadata properties for client

- api/app/serializers/v1/project_serializer.rb
- api/spec/api_docs/definitions/resource.rb
- api/spec/api_docs/definitions/resources/project.rb
- api/spec/api_docs/helpers/metadata_handler.rb
- api/spec/requests/api/v1/projects_spec.rb
- api/spec/swagger_helper.rb
Updates the projects documentation generator to use the new internal API
* Add paginated flag on show request
* Move read only attributes to serializer
* Expand on request attributes
> [C] Update Projects API documentation

- api/app/models/concerns/attachments.rb
- api/app/uploaders/concerns/shared_uploader.rb
- api/db/migrate/20191229155846_drop_checksum_fields.rb
- api/db/schema.rb
- api/spec/models/resource_spec.rb
> [B] Ensure attachment checksums are present

- api/config/routes.rb
> [B] Remove extraneous routes

- client/src/theme/styles/components/reader/_text-section.scss
> [B] Restore fallback font to reader

- api/config/manifold.yml
> [B] Allow audio/x-wav mimetype

- client/src/actions/ui/frontendMode.js
- client/src/global/containers/CheckFrontendMode/index.js
- client/src/store/reducers/ui/transitory/frontendMode.js
> [B] Decouple press bar content from standalone mode

- api/app/models/text.rb
> [B] Ensure texts destroy their exports

- api/app/authorizers/project_child_authorizer.rb
> [B] Make project child authorizer more resilient

- api/config/locales/en.yml
- api/spec/api_docs/examples/create.rb
- api/spec/api_docs/examples/destroy.rb
- api/spec/api_docs/examples/index.rb
- api/spec/api_docs/examples/show.rb
- api/spec/api_docs/examples/update.rb
- api/spec/api_docs/helpers/request.rb
- api/spec/requests/api/v1/users_spec.rb
Change made to reflect the changes in 825042cbbf18a688967b18fdc7ee7f284b563a10
> [WIP] Convert rswag 403 tests to 401

- api/spec/api_docs/examples/create.rb
- api/spec/api_docs/examples/destroy.rb
- api/spec/api_docs/examples/index.rb
- api/spec/api_docs/examples/show.rb
- api/spec/api_docs/examples/update.rb
- api/spec/api_docs/helpers/request.rb
- api/spec/requests/api/v1/action_callouts_spec.rb
- api/spec/requests/api/v1/annotations_spec.rb
- api/spec/requests/api/v1/categories_spec.rb
- api/spec/requests/api/v1/comments_spec.rb
- api/spec/requests/api/v1/content_blocks_spec.rb
- api/spec/requests/api/v1/projects_spec.rb
- api/spec/requests/api/v1/resource_collections_spec.rb
- api/spec/requests/api/v1/text_categories_spec.rb
- api/spec/requests/api/v1/users_spec.rb
- api/spec/support/requests/authenticated_request.rb
I documented why I made each change in the commit descriptions, so do look those over for more information on the changes. Feel free to look over all the changes in one go, or take it one commit at a time, but I suggest looking by commits to get a better sense of how the changes relate to each other.
The summary of these changes are that I made some clarification and enhancement changes to how response codes are tested and documented in rswag tests.
* Clarity changes involved the interface for passing information into rswag routes for testing response codes
* Enhancement changes involve expanding on the response codes tested/documented for each CRUD operation, as well as verifying which users can access which resources in the rswag tests.
Apart from adding a couple new 403 and 404 …
> [WIP] Upgrade authorization rswag tests

- api/app/serializers/v1/collection_project_serializer.rb
- api/spec/api_docs/definitions/resources/collection_project.rb
- api/spec/requests/api/v1/collection_project_spec.rb
I'm running into a problem with creating a CollectionProject on a ProjectCollection.
To reproduce the error,  run `rspec -fd spec/requests/api/v1/collection_project_spec.rb` from the `api` folder.
> [WIP] Document CollectionProjects API endpoints

- api/config/initializers/zzz_eager_load_in_dev.rb
Only run eager loading in development if no errors are present.
> [C] Adjust eager loading in development

- client/src/frontend/components/layout/Header/PressHeader.js
- client/src/frontend/components/project-collection/Detail.js
- client/src/frontend/components/project-collection/Summary.js
- client/src/frontend/components/resource-player/Audio.js
- client/src/theme/styles/base/_appearance.scss
- client/src/theme/styles/components/backend/_button-switch.scss
- client/src/theme/styles/components/backend/list/entity/_entity-list.scss
- client/src/theme/styles/components/global/_buttons.scss
- client/src/theme/styles/components/global/_checkboxes.scss
- client/src/theme/styles/components/global/forms/_form-inputs-primary.scss
- client/src/theme/styles/components/global/forms/_list-filter.scss
- client/src/theme/styles/components/reader/control-menus/_appearance.scss
> [B] Fix color regressions

- client/src/theme/styles/components/global/forms/_form-inputs-primary.scss
> [B] Fix Form.Date focus color in FF

- client/src/reader/components/notation/Marker.js
This narrows the conditions under which a click event makes a resource
notation active in the reader (versus linking through to view that
resource). Currently we show two different views for notations: on
smaller devices, the active one is fixed to the bottom of the viewport.
On wider devices, all notations are shown as thumbnails in the margin
of the reader text block. The previous click handler method tested
for whether the user's device had touch support, and assumed that if it
did, then that resource should be activated at the bottom of the
viewport. This conflated device size and touch support, however, and
led to an issue on laptops with touch screens, where the user could see
the active thumbnail present in the margin, but couldn't click on the
notation marker. To solve this, I've …
> [B] Adjust Notation.Marker click behavior

- client/src/theme/styles/components/frontend/layout/header/standalone-header.scss
> [B] Pad bottom of standalone header subtitle

- client/src/backend/components/dialog/Confirm.js
- client/src/backend/components/dialog/Wrapper.js
- client/src/backend/components/dialog/__tests__/Confirm-test.js
- client/src/backend/components/dialog/__tests__/__snapshots__/Confirm-test.js.snap
- client/src/backend/components/dialog/__tests__/__snapshots__/ResetPassword-test.js.snap
- client/src/backend/components/dialog/__tests__/__snapshots__/Wrapper-test.js.snap
Adds `role`, `aria-describedby`, and `aria-labelledby` attributes.
Resolves #2430
> [WIP] Improve a11y of Dialog components

- api/app/controllers/concerns/json_api.rb
- api/app/serializers/v1/helpers/errors.rb
- api/spec/serializers/error_serializer_spec.rb
- api/spec/serializers/helpers/error_helper_spec.rb
> [B] Correct regression with vars in error messages

- api/app/models/concerns/proxied_associations.rb
- api/spec/models/content/texts_block_spec.rb
> [B] Handle destroyed referencables on CBRs

- api/app/controllers/concerns/validation.rb
- api/app/serializers/serializer_registry.rb
- api/spec/api_docs/definitions/resources/text.rb
Commit addresses regression from 88a372
Fixes #2638
> [B] Restore ability to manage text covers

- client/src/frontend/components/content-block/Block/types/Texts.js
> [B] Ensure correct text ordering in text CB

- client/src/backend/components/list/EntitiesList/List/Search.js
> [B] Persist stateful search keyword param in UI

- api/app/models/text.rb
> [B] Delete callout when linked text is destroyed

- client/src/frontend/components/project-list/Filters.js
- client/src/frontend/containers/Projects/index.js
> [B] Exclude standalone projects from projects list

- api/app/serializers/v1/export_target_serializer.rb
- api/app/serializers/v1/project_exportation_serializer.rb
- api/app/services/types/serializer.rb
- api/public/api/static/docs/v1/swagger.json
- api/spec/api_docs/definitions/resources/export_target.rb
- api/spec/api_docs/definitions/resources/project_exportation.rb
- api/spec/requests/api/v1/export_targets_spec.rb
- api/spec/requests/api/v1/project_exportations_spec.rb
Resolves #2620 
While working on this, I noticed that the sign in feature on the swagger API docs interface does not send the right credentials when making a request. I opened an issue for it (#2662). All the tests to generate the docs pass, so I know that the documentation around authorization is correct and it will just be a matter of hooking the log in feature back up to get the swagger API docs interface fully operational.
Please feel free to make suggestions to correct or add to descriptions of routes and attributes.
> [F] Document ProjectExportations and ExportTargets routes

- client/src/theme/styles/components/frontend/resource/_audio-player.scss
Additionally, address regression in audio player width.
Resolves #2586
> [B] Use tabular numbers on audio player

- client/src/frontend/components/resource-player/Video.js
- client/src/frontend/components/resource-preview/__tests__/__snapshots__/Video-test.js.snap
- client/src/frontend/components/resource-slide/__tests__/__snapshots__/SlideVideo-test.js.snap
- client/src/theme/styles/base/_z-stack.scss
- client/src/theme/styles/components/frontend/resource/_audio-player.scss
> [B] Notify user when video playback fails

- client/src/theme/styles/base/_appearance.scss
> [B] Correct FG color in reader resource drawer

- client/src/frontend/components/layout/Header/LibraryHeader.js
> [B] Deliver higher resolution custom logo

- api/app/controllers/api/v1/resource_collections_controller.rb
- api/config/routes.rb
> [C] Cleanup unused routes

- api/app/models/stylesheet.rb
- api/app/services/ingestions/post_processor.rb
- api/spec/models/stylesheet_spec.rb
- api/spec/services/ingestions/ingestor_spec.rb
> [B] Do not modify user styles on reingest

- client/src/frontend/components/project-collection/Summary.js
- client/src/frontend/containers/ProjectCollections/__tests__/__snapshots__/ProjectCollections-test.js.snap
- client/src/frontend/containers/ProjectCollections/index.js
> [B] Address background color conflict

- client/src/frontend/containers/Subscriptions/index.js
- client/src/global/components/preferences/NotificationsForm.js
Fixes #2697
Additionaly, fixes radio regression introduces in radio accessibility refactor.
> [B] Update auth user state when notification changes

- api/app/models/concerns/with_parsed_name.rb
- api/spec/models/entitlement_spec.rb
Mitigates https://github.com/berkmancenter/namae/issues/21
Fixes #2701
> [B] Improve handling of lowercase names

- api/app/decorators/annotation_decorator.rb
- api/app/decorators/project_decorator.rb
- api/app/jobs/notifications/enqueue_annotation_notifications_job.rb
- api/app/jobs/notifications/send_annotation_notification_job.rb
- api/app/jobs/notifications/send_comment_notification_job.rb
- api/app/mailers/notification_mailer.rb
- api/app/models/annotation.rb
- api/app/models/comment.rb
- api/app/models/user.rb
- api/app/services/notifications/fetch_users_for_annotation_notification.rb
- api/app/views/notification_mailer/annotation_notification.html.erb
- api/app/views/notification_mailer/annotation_notification.text.erb
- api/spec/mailers/notifications_spec.rb
- api/spec/mailers/previews/notification_mailer_preview.rb
- api/spec/models/annotation_spec.rb
- api/spec/models/comment_spec.rb
> [B] Notify on new annotations; fix regressions

- client/src/theme/styles/components/global/notification/_notification.scss
> [B] Fix wrapping on login button

- client/src/backend/components/list/EntitiesList/Entity/MakerRow.js
- client/src/backend/containers/project/Collaborators.js
- client/src/backend/containers/text/Collaborators.js
- client/src/global/components/form/Picker/List.js
- client/src/global/components/form/Picker/index.js
- client/src/theme/styles/components/backend/forms/picker/_index.scss
> [B] Restore create and reorder to maker associations

- client/src/global/components/HeadContent/index.js
> [B] Correct incorrect og:image URL

- api/app/services/search/query.rb
- client/src/global/components/search/results/Types/Annotation.js
> [B] Correct annotation link in search results

- api/app/lib/updaters/content_block.rb
- api/app/models/content_block_reference.rb
- api/db/migrate/20200512192527_add_position_to_content_block_references.rb
- api/db/schema.rb
- client/src/backend/components/content-block/TypeForm/types/Resources.js
- client/src/backend/components/content-block/TypeForm/types/Texts.js
- client/src/theme/styles/components/backend/list/entity/_entity-row.scss
- client/src/theme/styles/components/global/drawer/_drawer.scss
> [F] Make content block references sortable

- api/app/models/annotation.rb
> [B] Exclude highlights from notification

- api/app/lib/updaters.rb
- api/config/locales/en.yml
- client/src/global/components/form/Select.js
- client/src/global/containers/form/Form.js
…And allow setting null values in a select input.
> [B] Correct select input behavior

- api/app/services/types/serializer.rb
- api/public/api/static/docs/v1/swagger.json
- api/spec/api_docs/definitions/resource.rb
- api/spec/api_docs/helpers/request.rb
The first commit adds pagination to the responses and the following two commits just clean up the code. I have been documenting which routes are paginated and this connects the pagination parameters to the documentation.
> [F] Add pagination to route response documentation

- api/app/services/search/query.rb
> [B] Handle unterminated quotation marks in search

- api/app/services/ingestions/concerns/file_operations.rb
> [B] Assign permissions to sources during ingestion

- client/src/frontend/components/resourceish/Thumbnail.js
> [B] Ensure resource icon is visible in the reader

- client/package.json
- client/src/theme/styles/base/_typography.scss
- client/src/theme/styles/components/backend/project-collection/_collection-list.scss
> [B] Truncate project collection titles that are too long

- api/app/models/collection_project.rb
- api/app/models/concerns/filterable.rb
- api/app/models/project.rb
- api/spec/factories/project_collection.rb
- api/spec/models/project_spec.rb
- config/elasticsearch/elasticsearch.yml
> [B] Correct project collection pagination

- api/app/models/concerns/collaborative.rb
- api/app/services/formatted_attributes/methods.rb
- api/lib/tasks/cache.rake
> [B] Maintain author name order on frontend

- api/app/services/packaging/bag_it_spec/text_proxy.rb
- api/spec/services/packaging/preservation/export_project_to_bag_it_spec.rb
> [F] Include text metadata in ProjectExports

- client/src/frontend/containers/SignUp/index.js
- client/src/frontend/containers/route-containers.js
- client/src/frontend/routes.js
- client/src/global/components/sign-in-up/Create.js
- client/src/global/components/sign-in-up/Interface.js
> [F] Expose signup form at /signup

- client/src/frontend/components/resource/Hero.js
Resolves #2789, building on e20d91.
> [B] Fix iframe height on detail view

- api/app/models/annotation.rb
- api/spec/models/annotation_spec.rb
> [B] Exclude resources when hiding public annotations

- api/app/services/external_auth/provisioners/user.rb
- api/spec/services/external_auth/provisioners/user_spec.rb
> [B] Set name for users provisioned from Twitter

- client/src/backend/components/dialog/Confirm.js
- client/src/backend/components/dialog/__tests__/Confirm-test.js
> [B] Prevent accidental submit of confirm dialog

- client/src/global/components/Annotation/Editor/index.js
- client/src/hoc/with-reading-groups/index.js
- client/src/reader/components/notes/FilteredList.js
> [B] Restore annotation editing in reading groups

- api/app/models/resource.rb
- api/spec/rails_helper.rb
- api/spec/requests/api/v1/search_results_spec.rb
> [B] Include tags when indexing resources

- api/app/controllers/api/v1/project_collections_controller.rb
> [B] Authorize ProjectCollections#show requests

- client/src/global/components/Annotation/Annotation/UserContent/index.js
> [F] Allow fetching annotation comments when absent

- api/app/serializers/v1/setting_serializer.rb
- client/src/frontend/components/project/AccessDenied.js
> [B] Fall back to global restricted access text

- client/src/global/components/form/MaskedTextInput.js
> [B] Improve hash tag regex mask

- api/app/services/notifications/fetch_users_for_annotation_notification.rb
- api/spec/factories/annotations.rb
- api/spec/services/notifications/fetch_users_for_annotation_notification_spec.rb
> [C] Don't send notifications for private annotations

- client/src/theme/styles/components/frontend/layout/_entity-section-wrapper.scss
> [C] Enable reverse italics for RA body text

- api/app/jobs/project_exports/prune_job.rb
- api/app/services/project_exports/prune.rb
- api/spec/jobs/project_exports/prune_job_spec.rb
- api/spec/services/project_exports/prune_spec.rb
- api/zhong.rb
> [C] Add project export expiration

- api/db/migrate/20201207011646_update_text_summaries_to_version_5.rb
- api/db/migrate/20201207011717_update_reading_group_membership_counts_to_version_2.rb
- api/db/migrate/20201207011750_update_reading_group_counts_to_version_2.rb
- api/db/schema.rb
- api/db/views/reading_group_counts_v02.sql
- api/db/views/reading_group_membership_counts_v02.sql
- api/db/views/text_summaries_v05.sql
> [C] Exclude orphaned annotations from counts

- api/app/models/content/resources_block.rb
- api/app/serializers/v1/content/resources_block_serializer.rb
- client/src/backend/components/content-block/TypeForm/types/Resources.js
- client/src/frontend/components/content-block/Block/types/Resources.js
> [F] Configure Resource Block title and description

- api/app/models/text.rb
- api/app/models/text_summary.rb
- api/app/serializers/v1/text_serializer.rb
- client/src/frontend/components/project/Hero/Callout/types/TOC.js
> [B] Properly link to TOC landmark when available

- api/app/controllers/api/v1/text_sections/relationships/annotations_controller.rb
- api/app/controllers/application_controller.rb
- api/app/services/html_nodes/node.rb
- api/app/services/testing/generate_random_annotations.rb
- client/package.json
- client/src/api/resources/annotations.js
- client/src/reader/containers/Section/index.js
- client/src/store/middleware/entityStoreMiddleware.js
- client/src/store/reducers/entityStore.js
- client/yarn.lock
> [F] Enforce annotation pagination

- api/app/controllers/concerns/api/v1/records_analytics.rb
- api/app/models/concerns/metadata.rb
- api/spec/support/shared_examples/formatted_attributes.rb
- client/src/backend/components/analytics/composed/Followed.js
- client/src/backend/containers/settings/Theme.js
- client/src/config/app/locale.js
- client/src/global/components/Footers/Parts/NavigationLink.js
- client/src/global/components/Footers/Parts/helpers/links.js
- client/src/global/components/form/AttributeMap/Attribute.js
- client/src/global/components/search/results/Types/TextSection.js
- client/src/global/containers/Manifold/index.js
> [WIP] V6 small fixes

- api/db/migrate/20210413160540_add_fa_cache_to_content_blocks.rb
- api/db/schema.rb
- api/spec/models/content/markdown_block_spec.rb
- api/spec/models/content/resources_block_spec.rb
- api/spec/models/content/texts_block_spec.rb
> [B] Add fa_cache to content blocks

- api/app/models/annotation.rb
- api/app/models/application_record.rb
- api/app/models/concerns/search_indexable.rb
- api/app/models/event.rb
- api/app/models/maker.rb
- api/app/models/project.rb
- api/app/models/resource.rb
- api/app/models/resource_collection.rb
- api/app/models/subject.rb
- api/app/models/tag.rb
- api/app/models/text.rb
- api/app/models/text_section.rb
- api/app/models/user.rb
- api/app/services/system_upgrades/upgrades/manifold060000.rb
> [B] Resolve tax indexing regression

- client/src/backend/components/project-collection/form/Fields.js
- client/src/theme/styles/components/global/forms/_form-inputs-secondary.scss
> [B] Fix project collection form spacing

- client/src/helpers/Html.js
- client/src/theme/print.js
- client/src/theme/styles/_print.scss
- client/webpack/config/browser-base.config.js
> [F] Add basic reader print styles

- api/app/services/ingestions/converters/html.rb
- api/app/services/testing/ingest_google_doc.rb
> [C] Remove Google URL redirection

- api/app/models/collaborator.rb
- api/app/models/concerns/collaborative.rb
- api/app/models/maker.rb
- api/app/models/project.rb
- api/app/models/text.rb
- api/app/services/collaborators/calculate_fingerprint.rb
- api/app/services/makers/calculate_fingerprint.rb
- api/app/services/packaging/bag_it_spec/compilation.rb
- api/app/services/packaging/bag_it_spec/context.rb
- api/app/services/packaging/bag_it_spec/entries/attachment.rb
- api/app/services/packaging/bag_it_spec/entries/builder.rb
- api/app/services/packaging/bag_it_spec/text_proxy.rb
- api/app/services/packaging/preservation/export_project_metadata.rb
- api/app/services/packaging/preservation/export_project_to_bag_it.rb
- api/app/services/projects/calculate_fingerprint.rb
* Bump BagIt spec Compilation version
Resolves #3017
> [C] Include collaborator metadata with exports

- client/src/backend/components/project/hero/Builder/forms/Social.js
- client/yarn.lock
> [B] Remove Hashtag mask

- client/src/backend/components/layout/ViewHeader.js
> [B] Correct ViewHeader rendering when count is 0

- client/src/reader/components/section/helpers/filter-annotations.js
> [B] Improve reader annotation visibility UX

- client/src/backend/components/analytics/composed/Followed.js
- client/src/backend/components/analytics/composed/ReturnVisits.js
> [B] Round analytics values to prevent overflow

- api/app/serializers/v1/version_serializer.rb
> [B] Improve missing log association handling

- api/app/services/ingestions/converters/ms_word.rb
- api/app/services/ingestions/strategy/document/inspector.rb
- api/spec/services/ingestions/strategies/document_spec.rb
> [B] Set correct text, section titles in doc ingest

- client/src/backend/components/layout/Header.js
- client/src/frontend/components/layout/Header/LibraryHeader.js
- client/src/global/components/atomic/HeaderLogo/index.js
- client/src/global/components/atomic/HeaderLogo/styles.js
- client/src/global/components/atomic/index.js
- client/src/theme/styles/base/resets.js
- client/src/theme/styles/components/frontend/layout/entitySectionWrapper.js
- client/src/theme/styles/components/global/buttons.js
- client/src/theme/styles/components/global/footer.js
- client/src/theme/styles/components/global/header/index.js
- client/src/theme/styles/components/global/header/logo.js
- client/src/theme/styles/components/global/overlay/header.js
- client/src/theme/styles/mixins/common.js
- client/src/theme/styles/mixins/layout.js
- client/src/theme/styles/mixins/mixed.js
Minor style fixes and refactors for visual regressions during styles migration
> FE  + reader style regressions

- client/src/global/components/atomic/EntityThumbnail/EntityMetadata/styles.js
- client/src/global/components/atomic/EntityThumbnail/__stories__/EntityThumbnail.stories.js
- client/src/global/components/atomic/EntityThumbnail/styles.js
- client/src/global/components/composed/ThumbnailGrid/__stories__/ThumbnailGrid.stories.js
- client/src/global/components/composed/ThumbnailGrid/styles.js
> [B] Fix EntityThumbnail and EntityGrid styles

- client/src/reader/containers/notation/resource-collection/Detail.js
> [B] Prevent scroll when closing reader RC modal

- api/app/models/collection_project_ranking.rb
- api/app/models/project.rb
- api/spec/models/project_spec.rb
> [B] Resolve duplication of collected projects

- api/app/models/text.rb
> [B] Correct text scope

- client/src/reader/components/annotation/popup/parts/Menu/index.js
- client/src/theme/styles/components/reader/annotations/popup.js
- client/src/theme/styles/utility/appearance.js
- [B] Fix CSS selector
- [B] Fix Annotation Popup tail styles
> [B] Fix minor CSS issues in Annotation Popup

- api/app/controllers/concerns/validation.rb
- api/app/models/journal.rb
- api/app/models/journal_issue.rb
- api/app/models/journal_volume.rb
- api/app/serializers/v1/journal_serializer.rb
- client/src/api/resources/journalVolumes.js
- client/src/api/resources/journals.js
- client/src/frontend/components/journal/IssueCount/index.js
- client/src/frontend/components/journal/IssueList/index.js
- client/src/frontend/components/journal/IssueList/styles.js
- client/src/frontend/components/journal/JournalIssueCount/index.js
- client/src/frontend/components/journal/VolumeList/index.js
- client/src/frontend/components/journal/VolumesForJournalLink/index.js
- client/src/frontend/components/journal/VolumesForJournalLink/styles.js
- client/src/frontend/components/journal/index.js
- client/src/frontend/containers/JournalDetail/index.js
- client/src/frontend/containers/JournalWrapper/index.js
- Resolves MNFLD-135
- Resolves MNFLD-136
> [C] Refactor journal detail components, fetching

- client/src/frontend/containers/IssuesList/index.js
- client/src/frontend/containers/JournalsList/index.js
- client/src/frontend/containers/ProjectCollections/__tests__/__snapshots__/ProjectCollections-test.js.snap
- client/src/frontend/containers/ProjectCollections/index.js
- client/src/frontend/containers/Projects/index.js
- client/src/global/components/composed/EntityCollectionPlaceholder/index.js
- client/src/global/components/composed/EntityCollectionPlaceholder/patterns/Issues.js
- client/src/global/components/composed/EntityCollectionPlaceholder/patterns/Journals.js
- client/src/global/components/composed/EntityCollectionPlaceholder/patterns/ReadingGroups.js
- [C] Add useCurrentUser hook to placeholder
- [F] Finalize journals placeholder
- [F] Create issues placeholder
- [B] Always show CollectionNavigation in FE index routes
> [F] Finalize journal/issue placeholders

- client/src/frontend/components/composed/EntityCollection/patterns/Issues.js
- client/src/frontend/containers/JournalIssuesList/index.js
- client/src/global/components/atomic/EntityThumbnail/EntityMetadata/Content/index.js
- client/src/global/components/atomic/EntityThumbnail/EntityMetadata/Content/styles.js
- client/src/global/components/atomic/EntityThumbnail/EntityMetadata/Wrapper.js
- client/src/global/components/atomic/EntityThumbnail/index.js
Resolves:
- MNFLD-243
- MNFLD-236
> [F] Render issue thumbnails contextually

- client/src/frontend/components/composed/CollectionNavigation/Link/index.js
- client/src/frontend/components/composed/CollectionNavigation/Link/styles.js
- client/src/frontend/components/composed/CollectionNavigation/index.js
- client/src/frontend/components/composed/CollectionNavigation/styles.js
- client/src/frontend/components/composed/EntityHero/patterns/ProjectHero.js
- client/src/frontend/components/project/Detail.js
- client/src/frontend/containers/Home/index.js
- client/src/frontend/containers/IssuesList/index.js
- client/src/frontend/containers/JournalsList/index.js
- client/src/frontend/containers/MyAnnotations/index.js
- client/src/frontend/containers/MyStarred/index.js
- client/src/frontend/containers/ProjectCollectionDetail/__tests__/__snapshots__/ProjectCollectionDetail-test.js.snap
- client/src/frontend/containers/ProjectCollectionDetail/index.js
- client/src/frontend/containers/ProjectCollections/__tests__/__snapshots__/ProjectCollections-test.js.snap
- client/src/frontend/containers/ProjectCollections/index.js
- client/src/frontend/containers/Projects/index.js
- client/src/global/components/composed/EntityCollectionPlaceholder/patterns/MyStarred/index.js
- [F] Build new CollectionsNavigation
- [C] Fix incorrect propType
> [F] Build new CollectionsNavigation

- client/src/frontend/components/collecting/Toggle/index.js
- client/src/frontend/containers/IssuesList/index.js
- [B] Hide collecting toggle for journals & issues
- [B] Fix issues index pagination
> [B] Hide collecting toggle for journals & issues

- client/src/frontend/components/composed/EntityCollection/EntityCollection.js
- client/src/frontend/containers/IssuesList/index.js
- client/src/frontend/containers/Projects/index.js
- client/src/theme/styles/utility/layout.js
- [B] Push CollectionNavigation to bottom
- [B] Fix conditions for showing issues placeholder
> [B] Fix conditions for showing issues placeholder

- client/src/frontend/components/collecting/Dialog/Checkbox/styles.js
Prevents focus style from appearing when using pointer
> [B] Fix collecting dialog focus style

- client/src/frontend/components/reading-group/headings/Group/GroupSummaryBox/index.js
Initially introduced in 3e54e32
> [B] Fix regressions in RG counts

- client/src/global/components/Annotation/Editor/index.js
- client/src/theme/styles/components/global/annotation/editor.js
- [B] Fix annotation editor bugs outside of reader context
- [B] Fix annotation editor button style
> [B] Fix annotation editor bugs outside of reader context

- client/src/frontend/components/content-block-list/List.js
- client/src/frontend/components/content-block/Block/index.js
- client/src/frontend/components/content-block/Block/styles.js
- client/src/frontend/components/journal/VolumeDetail/index.js
- client/src/frontend/components/journal/VolumeDetail/styles.js
- client/src/frontend/components/toc/List/styles.js
Conditionally adds border between issues to visually separate them
> [B] Improve VolumeDetail presentation

- client/src/config/app/locale/en/en.json
- client/src/frontend/components/collecting/SearchDialog/index.js
- client/src/frontend/components/collecting/reading-group/static/CollectionPlaceholder.js
- client/src/frontend/components/composed/EntityCollection/patterns/JournalSummaryEmpty.js
- client/src/frontend/components/composed/EntityCollection/patterns/MyStarred.js
- client/src/frontend/components/content-block/parts/Warning/patterns/Incomplete/errors.js
- client/src/frontend/components/content-block/parts/Warning/patterns/Incomplete/index.js
- client/src/frontend/components/event/AllLink/index.js
- client/src/frontend/components/event/Tile/index.js
- client/src/frontend/components/event/__tests__/__snapshots__/AllLink-test.js.snap
- client/src/frontend/components/journal/IssueCount/index.js
- client/src/frontend/components/journal/IssueList/index.js
- client/src/frontend/components/journal/JournalIssueCount/index.js
- client/src/frontend/components/journal/Metadata/index.js
- client/src/frontend/components/journal/VolumeDetail/index.js
- client/src/frontend/components/journal/VolumeList/index.js
- client/src/frontend/containers/JournalDetail/index.js
- `frontend/components/journal`
- `frontend/components/content-block`
- `frontend/components/event`
> [F] Additional frontend localization

- client/src/config/app/locale/en/en.json
- client/src/frontend/components/resource-collection/__tests__/__snapshots__/Cover-test.js.snap
- client/src/frontend/components/resource-list/__tests__/__snapshots__/Slideshow-test.js.snap
- client/src/frontend/components/resource-slide/__tests__/__snapshots__/Caption-test.js.snap
- client/src/frontend/components/resource/__tests__/__snapshots__/Detail-test.js.snap
- client/src/frontend/components/resource/__tests__/__snapshots__/Link-test.js.snap
- client/src/frontend/components/resource/__tests__/__snapshots__/Title-test.js.snap
- client/src/frontend/components/resourceish/__tests__/__snapshots__/Thumbnail-test.js.snap
- client/src/frontend/components/text/__tests__/__snapshots__/Bibliographic-test.js.snap
- client/src/frontend/components/text/__tests__/__snapshots__/Counts-test.js.snap
- client/src/frontend/components/utility/__tests__/__snapshots__/Toggle-test.js.snap
- client/src/frontend/containers/Contact/index.js
- client/src/frontend/containers/EventList/__tests__/EventList-test.js
- client/src/frontend/containers/EventList/__tests__/__snapshots__/EventList-test.js.snap
- client/src/frontend/containers/EventList/index.js
- client/src/frontend/containers/IssuesList/index.js
- client/src/frontend/containers/JournalDetail/index.js
- client/src/frontend/containers/JournalIssuesList/index.js
- client/src/frontend/containers/JournalVolumesList/index.js
- client/src/frontend/containers/JournalsList/index.js
- client/src/hooks/useSetLocation/index.js
> [F] Localize frontend containers

- client/src/frontend/containers/JournalDetail/index.js
- client/src/frontend/containers/JournalIssuesList/index.js
- client/src/frontend/containers/JournalVolumesList/index.js
- client/src/frontend/containers/ProjectWrapper/helpers.js
- client/src/frontend/containers/ProjectWrapper/index.js
- client/src/frontend/containers/VolumeDetail/index.js
> [B] Remove all journals breadcrumb when library views are disabled

- client/src/store/middleware/entityStoreMiddleware.js
> [B] Address “refresh” API option failure

- client/src/helpers/colorSchemeGenerator.js
- client/src/theme/styles/components/reader/annotations/menuItem.js
- client/src/theme/styles/components/reader/annotations/popup.js
- client/src/theme/styles/utility/appearance.js
> [B] Fix misnamed CSS color vars

- client/src/frontend/containers/ResourceDetail/index.js
Per Slack conversation re: #3346
> [B] Update resource breadcrumb links

- api/app/models/journal_issue.rb
- api/app/models/project.rb
> [B] Ensure project is deleted alongside issue

- client/src/backend/containers/action-callout/Form.js
> [B] Hide unused journal CTA types

- api/app/controllers/api/v1/journals/relationships/journal_issues_controller.rb
- api/app/controllers/api/v1/journals/relationships/journal_volumes_controller.rb
- api/app/controllers/concerns/validation.rb
- api/app/models/journal.rb
- api/app/models/journal_issue.rb
- client/src/backend/containers/dashboards/Admin.js
- client/src/backend/containers/journal/Issues.js
- client/src/backend/containers/journal/Wrapper.js
- client/src/backend/containers/journals/List.js
- client/src/helpers/router/navigation.js
> [B] Grant editors access to updateable issues

- api/app/controllers/api/v1/journals/relationships/journal_issues_controller.rb
- api/app/services/journal_issues/create.rb
> [B] Correctly structure issue create errors

- client/src/config/app/locale/en-US/json/messages.json
- client/src/frontend/components/reading-group/headings/Group/ChildNav.js
- client/src/frontend/components/reading-group/headings/Group/index.js
- client/src/frontend/components/reading-group/headings/parts/Title/index.js
- client/src/frontend/components/reading-group/headings/parts/Title/styles.js
- client/src/frontend/containers/ReadingGroup/Members/Wrapper.js
- client/src/frontend/containers/ReadingGroup/index.js
> [B] Improve admin reading group user experience

- client/src/frontend/components/resource-player/Iframe/styles.js
@dananjohnson just asking for your 👀 on this since we're so close to v7. It's a small change. Thanks!
> [B] Fix rendering of interactive resources

- api/app/controllers/api/v1/me/relationships/annotations_controller.rb
- api/app/models/annotation.rb
- api/app/models/user.rb
> [B] Exclude orphaned annotations from lists

- client/src/theme/styles/base/appearance.js
- client/src/theme/styles/components/backend/listEntity/entityRow.js
- client/src/theme/styles/components/global/forms/formInputsPrimary.js
- [B] Hide focus ring on main element
- [B] Fix entity-row focus style
- [B] Receive Form.Switch click on input directly
> [B] Receive Form.Switch click on input directly

- client/src/backend/containers/resource-import/New.js
> [B] Remove notification when importing resources

- client/src/frontend/components/entity/Collection/EntityCollection.js
- client/src/frontend/components/resource-list/Cards/styles.js
- client/src/frontend/containers/IssuesList/index.js
- client/src/frontend/containers/JournalIssuesList/index.js
- client/src/frontend/containers/MyAnnotations/index.js
- client/src/frontend/containers/MyReadingGroups/List.js
- client/src/frontend/containers/ProjectCollectionDetail/index.js
- client/src/frontend/containers/ProjectCollections/index.js
- client/src/frontend/containers/ProjectResources/index.js
- client/src/frontend/containers/Projects/index.js
- client/src/frontend/containers/PublicReadingGroups/List.js
- client/src/frontend/containers/ReadingGroup/Annotations.js
- client/src/global/components/drawer/Wrapper.js
- client/src/global/components/table/index.js
- [B] Prevent default on some pagination links
- [B] Fix resources layout in FF
- [B] Deactivate focus trap only if close callback exists
- [B] Restore EntityCollection's UtilityComponent
> [B] Misc bug fixes

- client/src/global/components/utility/Pagination/hooks/usePagination.js
* Add missing final return statement from hook for when earlier
conditions aren't met
* Refine logic for when to render ellipses to address edge cases
> [B] Fix pagination rendering logic

- client/src/config/app/locale/en-US/json/actions.json
- client/src/frontend/components/reading-group/tables/Groups/actions/Join.js
- client/src/frontend/components/reading-group/tables/Groups/actions/Leave.js
- client/src/frontend/components/reading-group/tables/Groups/actions/index.js
- client/src/frontend/components/reading-group/tables/Groups/index.js
Resolves:
- MNFLD-404
- MNFLD-406
> [B] Reading group fixes

- client/src/reader/containers/ReaderFullNotes/index.js
> [B] Update reader notes pane pagination target

- client/src/config/app/locale/en-US/json/utility.json
- client/src/theme/styles/components/backend/project-collection/iconPicker.js
> [B] Icon selector + i18n fixes

- client/src/backend/containers/project-collection/Wrapper.js
- client/src/theme/styles/components/backend/project-collection/collectionList.js
- client/src/theme/styles/components/reader/controlMenus/visibility.js
Also resolves:
- MNFLD-442
- #3487, #3489
> [B] Allow scroll in reader menu + project collections list

- api/app/lib/updaters/text_section.rb
- api/app/models/text_section.rb
- api/app/serializers/v1/text_section_serializer.rb
- api/app/services/ingestions/post_processors/text_section_body.rb
- api/app/services/system_upgrades/upgrades/manifold080000.rb
- api/db/migrate/20230125004558_add_has_mathml_to_text_section.rb
- api/db/schema.rb
- api/spec/models/text_section_spec.rb
Adds callbacks for updating `body_json` and calculating `has_mathml` when section body is changed.
> [F] Handle text section body updates

- client/src/config/app/locale/en-US/json/shared/errors.json
- client/src/frontend/components/privacy/AccountData/DeleteConfirm/index.js
- client/src/frontend/components/privacy/AccountData/index.js
- client/src/frontend/components/privacy/CookiesForm/index.js
- client/src/global/components/CookiesBanner/AnonymousUser.js
- client/src/global/components/CookiesBanner/CurrentUser.js
- client/src/global/components/CookiesBanner/NarrowBanner.js
- client/src/global/components/CookiesBanner/styles.js
- client/src/global/components/form/BaseInput/index.js
- client/src/global/components/sign-in-up/CreateUserForm/CreateFormFields/index.js
- Adds error states for cookies banner and account deletion
- Fixes create account form so first name and last name errors are visible
- Hides download account data UI
> [F] GDPR UI updates

- client/src/reader/components/Header/__tests__/__snapshots__/Header-test.js.snap
- client/src/reader/components/Header/index.js
> [B] Include missing prop

- client/src/reader/components/notation/viewer/Link.js
- client/src/reader/components/notation/viewer/List.js
- client/src/reader/containers/annotation/Annotatable.js
- client/src/reader/containers/annotation/annotatable-components/NotationViewer.js
> [B] Replace id with slug in resource thumbnail URL

- api/app/controllers/concerns/validation.rb
- api/app/models/text.rb
- api/app/serializers/v1/stylesheet_serializer.rb
- api/app/services/ingestions/compilers/stylesheet.rb
- api/app/services/ingestions/pre_processors/inject_global_styles.rb
- api/db/migrate/20230313215126_add_applies_to_all_to_stylesheets.rb
- api/db/schema.rb
- client/src/backend/containers/stylesheet/Edit.js
- client/src/backend/containers/stylesheet/SectionFields.js
- client/src/backend/containers/stylesheet/styles.js
- client/src/config/app/locale/en-US/json/backend/texts.json
- client/src/global/components/form/Switch/index.js
- client/src/reader/components/Header/__tests__/__snapshots__/Header-test.js.snap
- client/src/reader/components/Header/index.js
- client/src/reader/containers/Section/index.js
Adds an applies to all sections property on stylesheets and attaches a global stylesheet when a text is created via the api. Updates admin and the reader for this new stylesheet property.
> [F] Update global stylesheet implementation

- client/package.json
- client/src/backend/containers/makers/Edit.js
- client/src/backend/containers/makers/List.js
- client/src/backend/containers/settings/Integrations.js
- client/src/backend/containers/users/Edit.js
- client/src/backend/containers/users/List.js
- client/src/config/app/locale/en-US/json/settings.json
- client/src/frontend/components/entity/Collection/patterns/ReaderFullNotes.js
- client/src/global/components/Annotation/Annotation/index.js
- client/src/global/components/Annotation/List/GroupedBySection.js
- client/src/global/components/search/results/Types/Generic/index.js
- client/src/global/components/search/results/Types/Generic/styles.js
- client/src/global/containers/Manifold/index.js
- client/src/hoc/analytics/hooks/useGoogleAnalytics.js
- client/src/reader/components/notation/viewer/Link.js
- client/src/reader/components/notation/viewer/List.js
- client/src/reader/containers/ReaderFullNotes/index.js
- client/src/reader/containers/annotation/Annotatable.js
- client/src/reader/containers/annotation/annotatable-components/NotationViewer.js
- client/src/store/reducers/entityStore.js
- client/yarn.lock
Also, includes a number of bug fixes that can go out with v7.1.
> [F] GA4 support for v7.1

- client/src/backend/components/authoring/TOCList/List.js
- client/src/backend/components/authoring/TOCList/Loader.js
- client/src/backend/components/authoring/TOCList/TOCEntry.js
- client/src/backend/components/authoring/TOCList/styles.js
- client/yarn.lock
> [F][B] TOC Improvements

- api/app/models/reading_group.rb
- client/src/backend/components/analytics/composed/Annotations.js
- client/src/frontend/containers/MyReadingGroups/List.js
- client/src/frontend/containers/PublicReadingGroups/List.js
- client/src/hooks/api/useFetch/index.js
- client/src/reader/containers/Reader/index.js
- client/src/reader/containers/ReaderFullNotes/index.js
- client/src/reader/containers/ReaderNotes/index.js
Also resolves:
- PROJ-696
- MNFLD-557
> [B] Ensure archived RGs are shown/hidden correctly

- client/src/global/components/form/ContentEditor/components/Editor.js
- client/src/reader/containers/Section/index.js
- client/src/theme/styles/base/fonts.js
- client/src/theme/styles/globalStyles.js
Resolves MNFLD-544; also, updates `font-display` to `swap`
> [F] Add css layers

- client/src/backend/containers/Backend/index.js
- client/src/backend/containers/Records/index.js
- client/src/backend/containers/journal/Wrapper.js
- client/src/backend/containers/pages/Detail.js
- client/src/backend/containers/project/Wrapper.js
- client/src/backend/containers/projects/Wrapper.js
- client/src/backend/containers/resource-collection/Wrapper.js
- client/src/backend/containers/resource/Wrapper.js
- client/src/backend/containers/settings/Wrapper.js
- client/src/backend/containers/text/Wrapper.js
- client/src/frontend/containers/JournalWrapper/index.js
- client/src/frontend/containers/JournalsWrapper/index.js
- client/src/frontend/containers/ProjectWrapper/index.js
- client/src/frontend/containers/ProjectsWrapper/index.js
- client/src/global/components/navigation/Primary.js
- client/src/global/components/navigation/helpers.js
- client/src/helpers/router/RedirectToFirstMatch.js
- client/src/hooks/index.js
- client/src/hooks/useRedirectToFirstMatch/index.js
- client/src/hooks/useShowJournalsActive/index.js
Resolves: https://github.com/ManifoldScholar/manifold/discussions/3440
> [F] Link to entity when entering/exiting admin mode

- client/src/reader/components/annotation/popup/menus/FollowLink.js
- client/src/reader/components/section/body-nodes/nodes/Text.js
- client/src/reader/containers/annotation/Annotatable.js
- client/src/reader/containers/annotation/annotatable-components/CaptureClick.js
- client/src/reader/containers/annotation/annotatable-components/Popup/LinkMenu.js
- client/src/theme/styles/components/reader/annotations/marker.js
> [F] Render annotations as links

- api/app/controllers/concerns/validation.rb
- api/app/models/annotation.rb
- client/src/frontend/containers/ReadingGroup/Annotations.js
- client/src/global/components/list/Filters/types/index.js
- client/src/global/components/list/Filters/types/sortChron.js
> [F] Allow RG annotations to be sorted by date

- api/app/models/annotation_node.rb
- api/app/models/text_section_node.rb
- api/app/operations/text_sections/correct_intermediate_nodes.rb
- api/app/operations/text_sections/extrapolate_nodes.rb
- api/app/operations/text_sections/introspect_nodes.rb
- api/db/migrate/20230921024546_update_annotation_nodes_to_version_3.rb
- api/db/structure.sql
- api/db/views/annotation_nodes_v03.sql
- client/src/global/components/Annotation/Annotation/TextContent/FromNodes/helpers.js
> [B] Adjust annotation nodes

- api/app/models/concerns/sluggable.rb
- api/app/models/text_section.rb
- api/config/initializers/friendly_id.rb
* Removes index, images; adds slug candidates for text section
> [B] Ensure FriendlyId doesn't cause ingestion to fail silently

- api/app/services/serializer/html.rb
- client/src/backend/components/authoring/AddEditAssetForm/index.js
- client/src/backend/components/authoring/SectionsList/SectionListItem.js
- client/src/backend/components/list/EntitiesList/Entity/AssetRow/index.js
- client/src/config/app/locale/en-US/json/backend/editor.json
- client/src/global/components/form/ContentEditor/components/controls/ToolbarRTE.js
- client/src/global/components/form/ContentEditor/components/controls/buttons/insert/LinkForm.js
- client/src/global/components/form/ContentEditor/utils/elements.js
Also resolves:
- MNFLD-849
- MNFLD-854
- MNFLD-851
- MNFLD-856
> [B] Various fixes

- .github/actions/setup-elasticsearch/action.yml
- .github/actions/setup-node/action.yml
- .github/actions/setup-ruby/action.yml
- .github/workflows/continuous_integration.yml
- api/.rubocop.yml
- api/app/models/concerns/filterable.rb
- api/app/models/project.rb
- api/app/operations/filtering/apply.rb
- api/app/operations/filtering/find_param_scope.rb
- api/app/operations/filtering/maybe_scope_by_param.rb
- api/app/services/filtering/applicator.rb
- api/app/services/filtering/types.rb
- api/app/services/search/query.rb
- api/spec/requests/api/v1/search_results_spec.rb
- api/spec/requests/subjects_spec.rb
- api/spec/services/search/query_spec.rb
- api/spec/support/contexts/elasticsearch.rb
* Improve Filterable concern
* Improve Github Actions to always test elasticsearch, use composite actions
> [B] Fix Scoped Search

- client/src/global/components/form/ContentEditor/components/controls/buttons/IframeButton.js
- client/src/global/components/form/ContentEditor/components/renderers/Element.js
- client/src/global/components/form/ContentEditor/components/renderers/Image.js
- client/src/global/components/form/ContentEditor/plugins/withHtmlAwareBreaks.js
- client/src/global/components/form/ContentEditor/plugins/withVoids.js
- client/src/global/components/form/ContentEditor/serializers/htmlToSlate/serializer.js
- client/src/global/components/form/ContentEditor/utils/elements.js
- client/src/global/components/form/ContentEditor/utils/slate/transforms/iframes.js
- client/src/global/components/form/ContentEditor/utils/slate/transforms/textBlocks.js
- client/src/reader/components/section/body-nodes/nodes/Link.js
- client/src/reader/components/section/body-nodes/nodes/Video.js
- client/src/reader/components/section/body-nodes/nodes/index.js
- client/src/theme/styles/components/reader/responsiveIframe.js
Also, adjusts how classes are applied to new list items and fixes paragraph insert after RTE voids.
> [B][E] Improve asset handling in RTE

- api/app/enums/source_node_kind.rb
- api/app/services/html_nodes/node.rb
- api/lib/patches/better_enums.rb
- api/spec/factories/text_section.rb
- api/spec/services/packaging/epub_v3/compile_node_to_xhtml_spec.rb
- api/spec/services/packaging/epub_v3/text_section_compilation/pipeline_spec.rb
> [B] Handle empty text sections when generating EPUB

- api/app/models/annotation.rb
* `eager_load` is trying to join records when we just want lazy loads
> [B] Correct filtering eager loads for annotations

- .github/actions/setup-ruby/action.yml
- api/app/authorizers/application_authorizer.rb
- api/app/authorizers/user_authorizer.rb
- api/app/controllers/api/v1/bulk_deletions_controller.rb
- api/app/enums/user_classification.rb
- api/app/models/annotation.rb
- api/app/models/concerns/soft_deletable.rb
- api/app/models/favorite.rb
- api/app/models/reading_group.rb
- api/app/models/user.rb
- api/app/operations/bulk_deletions/handle_request.rb
- api/app/operations/users/prune_attached_records.rb
- api/app/services/bulk_deletions/request_handler.rb
- api/app/services/bulk_deletions/types.rb
- api/app/services/users/attached_records_pruner.rb
- api/app/services/users/reading_group_count.rb
- api/app/services/users/types.rb
- api/config/initializers/authority.rb
- api/config/locales/en.yml
- api/config/routes.rb
- api/db/migrate/20241210200353_add_more_soft_deletable_records.rb
- api/db/structure.sql
- api/spec/requests/api/v1/bulk_deletions_spec.rb
* Make annotations, reading groups, and users soft-deletable
* Add handling for pruning records attached to users when performing a soft-delete
Resolves MNFLD-945
> [F] Add bulk deletions API

- client/src/config/app/locale/en-US/json/shared/actions.json
- client/src/frontend/components/entity/Collection/patterns/GroupAnnotations.js
- client/src/frontend/containers/ReadingGroup/Annotations.js
- client/src/global/components/Annotation/Annotation/TextAnnotation/index.js
- client/src/global/components/Annotation/Annotation/UserContent/BlockToggle.js
- client/src/global/components/Annotation/Annotation/UserContent/index.js
- client/src/global/components/Annotation/List/Default.js
- client/src/global/containers/comment/Editor/index.js
- client/src/global/containers/comment/Thread.js
- client/src/theme/styles/components/global/annotation/footerButton.js
Resolves MNFLD-970:
* Ensure comment pages after first are fetched correctly
* Add hide comments toggle
* Refresh comments and open thread on create
> [B][E] Improve comment thread behavior

- api/app/controllers/concerns/validation.rb
- api/app/models/content/resources_block.rb
- api/app/models/resource.rb
- api/app/serializers/v1/content/resources_block_serializer.rb
- api/app/serializers/v1/resource_serializer.rb
- api/db/migrate/20250210230256_add_sort_order_to_resources.rb
- api/db/structure.sql
- client/src/api/resources/resourceCollections.js
- client/src/backend/components/content-block/TypeForm/types/Resources.js
- client/src/backend/components/list/EntitiesList/Entity/ResourceRow.js
- client/src/backend/containers/resource-collection/Resources.js
- client/src/backend/containers/resource-collection/breadcrumbs.js
- client/src/backend/containers/resource/Properties.js
- client/src/config/app/locale/en-US/json/backend/layout.json
- client/src/config/app/locale/en-US/json/backend/resources.json
- client/src/frontend/components/content-block/types/Resources.js
- client/src/hoc/withFilteredLists/resourceFilters.js
Also resolves MNFLD-975, MNFLD-954
> [F] Improve control of resource list displays

- client/src/global/components/Annotation/Annotation/UserContent/Flag/Modal.js
- client/src/global/components/Annotation/Annotation/UserContent/Flag/Toggle.js
- client/src/global/components/Annotation/Annotation/UserContent/Flag/styles.js
- Switch toggle label to "report"
- Ensure modal responds to color scheme
> [E][B] Update reader flag UI

- client/src/config/app/locale/en-US/json/backend/layout.json
- client/src/frontend/components/content-block/types/Resources.js
- client/src/frontend/components/resource-list/Thumbnails/styles.js
- client/src/frontend/components/resource/Card/Preview/styles.js
- client/src/frontend/components/resource/Card/styles.js
- client/src/frontend/components/resourceish/Thumbnail/styles.js
- client/src/global/components/FatalError/styles.js
- client/src/global/components/atomic/HeaderLogo/styles.js
- client/src/reader/components/notation/viewer/Link.js
- client/src/theme/styles/components/global/buttons.js
Resolves MNFLD-995
Resolves MNFLD-996
Resolves MNFLD-999
Resolves MNFLD-1000
Resolves MNFLD-1001
Resolves MNFLD-1003
> [B] Misc a11y fixes

- client/src/global/components/UserMenuButton/styles.js
- client/src/global/components/atomic/Breadcrumbs/Frontend/styles.js
- client/src/theme/styles/components/global/header/modeButton.js
- client/src/theme/styles/components/reader/annotations/marker.js
- client/src/theme/styles/components/reader/search/menu.js
- client/src/theme/styles/components/reader/textSection.js
- client/src/theme/styles/variables/colors.js
Resolves MNFLD-923
Resolves MNFLD-1006
> [B] Misc a11y improvements

- client/src/config/app/locale/en-US/json/shared/utility.json
- client/src/global/components/drawer/Content/index.js
- client/src/global/components/drawer/Content/styles.js
- client/src/global/components/drawer/Wrapper/index.js
- client/src/hoc/withReadingGroups/index.js
- client/src/reader/components/notes/FilteredList.js
- client/src/reader/components/notes/ReaderDrawer.js
- client/src/reader/containers/ReaderFullNotes/index.js
> [B] Notes overlay fixes

- client/src/frontend/components/resource/Link/index.js
- client/src/global/components/form/GeneratedPasswordInput/index.js
Resolves MNFLD-1020 and MNFLD-1019
> [B] Ensure file resources download as correct type

- api/app/serializers/v1/content/resources_block_serializer.rb
- client/src/backend/components/content-block/helpers/draggableEvent.js
- client/src/config/app/locale/en-US/json/backend/projects.json
Also resolves MNFLD-1023 and MNFLD-1027
> [B][E] Various v9 fixes

- client/src/frontend/components/content-block/types/Texts.js
- client/src/frontend/components/text-list/List/index.js
- client/src/frontend/components/text-list/List/styles.js
- client/src/frontend/components/text/styles.js
- client/src/global/components/FatalError/index.js
- **[B] Render HTML meta on fatal error screen**
- **[B] Show border between text categories when labels hidden**
- **[B] Adjust Text collectable toggle position**
> [B] Few small client bug fixes

- api/app/models/ingestion_source.rb
- api/app/models/text.rb
- api/app/services/packaging/epub_v3/ingestion_source_item.rb
> [B] Address issue with nil source paths when packaging epubs

- client/src/global/components/FatalError/index.js
Resolves issue introduced by 4168d42
> [B] Fix SSR exception from HeadContent render in FatalError

- client/src/global/components/UserMenuBody/styles.js
- client/src/reader/components/Header/index.js
- client/src/theme/styles/components/reader/readerHeader.js
- client/src/theme/styles/utility/zStack.js
> [B] Dialog bug fixes

- api/app/models/journal_issue.rb
- api/app/serializers/v1/concerns/project_serializer.rb
- api/app/serializers/v1/journal_issue_serializer.rb
- api/app/serializers/v1/text_serializer.rb
- client/src/api/notifications.js
- client/src/backend/components/category/List/index.js
- client/src/backend/components/content-block/TypeForm/index.js
- client/src/backend/components/content-block/TypeForm/types/Markdown.js
- client/src/backend/components/content-block/TypeForm/types/TableOfContents.js
- client/src/backend/components/content-block/TypeForm/types/Texts.js
- client/src/backend/components/content-block/TypeForm/types/index.js
- client/src/backend/containers/project/Texts.js
- client/src/backend/containers/text/Sections.js
- client/src/backend/containers/text/Wrapper.js
- client/src/backend/routes.js
- client/src/config/app/locale/en-US/json/shared/notifications.json
- client/src/frontend/containers/Home/useFetchHomepageContent.js
- client/src/global/components/drawer/Content/index.js
- client/src/global/components/drawer/FrontMatter/index.js
Also resolves:
- MNFLD-1056
- MNFLD-1064
> [B] Various admin fixes
